// 追加300語（ニュース150 + TOEIC生活150）
const WORDS_EXTRA = [
  { en: "ambassador", pos: "名詞", kana: "アンバサダー", ja: "大使", ex: "The briefing highlighted ambassador in today's update.", exJa: "今日の報告では大使が取り上げられた。", cat: "ニュース" },
  { en: "embassy", pos: "名詞", kana: "エンバシー", ja: "大使館", ex: "The briefing highlighted embassy in today's update.", exJa: "今日の報告では大使館が取り上げられた。", cat: "ニュース" },
  { en: "envoy", pos: "名詞", kana: "エンボイ", ja: "特使", ex: "The briefing highlighted envoy in today's update.", exJa: "今日の報告では特使が取り上げられた。", cat: "ニュース" },
  { en: "delegate", pos: "名詞", kana: "デリゲイト", ja: "代表者", ex: "The briefing highlighted delegate in today's update.", exJa: "今日の報告では代表者が取り上げられた。", cat: "ニュース" },
  { en: "delegation", pos: "名詞", kana: "デレゲーション", ja: "代表団", ex: "The briefing highlighted delegation in today's update.", exJa: "今日の報告では代表団が取り上げられた。", cat: "ニュース" },
  { en: "bilateral", pos: "名詞", kana: "バイラテラル", ja: "二国間", ex: "The briefing highlighted bilateral in today's update.", exJa: "今日の報告では二国間が取り上げられた。", cat: "ニュース" },
  { en: "multilateral", pos: "名詞", kana: "マルチラテラル", ja: "多国間", ex: "The briefing highlighted multilateral in today's update.", exJa: "今日の報告では多国間が取り上げられた。", cat: "ニュース" },
  { en: "communique", pos: "名詞", kana: "コミュニケ", ja: "公式声明", ex: "The briefing highlighted communique in today's update.", exJa: "今日の報告では公式声明が取り上げられた。", cat: "ニュース" },
  { en: "jurisdiction", pos: "名詞", kana: "ジュリスディクション", ja: "管轄権", ex: "The briefing highlighted jurisdiction in today's update.", exJa: "今日の報告では管轄権が取り上げられた。", cat: "ニュース" },
  { en: "tribunal", pos: "名詞", kana: "トライビューナル", ja: "裁判所", ex: "The briefing highlighted tribunal in today's update.", exJa: "今日の報告では裁判所が取り上げられた。", cat: "ニュース" },
  { en: "indictment", pos: "名詞", kana: "インダイトメント", ja: "起訴", ex: "The briefing highlighted indictment in today's update.", exJa: "今日の報告では起訴が取り上げられた。", cat: "ニュース" },
  { en: "arbitration", pos: "名詞", kana: "アービトレーション", ja: "仲裁", ex: "The briefing highlighted arbitration in today's update.", exJa: "今日の報告では仲裁が取り上げられた。", cat: "ニュース" },
  { en: "watchdog", pos: "名詞", kana: "ウォッチドッグ", ja: "監視機関", ex: "The briefing highlighted watchdog in today's update.", exJa: "今日の報告では監視機関が取り上げられた。", cat: "ニュース" },
  { en: "whistleblower", pos: "名詞", kana: "ホイッスルブロワー", ja: "内部告発者", ex: "The briefing highlighted whistleblower in today's update.", exJa: "今日の報告では内部告発者が取り上げられた。", cat: "ニュース" },
  { en: "disinformation", pos: "名詞", kana: "ディスインフォメーション", ja: "偽情報", ex: "The briefing highlighted disinformation in today's update.", exJa: "今日の報告では偽情報が取り上げられた。", cat: "ニュース" },
  { en: "narrative", pos: "名詞", kana: "ナラティブ", ja: "語り口", ex: "The briefing highlighted narrative in today's update.", exJa: "今日の報告では語り口が取り上げられた。", cat: "ニュース" },
  { en: "rhetoric", pos: "名詞", kana: "レトリック", ja: "政治的言辞", ex: "The briefing highlighted rhetoric in today's update.", exJa: "今日の報告では政治的言辞が取り上げられた。", cat: "ニュース" },
  { en: "briefing", pos: "名詞", kana: "ブリーフィング", ja: "記者説明", ex: "The briefing highlighted briefing in today's update.", exJa: "今日の報告では記者説明が取り上げられた。", cat: "ニュース" },
  { en: "spokesperson", pos: "名詞", kana: "スポークスパーソン", ja: "報道官", ex: "The briefing highlighted spokesperson in today's update.", exJa: "今日の報告では報道官が取り上げられた。", cat: "ニュース" },
  { en: "correspondent", pos: "名詞", kana: "コレスポンデント", ja: "特派員", ex: "The briefing highlighted correspondent in today's update.", exJa: "今日の報告では特派員が取り上げられた。", cat: "ニュース" },
  { en: "bureau", pos: "名詞", kana: "ビューロー", ja: "支局", ex: "The briefing highlighted bureau in today's update.", exJa: "今日の報告では支局が取り上げられた。", cat: "ニュース" },
  { en: "separatist", pos: "名詞", kana: "セパラティスト", ja: "分離主義者", ex: "The briefing highlighted separatist in today's update.", exJa: "今日の報告では分離主義者が取り上げられた。", cat: "ニュース" },
  { en: "extremism", pos: "名詞", kana: "エクストリーミズム", ja: "過激主義", ex: "The briefing highlighted extremism in today's update.", exJa: "今日の報告では過激主義が取り上げられた。", cat: "ニュース" },
  { en: "radicalization", pos: "名詞", kana: "ラディカライゼーション", ja: "過激化", ex: "The briefing highlighted radicalization in today's update.", exJa: "今日の報告では過激化が取り上げられた。", cat: "ニュース" },
  { en: "flashpoint", pos: "名詞", kana: "フラッシュポイント", ja: "緊張地域", ex: "The briefing highlighted flashpoint in today's update.", exJa: "今日の報告では緊張地域が取り上げられた。", cat: "ニュース" },
  { en: "crackdown", pos: "名詞", kana: "クラックダウン", ja: "取り締まり強化", ex: "The briefing highlighted crackdown in today's update.", exJa: "今日の報告では取り締まり強化が取り上げられた。", cat: "ニュース" },
  { en: "curfew", pos: "名詞", kana: "カーフュー", ja: "外出禁止令", ex: "The briefing highlighted curfew in today's update.", exJa: "今日の報告では外出禁止令が取り上げられた。", cat: "ニュース" },
  { en: "checkpoint", pos: "名詞", kana: "チェックポイント", ja: "検問所", ex: "The briefing highlighted checkpoint in today's update.", exJa: "今日の報告では検問所が取り上げられた。", cat: "ニュース" },
  { en: "repatriation", pos: "名詞", kana: "リパトリエーション", ja: "本国送還", ex: "The briefing highlighted repatriation in today's update.", exJa: "今日の報告では本国送還が取り上げられた。", cat: "ニュース" },
  { en: "detention", pos: "名詞", kana: "ディテンション", ja: "拘束", ex: "The briefing highlighted detention in today's update.", exJa: "今日の報告では拘束が取り上げられた。", cat: "ニュース" },
  { en: "detainee", pos: "名詞", kana: "ディテイニー", ja: "被拘束者", ex: "The briefing highlighted detainee in today's update.", exJa: "今日の報告では被拘束者が取り上げられた。", cat: "ニュース" },
  { en: "custody", pos: "名詞", kana: "カスタディ", ja: "拘留", ex: "The briefing highlighted custody in today's update.", exJa: "今日の報告では拘留が取り上げられた。", cat: "ニュース" },
  { en: "incursion", pos: "名詞", kana: "インカージョン", ja: "侵入", ex: "The briefing highlighted incursion in today's update.", exJa: "今日の報告では侵入が取り上げられた。", cat: "ニュース" },
  { en: "skirmish", pos: "名詞", kana: "スカーミッシュ", ja: "小競り合い", ex: "The briefing highlighted skirmish in today's update.", exJa: "今日の報告では小競り合いが取り上げられた。", cat: "ニュース" },
  { en: "shelling", pos: "名詞", kana: "シェリング", ja: "砲撃", ex: "The briefing highlighted shelling in today's update.", exJa: "今日の報告では砲撃が取り上げられた。", cat: "ニュース" },
  { en: "crossfire", pos: "名詞", kana: "クロスファイア", ja: "銃撃戦", ex: "The briefing highlighted crossfire in today's update.", exJa: "今日の報告では銃撃戦が取り上げられた。", cat: "ニュース" },
  { en: "frontline", pos: "名詞", kana: "フロントライン", ja: "前線", ex: "The briefing highlighted frontline in today's update.", exJa: "今日の報告では前線が取り上げられた。", cat: "ニュース" },
  { en: "backchannel", pos: "名詞", kana: "バックチャネル", ja: "秘密交渉ルート", ex: "The briefing highlighted backchannel in today's update.", exJa: "今日の報告では秘密交渉ルートが取り上げられた。", cat: "ニュース" },
  { en: "deescalation", pos: "名詞", kana: "ディエスカレーション", ja: "緊張緩和", ex: "The briefing highlighted deescalation in today's update.", exJa: "今日の報告では緊張緩和が取り上げられた。", cat: "ニュース" },
  { en: "reconciliation", pos: "名詞", kana: "リコンシリエーション", ja: "和解", ex: "The briefing highlighted reconciliation in today's update.", exJa: "今日の報告では和解が取り上げられた。", cat: "ニュース" },
  { en: "normalization", pos: "名詞", kana: "ノーマライゼーション", ja: "関係正常化", ex: "The briefing highlighted normalization in today's update.", exJa: "今日の報告では関係正常化が取り上げられた。", cat: "ニュース" },
  { en: "rapprochement", pos: "名詞", kana: "ラプロシュマン", ja: "関係改善", ex: "The briefing highlighted rapprochement in today's update.", exJa: "今日の報告では関係改善が取り上げられた。", cat: "ニュース" },
  { en: "neutrality", pos: "名詞", kana: "ニュートラリティ", ja: "中立", ex: "The briefing highlighted neutrality in today's update.", exJa: "今日の報告では中立が取り上げられた。", cat: "ニュース" },
  { en: "hegemony", pos: "名詞", kana: "ヘゲモニー", ja: "覇権", ex: "The briefing highlighted hegemony in today's update.", exJa: "今日の報告では覇権が取り上げられた。", cat: "ニュース" },
  { en: "doctrine", pos: "名詞", kana: "ドクトリン", ja: "基本方針", ex: "The briefing highlighted doctrine in today's update.", exJa: "今日の報告では基本方針が取り上げられた。", cat: "ニュース" },
  { en: "ultimatum", pos: "名詞", kana: "アルティメイタム", ja: "最後通告", ex: "The briefing highlighted ultimatum in today's update.", exJa: "今日の報告では最後通告が取り上げられた。", cat: "ニュース" },
  { en: "oversight", pos: "名詞", kana: "オーバーサイト", ja: "監督", ex: "The briefing highlighted oversight in today's update.", exJa: "今日の報告では監督が取り上げられた。", cat: "ニュース" },
  { en: "ratification", pos: "名詞", kana: "ラティフィケーション", ja: "批准", ex: "The briefing highlighted ratification in today's update.", exJa: "今日の報告では批准が取り上げられた。", cat: "ニュース" },
  { en: "annexation", pos: "名詞", kana: "アネクセーション", ja: "併合", ex: "The briefing highlighted annexation in today's update.", exJa: "今日の報告では併合が取り上げられた。", cat: "ニュース" },
  { en: "statehood", pos: "名詞", kana: "ステートフッド", ja: "国家としての地位", ex: "The briefing highlighted statehood in today's update.", exJa: "今日の報告では国家としての地位が取り上げられた。", cat: "ニュース" },
  { en: "plenary", pos: "名詞", kana: "プレナリー", ja: "本会議", ex: "The briefing highlighted plenary in today's update.", exJa: "今日の報告では本会議が取り上げられた。", cat: "ニュース" },
  { en: "incumbent", pos: "名詞", kana: "インカンベント", ja: "現職者", ex: "The briefing highlighted incumbent in today's update.", exJa: "今日の報告では現職者が取り上げられた。", cat: "ニュース" },
  { en: "turnout", pos: "名詞", kana: "ターンアウト", ja: "投票率", ex: "The briefing highlighted turnout in today's update.", exJa: "今日の報告では投票率が取り上げられた。", cat: "ニュース" },
  { en: "municipality", pos: "名詞", kana: "ミュニシパリティ", ja: "自治体", ex: "The briefing highlighted municipality in today's update.", exJa: "今日の報告では自治体が取り上げられた。", cat: "ニュース" },
  { en: "ordinance", pos: "名詞", kana: "オーディナンス", ja: "条例", ex: "The briefing highlighted ordinance in today's update.", exJa: "今日の報告では条例が取り上げられた。", cat: "ニュース" },
  { en: "bylaw", pos: "名詞", kana: "バイロー", ja: "細則", ex: "The briefing highlighted bylaw in today's update.", exJa: "今日の報告では細則が取り上げられた。", cat: "ニュース" },
  { en: "jurisprudence", pos: "名詞", kana: "ジュリスプルーデンス", ja: "法理学", ex: "The briefing highlighted jurisprudence in today's update.", exJa: "今日の報告では法理学が取り上げられた。", cat: "ニュース" },
  { en: "adjudication", pos: "名詞", kana: "アジュディケーション", ja: "司法判断", ex: "The briefing highlighted adjudication in today's update.", exJa: "今日の報告では司法判断が取り上げられた。", cat: "ニュース" },
  { en: "litigation", pos: "名詞", kana: "リティゲーション", ja: "訴訟", ex: "The briefing highlighted litigation in today's update.", exJa: "今日の報告では訴訟が取り上げられた。", cat: "ニュース" },
  { en: "settlement", pos: "名詞", kana: "セトルメント", ja: "和解金", ex: "The briefing highlighted settlement in today's update.", exJa: "今日の報告では和解金が取り上げられた。", cat: "ニュース" },
  { en: "armory", pos: "名詞", kana: "アーモリー", ja: "兵器庫", ex: "The briefing highlighted armory in today's update.", exJa: "今日の報告では兵器庫が取り上げられた。", cat: "ニュース" },
  { en: "warship", pos: "名詞", kana: "ウォーシップ", ja: "軍艦", ex: "The briefing highlighted warship in today's update.", exJa: "今日の報告では軍艦が取り上げられた。", cat: "ニュース" },
  { en: "frigate", pos: "名詞", kana: "フリゲート", ja: "フリゲート艦", ex: "The briefing highlighted frigate in today's update.", exJa: "今日の報告ではフリゲート艦が取り上げられた。", cat: "ニュース" },
  { en: "submarine", pos: "名詞", kana: "サブマリン", ja: "潜水艦", ex: "The briefing highlighted submarine in today's update.", exJa: "今日の報告では潜水艦が取り上げられた。", cat: "ニュース" },
  { en: "airspace", pos: "名詞", kana: "エアスペース", ja: "領空", ex: "The briefing highlighted airspace in today's update.", exJa: "今日の報告では領空が取り上げられた。", cat: "ニュース" },
  { en: "coastline", pos: "名詞", kana: "コーストライン", ja: "海岸線", ex: "The briefing highlighted coastline in today's update.", exJa: "今日の報告では海岸線が取り上げられた。", cat: "ニュース" },
  { en: "peninsula", pos: "名詞", kana: "ペニンシュラ", ja: "半島", ex: "The briefing highlighted peninsula in today's update.", exJa: "今日の報告では半島が取り上げられた。", cat: "ニュース" },
  { en: "strait", pos: "名詞", kana: "ストレイト", ja: "海峡", ex: "The briefing highlighted strait in today's update.", exJa: "今日の報告では海峡が取り上げられた。", cat: "ニュース" },
  { en: "maritime", pos: "名詞", kana: "マリタイム", ja: "海上の", ex: "The briefing highlighted maritime in today's update.", exJa: "今日の報告では海上のが取り上げられた。", cat: "ニュース" },
  { en: "inspectorate", pos: "名詞", kana: "インスペクトレート", ja: "監察機関", ex: "The briefing highlighted inspectorate in today's update.", exJa: "今日の報告では監察機関が取り上げられた。", cat: "ニュース" },
  { en: "taskforce", pos: "名詞", kana: "タスクフォース", ja: "特別部隊", ex: "The briefing highlighted taskforce in today's update.", exJa: "今日の報告では特別部隊が取り上げられた。", cat: "ニュース" },
  { en: "persecution", pos: "名詞", kana: "パーセキューション", ja: "迫害", ex: "The briefing highlighted persecution in today's update.", exJa: "今日の報告では迫害が取り上げられた。", cat: "ニュース" },
  { en: "oppression", pos: "名詞", kana: "オプレッション", ja: "抑圧", ex: "The briefing highlighted oppression in today's update.", exJa: "今日の報告では抑圧が取り上げられた。", cat: "ニュース" },
  { en: "massacre", pos: "名詞", kana: "マサカー", ja: "虐殺", ex: "The briefing highlighted massacre in today's update.", exJa: "今日の報告では虐殺が取り上げられた。", cat: "ニュース" },
  { en: "donor", pos: "名詞", kana: "ドナー", ja: "支援提供者", ex: "The briefing highlighted donor in today's update.", exJa: "今日の報告では支援提供者が取り上げられた。", cat: "ニュース" },
  { en: "funding", pos: "名詞", kana: "ファンディング", ja: "資金供給", ex: "The briefing highlighted funding in today's update.", exJa: "今日の報告では資金供給が取り上げられた。", cat: "ニュース" },
  { en: "allocation", pos: "名詞", kana: "アロケーション", ja: "配分", ex: "The briefing highlighted allocation in today's update.", exJa: "今日の報告では配分が取り上げられた。", cat: "ニュース" },
  { en: "distribution", pos: "名詞", kana: "ディストリビューション", ja: "配布", ex: "The briefing highlighted distribution in today's update.", exJa: "今日の報告では配布が取り上げられた。", cat: "ニュース" },
  { en: "corridor", pos: "名詞", kana: "コリドー", ja: "回廊", ex: "The briefing highlighted corridor in today's update.", exJa: "今日の報告では回廊が取り上げられた。", cat: "ニュース" },
  { en: "evacuee", pos: "名詞", kana: "イバキュイー", ja: "避難民", ex: "The briefing highlighted evacuee in today's update.", exJa: "今日の報告では避難民が取り上げられた。", cat: "ニュース" },
  { en: "remittance", pos: "名詞", kana: "リミッタンス", ja: "送金", ex: "The briefing highlighted remittance in today's update.", exJa: "今日の報告では送金が取り上げられた。", cat: "ニュース" },
  { en: "smuggler", pos: "名詞", kana: "スマグラー", ja: "密輸業者", ex: "The briefing highlighted smuggler in today's update.", exJa: "今日の報告では密輸業者が取り上げられた。", cat: "ニュース" },
  { en: "trafficking", pos: "名詞", kana: "トラフィッキング", ja: "不正取引", ex: "The briefing highlighted trafficking in today's update.", exJa: "今日の報告では不正取引が取り上げられた。", cat: "ニュース" },
  { en: "piracy", pos: "名詞", kana: "パイラシー", ja: "海賊行為", ex: "The briefing highlighted piracy in today's update.", exJa: "今日の報告では海賊行為が取り上げられた。", cat: "ニュース" },
  { en: "hostility", pos: "名詞", kana: "ホスティリティ", ja: "敵対行為", ex: "The briefing highlighted hostility in today's update.", exJa: "今日の報告では敵対行為が取り上げられた。", cat: "ニュース" },
  { en: "deterrent", pos: "名詞", kana: "ディターラント", ja: "抑止要因", ex: "The briefing highlighted deterrent in today's update.", exJa: "今日の報告では抑止要因が取り上げられた。", cat: "ニュース" },
  { en: "countermeasure", pos: "名詞", kana: "カウンターメジャー", ja: "対抗措置", ex: "The briefing highlighted countermeasure in today's update.", exJa: "今日の報告では対抗措置が取り上げられた。", cat: "ニュース" },
  { en: "standstill", pos: "名詞", kana: "スタンドスティル", ja: "行き詰まり", ex: "The briefing highlighted standstill in today's update.", exJa: "今日の報告では行き詰まりが取り上げられた。", cat: "ニュース" },
  { en: "withdrawal", pos: "名詞", kana: "ウィズドローアル", ja: "撤退", ex: "The briefing highlighted withdrawal in today's update.", exJa: "今日の報告では撤退が取り上げられた。", cat: "ニュース" },
  { en: "customs", pos: "名詞", kana: "カスタムズ", ja: "税関", ex: "The briefing highlighted customs in today's update.", exJa: "今日の報告では税関が取り上げられた。", cat: "ニュース" },
  { en: "boycott", pos: "名詞", kana: "ボイコット", ja: "不買運動", ex: "The briefing highlighted boycott in today's update.", exJa: "今日の報告では不買運動が取り上げられた。", cat: "ニュース" },
  { en: "quarantine", pos: "名詞", kana: "クアランティーン", ja: "隔離措置", ex: "The briefing highlighted quarantine in today's update.", exJa: "今日の報告では隔離措置が取り上げられた。", cat: "ニュース" },
  { en: "monitoring", pos: "名詞", kana: "モニタリング", ja: "監視活動", ex: "The briefing highlighted monitoring in today's update.", exJa: "今日の報告では監視活動が取り上げられた。", cat: "ニュース" },
  { en: "sanctuary", pos: "名詞", kana: "サンクチュアリ", ja: "保護区域", ex: "The briefing highlighted sanctuary in today's update.", exJa: "今日の報告では保護区域が取り上げられた。", cat: "ニュース" },
  { en: "insurgents", pos: "名詞", kana: "インサージェンツ", ja: "反乱勢力", ex: "The briefing highlighted insurgents in today's update.", exJa: "今日の報告では反乱勢力が取り上げられた。", cat: "ニュース" },
  { en: "uprising", pos: "名詞", kana: "アップライジング", ja: "蜂起", ex: "The briefing highlighted uprising in today's update.", exJa: "今日の報告では蜂起が取り上げられた。", cat: "ニュース" },
  { en: "standoff", pos: "名詞", kana: "スタンドオフ", ja: "にらみ合い", ex: "The briefing highlighted standoff in today's update.", exJa: "今日の報告ではにらみ合いが取り上げられた。", cat: "ニュース" },
  { en: "truce line", pos: "名詞", kana: "トゥルースライン", ja: "停戦ライン", ex: "The briefing highlighted truce line in today's update.", exJa: "今日の報告では停戦ラインが取り上げられた。", cat: "ニュース" },
  { en: "peace process", pos: "名詞", kana: "ピースプロセス", ja: "和平プロセス", ex: "The briefing highlighted peace process in today's update.", exJa: "今日の報告では和平プロセスが取り上げられた。", cat: "ニュース" },
  { en: "demarcation", pos: "名詞", kana: "ディマーケーション", ja: "境界画定", ex: "The briefing highlighted demarcation in today's update.", exJa: "今日の報告では境界画定が取り上げられた。", cat: "ニュース" },
  { en: "red line", pos: "名詞", kana: "レッドライン", ja: "越えてはならない一線", ex: "The briefing highlighted red line in today's update.", exJa: "今日の報告では越えてはならない一線が取り上げられた。", cat: "ニュース" },
  { en: "proxy", pos: "名詞", kana: "プロキシ", ja: "代理勢力", ex: "The briefing highlighted proxy in today's update.", exJa: "今日の報告では代理勢力が取り上げられた。", cat: "ニュース" },
  { en: "firepower", pos: "名詞", kana: "ファイアパワー", ja: "火力", ex: "The briefing highlighted firepower in today's update.", exJa: "今日の報告では火力が取り上げられた。", cat: "ニュース" },
  { en: "mobilization", pos: "名詞", kana: "モビライゼーション", ja: "動員", ex: "The briefing highlighted mobilization in today's update.", exJa: "今日の報告では動員が取り上げられた。", cat: "ニュース" },
  { en: "conscription", pos: "名詞", kana: "コンスクリプション", ja: "徴兵", ex: "The briefing highlighted conscription in today's update.", exJa: "今日の報告では徴兵が取り上げられた。", cat: "ニュース" },
  { en: "demobilization", pos: "名詞", kana: "ディモビライゼーション", ja: "動員解除", ex: "The briefing highlighted demobilization in today's update.", exJa: "今日の報告では動員解除が取り上げられた。", cat: "ニュース" },
  { en: "safe zone", pos: "名詞", kana: "セーフゾーン", ja: "安全地帯", ex: "The briefing highlighted safe zone in today's update.", exJa: "今日の報告では安全地帯が取り上げられた。", cat: "ニュース" },
  { en: "buffer zone", pos: "名詞", kana: "バッファーゾーン", ja: "緩衝地帯", ex: "The briefing highlighted buffer zone in today's update.", exJa: "今日の報告では緩衝地帯が取り上げられた。", cat: "ニュース" },
  { en: "landmine", pos: "名詞", kana: "ランドマイン", ja: "地雷", ex: "The briefing highlighted landmine in today's update.", exJa: "今日の報告では地雷が取り上げられた。", cat: "ニュース" },
  { en: "ordinance team", pos: "名詞", kana: "オーディナンスティーム", ja: "兵器処理班", ex: "The briefing highlighted ordinance team in today's update.", exJa: "今日の報告では兵器処理班が取り上げられた。", cat: "ニュース" },
  { en: "fact-finding", pos: "名詞", kana: "ファクトファインディング", ja: "事実調査", ex: "The briefing highlighted fact-finding in today's update.", exJa: "今日の報告では事実調査が取り上げられた。", cat: "ニュース" },
  { en: "observer mission", pos: "名詞", kana: "オブザーバーミッション", ja: "監視団派遣", ex: "The briefing highlighted observer mission in today's update.", exJa: "今日の報告では監視団派遣が取り上げられた。", cat: "ニュース" },
  { en: "peace envoy", pos: "名詞", kana: "ピースエンボイ", ja: "和平特使", ex: "The briefing highlighted peace envoy in today's update.", exJa: "今日の報告では和平特使が取り上げられた。", cat: "ニュース" },
  { en: "confidence-building", pos: "名詞", kana: "コンフィデンスビルディング", ja: "信頼醸成", ex: "The briefing highlighted confidence-building in today's update.", exJa: "今日の報告では信頼醸成が取り上げられた。", cat: "ニュース" },
  { en: "transit route", pos: "名詞", kana: "トランジットルート", ja: "輸送経路", ex: "The briefing highlighted transit route in today's update.", exJa: "今日の報告では輸送経路が取り上げられた。", cat: "ニュース" },
  { en: "supply route", pos: "名詞", kana: "サプライルート", ja: "補給路", ex: "The briefing highlighted supply route in today's update.", exJa: "今日の報告では補給路が取り上げられた。", cat: "ニュース" },
  { en: "aid convoy", pos: "名詞", kana: "エイドコンボイ", ja: "支援車列", ex: "The briefing highlighted aid convoy in today's update.", exJa: "今日の報告では支援車列が取り上げられた。", cat: "ニュース" },
  { en: "host country", pos: "名詞", kana: "ホストカントリー", ja: "受け入れ国", ex: "The briefing highlighted host country in today's update.", exJa: "今日の報告では受け入れ国が取り上げられた。", cat: "ニュース" },
  { en: "receiving center", pos: "名詞", kana: "リシービングセンター", ja: "受け入れ施設", ex: "The briefing highlighted receiving center in today's update.", exJa: "今日の報告では受け入れ施設が取り上げられた。", cat: "ニュース" },
  { en: "screening", pos: "名詞", kana: "スクリーニング", ja: "審査", ex: "The briefing highlighted screening in today's update.", exJa: "今日の報告では審査が取り上げられた。", cat: "ニュース" },
  { en: "clearance", pos: "名詞", kana: "クリアランス", ja: "許可", ex: "The briefing highlighted clearance in today's update.", exJa: "今日の報告では許可が取り上げられた。", cat: "ニュース" },
  { en: "visa waiver", pos: "名詞", kana: "ビザウェイバー", ja: "査証免除", ex: "The briefing highlighted visa waiver in today's update.", exJa: "今日の報告では査証免除が取り上げられた。", cat: "ニュース" },
  { en: "travel advisory", pos: "名詞", kana: "トラベルアドバイザリー", ja: "渡航勧告", ex: "The briefing highlighted travel advisory in today's update.", exJa: "今日の報告では渡航勧告が取り上げられた。", cat: "ニュース" },
  { en: "border crossing", pos: "名詞", kana: "ボーダークロッシング", ja: "国境通過地点", ex: "The briefing highlighted border crossing in today's update.", exJa: "今日の報告では国境通過地点が取り上げられた。", cat: "ニュース" },
  { en: "entry point", pos: "名詞", kana: "エントリーポイント", ja: "入国地点", ex: "The briefing highlighted entry point in today's update.", exJa: "今日の報告では入国地点が取り上げられた。", cat: "ニュース" },
  { en: "exit permit", pos: "名詞", kana: "エグジットパーミット", ja: "出国許可", ex: "The briefing highlighted exit permit in today's update.", exJa: "今日の報告では出国許可が取り上げられた。", cat: "ニュース" },
  { en: "maritime lane", pos: "名詞", kana: "マリタイムレーン", ja: "海上航路", ex: "The briefing highlighted maritime lane in today's update.", exJa: "今日の報告では海上航路が取り上げられた。", cat: "ニュース" },
  { en: "air corridor", pos: "名詞", kana: "エアコリドー", ja: "航空回廊", ex: "The briefing highlighted air corridor in today's update.", exJa: "今日の報告では航空回廊が取り上げられた。", cat: "ニュース" },
  { en: "no-fly area", pos: "名詞", kana: "ノーフライエリア", ja: "飛行禁止区域", ex: "The briefing highlighted no-fly area in today's update.", exJa: "今日の報告では飛行禁止区域が取り上げられた。", cat: "ニュース" },
  { en: "joint statement", pos: "名詞", kana: "ジョイントステートメント", ja: "共同声明", ex: "The briefing highlighted joint statement in today's update.", exJa: "今日の報告では共同声明が取り上げられた。", cat: "ニュース" },
  { en: "press corps", pos: "名詞", kana: "プレスコー", ja: "記者団", ex: "The briefing highlighted press corps in today's update.", exJa: "今日の報告では記者団が取り上げられた。", cat: "ニュース" },
  { en: "photo op", pos: "名詞", kana: "フォトオプ", ja: "写真撮影機会", ex: "The briefing highlighted photo op in today's update.", exJa: "今日の報告では写真撮影機会が取り上げられた。", cat: "ニュース" },
  { en: "closed-door session", pos: "名詞", kana: "クローズドドアセッション", ja: "非公開会合", ex: "The briefing highlighted closed-door session in today's update.", exJa: "今日の報告では非公開会合が取り上げられた。", cat: "ニュース" },
  { en: "draft text", pos: "名詞", kana: "ドラフトテキスト", ja: "草案文書", ex: "The briefing highlighted draft text in today's update.", exJa: "今日の報告では草案文書が取り上げられた。", cat: "ニュース" },
  { en: "final text", pos: "名詞", kana: "ファイナルテキスト", ja: "最終文書", ex: "The briefing highlighted final text in today's update.", exJa: "今日の報告では最終文書が取り上げられた。", cat: "ニュース" },
  { en: "signatory", pos: "名詞", kana: "シグナトリー", ja: "署名国", ex: "The briefing highlighted signatory in today's update.", exJa: "今日の報告では署名国が取り上げられた。", cat: "ニュース" },
  { en: "depositary", pos: "名詞", kana: "デポジタリー", ja: "寄託者", ex: "The briefing highlighted depositary in today's update.", exJa: "今日の報告では寄託者が取り上げられた。", cat: "ニュース" },
  { en: "compliance review", pos: "名詞", kana: "コンプライアンスレビュー", ja: "履行審査", ex: "The briefing highlighted compliance review in today's update.", exJa: "今日の報告では履行審査が取り上げられた。", cat: "ニュース" },
  { en: "verification team", pos: "名詞", kana: "ベリフィケーションティーム", ja: "検証チーム", ex: "The briefing highlighted verification team in today's update.", exJa: "今日の報告では検証チームが取り上げられた。", cat: "ニュース" },
  { en: "monitoring mission", pos: "名詞", kana: "モニタリングミッション", ja: "監視任務", ex: "The briefing highlighted monitoring mission in today's update.", exJa: "今日の報告では監視任務が取り上げられた。", cat: "ニュース" },
  { en: "field office", pos: "名詞", kana: "フィールドオフィス", ja: "現地事務所", ex: "The briefing highlighted field office in today's update.", exJa: "今日の報告では現地事務所が取り上げられた。", cat: "ニュース" },
  { en: "liaison office", pos: "名詞", kana: "リエゾンオフィス", ja: "連絡事務所", ex: "The briefing highlighted liaison office in today's update.", exJa: "今日の報告では連絡事務所が取り上げられた。", cat: "ニュース" },
  { en: "policy brief", pos: "名詞", kana: "ポリシーブリーフ", ja: "政策要約", ex: "The briefing highlighted policy brief in today's update.", exJa: "今日の報告では政策要約が取り上げられた。", cat: "ニュース" },
  { en: "white paper", pos: "名詞", kana: "ホワイトペーパー", ja: "白書", ex: "The briefing highlighted white paper in today's update.", exJa: "今日の報告では白書が取り上げられた。", cat: "ニュース" },
  { en: "special session", pos: "名詞", kana: "スペシャルセッション", ja: "特別会期", ex: "The briefing highlighted special session in today's update.", exJa: "今日の報告では特別会期が取り上げられた。", cat: "ニュース" },
  { en: "floor vote", pos: "名詞", kana: "フロアボート", ja: "本会議採決", ex: "The briefing highlighted floor vote in today's update.", exJa: "今日の報告では本会議採決が取り上げられた。", cat: "ニュース" },
  { en: "voice vote", pos: "名詞", kana: "ボイスボート", ja: "声による採決", ex: "The briefing highlighted voice vote in today's update.", exJa: "今日の報告では声による採決が取り上げられた。", cat: "ニュース" },
  { en: "roll call", pos: "名詞", kana: "ロールコール", ja: "記名投票", ex: "The briefing highlighted roll call in today's update.", exJa: "今日の報告では記名投票が取り上げられた。", cat: "ニュース" },
  { en: "committee hearing", pos: "名詞", kana: "コミッティーヒアリング", ja: "委員会公聴会", ex: "The briefing highlighted committee hearing in today's update.", exJa: "今日の報告では委員会公聴会が取り上げられた。", cat: "ニュース" },
  { en: "public hearing", pos: "名詞", kana: "パブリックヒアリング", ja: "公開ヒアリング", ex: "The briefing highlighted public hearing in today's update.", exJa: "今日の報告では公開ヒアリングが取り上げられた。", cat: "ニュース" },
  { en: "appointment", pos: "名詞", kana: "アポイントメント", ja: "予約", ex: "I checked the appointment before leaving for work.", exJa: "出勤前に予約を確認した。", cat: "生活" },
  { en: "reservation", pos: "名詞", kana: "レザベーション", ja: "予約席", ex: "I checked the reservation before leaving for work.", exJa: "出勤前に予約席を確認した。", cat: "生活" },
  { en: "itinerary", pos: "名詞", kana: "アイティナラリー", ja: "旅程", ex: "I checked the itinerary before leaving for work.", exJa: "出勤前に旅程を確認した。", cat: "生活" },
  { en: "boarding pass", pos: "名詞", kana: "ボーディングパス", ja: "搭乗券", ex: "I checked the boarding pass before leaving for work.", exJa: "出勤前に搭乗券を確認した。", cat: "生活" },
  { en: "platform number", pos: "名詞", kana: "プラットフォームナンバー", ja: "乗り場番号", ex: "I checked the platform number before leaving for work.", exJa: "出勤前に乗り場番号を確認した。", cat: "生活" },
  { en: "transfer", pos: "名詞", kana: "トランスファー", ja: "乗り換え", ex: "I checked the transfer before leaving for work.", exJa: "出勤前に乗り換えを確認した。", cat: "生活" },
  { en: "commute", pos: "名詞", kana: "コミュート", ja: "通勤", ex: "I checked the commute before leaving for work.", exJa: "出勤前に通勤を確認した。", cat: "生活" },
  { en: "detour", pos: "名詞", kana: "ディトゥア", ja: "迂回路", ex: "I checked the detour before leaving for work.", exJa: "出勤前に迂回路を確認した。", cat: "生活" },
  { en: "intersection", pos: "名詞", kana: "インターセクション", ja: "交差点", ex: "I checked the intersection before leaving for work.", exJa: "出勤前に交差点を確認した。", cat: "生活" },
  { en: "crosswalk", pos: "名詞", kana: "クロスウォーク", ja: "横断歩道", ex: "I checked the crosswalk before leaving for work.", exJa: "出勤前に横断歩道を確認した。", cat: "生活" },
  { en: "fare", pos: "名詞", kana: "フェア", ja: "運賃", ex: "I checked the fare before leaving for work.", exJa: "出勤前に運賃を確認した。", cat: "生活" },
  { en: "refund", pos: "名詞", kana: "リファンド", ja: "払い戻し", ex: "I checked the refund before leaving for work.", exJa: "出勤前に払い戻しを確認した。", cat: "生活" },
  { en: "receipt", pos: "名詞", kana: "レシート", ja: "領収書", ex: "I checked the receipt before leaving for work.", exJa: "出勤前に領収書を確認した。", cat: "生活" },
  { en: "invoice", pos: "名詞", kana: "インボイス", ja: "請求書", ex: "I checked the invoice before leaving for work.", exJa: "出勤前に請求書を確認した。", cat: "生活" },
  { en: "quotation", pos: "名詞", kana: "クオーテーション", ja: "見積書", ex: "I checked the quotation before leaving for work.", exJa: "出勤前に見積書を確認した。", cat: "生活" },
  { en: "deadline", pos: "名詞", kana: "デッドライン", ja: "締め切り", ex: "I checked the deadline before leaving for work.", exJa: "出勤前に締め切りを確認した。", cat: "生活" },
  { en: "extension", pos: "名詞", kana: "エクステンション", ja: "延長", ex: "I checked the extension before leaving for work.", exJa: "出勤前に延長を確認した。", cat: "生活" },
  { en: "approval form", pos: "名詞", kana: "アプルーバルフォーム", ja: "承認書", ex: "I checked the approval form before leaving for work.", exJa: "出勤前に承認書を確認した。", cat: "生活" },
  { en: "signature", pos: "名詞", kana: "シグネチャー", ja: "署名", ex: "I checked the signature before leaving for work.", exJa: "出勤前に署名を確認した。", cat: "生活" },
  { en: "initials", pos: "名詞", kana: "イニシャルズ", ja: "頭文字署名", ex: "I checked the initials before leaving for work.", exJa: "出勤前に頭文字署名を確認した。", cat: "生活" },
  { en: "memo", pos: "名詞", kana: "メモ", ja: "社内メモ", ex: "I checked the memo before leaving for work.", exJa: "出勤前に社内メモを確認した。", cat: "生活" },
  { en: "minutes", pos: "名詞", kana: "ミニッツ", ja: "議事録", ex: "I checked the minutes before leaving for work.", exJa: "出勤前に議事録を確認した。", cat: "生活" },
  { en: "agenda item", pos: "名詞", kana: "アジェンダアイテム", ja: "議題項目", ex: "I checked the agenda item before leaving for work.", exJa: "出勤前に議題項目を確認した。", cat: "生活" },
  { en: "conference room", pos: "名詞", kana: "カンファレンスルーム", ja: "会議室", ex: "I checked the conference room before leaving for work.", exJa: "出勤前に会議室を確認した。", cat: "生活" },
  { en: "workstation", pos: "名詞", kana: "ワークステーション", ja: "作業席", ex: "I checked the workstation before leaving for work.", exJa: "出勤前に作業席を確認した。", cat: "生活" },
  { en: "cafeteria", pos: "名詞", kana: "カフェテリア", ja: "社員食堂", ex: "I checked the cafeteria before leaving for work.", exJa: "出勤前に社員食堂を確認した。", cat: "生活" },
  { en: "vendor", pos: "名詞", kana: "ベンダー", ja: "取引先", ex: "I checked the vendor before leaving for work.", exJa: "出勤前に取引先を確認した。", cat: "生活" },
  { en: "client meeting", pos: "名詞", kana: "クライアントミーティング", ja: "顧客打ち合わせ", ex: "I checked the client meeting before leaving for work.", exJa: "出勤前に顧客打ち合わせを確認した。", cat: "生活" },
  { en: "follow-up", pos: "名詞", kana: "フォローアップ", ja: "追跡連絡", ex: "I checked the follow-up before leaving for work.", exJa: "出勤前に追跡連絡を確認した。", cat: "生活" },
  { en: "reminder", pos: "名詞", kana: "リマインダー", ja: "通知", ex: "I checked the reminder before leaving for work.", exJa: "出勤前に通知を確認した。", cat: "生活" },
  { en: "schedule", pos: "名詞", kana: "スケジュール", ja: "予定", ex: "I checked the schedule before leaving for work.", exJa: "出勤前に予定を確認した。", cat: "生活" },
  { en: "calendar", pos: "名詞", kana: "カレンダー", ja: "予定表", ex: "I checked the calendar before leaving for work.", exJa: "出勤前に予定表を確認した。", cat: "生活" },
  { en: "postponement", pos: "名詞", kana: "ポストポーンメント", ja: "延期", ex: "I checked the postponement before leaving for work.", exJa: "出勤前に延期を確認した。", cat: "生活" },
  { en: "cancellation", pos: "名詞", kana: "キャンセレーション", ja: "取り消し", ex: "I checked the cancellation before leaving for work.", exJa: "出勤前に取り消しを確認した。", cat: "生活" },
  { en: "attendance", pos: "名詞", kana: "アテンダンス", ja: "出席", ex: "I checked the attendance before leaving for work.", exJa: "出勤前に出席を確認した。", cat: "生活" },
  { en: "absence", pos: "名詞", kana: "アブセンス", ja: "欠席", ex: "I checked the absence before leaving for work.", exJa: "出勤前に欠席を確認した。", cat: "生活" },
  { en: "overtime", pos: "名詞", kana: "オーバータイム", ja: "残業", ex: "I checked the overtime before leaving for work.", exJa: "出勤前に残業を確認した。", cat: "生活" },
  { en: "shift", pos: "名詞", kana: "シフト", ja: "勤務帯", ex: "I checked the shift before leaving for work.", exJa: "出勤前に勤務帯を確認した。", cat: "生活" },
  { en: "payroll", pos: "名詞", kana: "ペイロール", ja: "給与台帳", ex: "I checked the payroll before leaving for work.", exJa: "出勤前に給与台帳を確認した。", cat: "生活" },
  { en: "allowance", pos: "名詞", kana: "アローワンス", ja: "手当", ex: "I checked the allowance before leaving for work.", exJa: "出勤前に手当を確認した。", cat: "生活" },
  { en: "bonus", pos: "名詞", kana: "ボーナス", ja: "賞与", ex: "I checked the bonus before leaving for work.", exJa: "出勤前に賞与を確認した。", cat: "生活" },
  { en: "deduction", pos: "名詞", kana: "ディダクション", ja: "控除", ex: "I checked the deduction before leaving for work.", exJa: "出勤前に控除を確認した。", cat: "生活" },
  { en: "reimbursement", pos: "名詞", kana: "リインバースメント", ja: "経費精算", ex: "I checked the reimbursement before leaving for work.", exJa: "出勤前に経費精算を確認した。", cat: "生活" },
  { en: "expense", pos: "名詞", kana: "エクスペンス", ja: "経費", ex: "I checked the expense before leaving for work.", exJa: "出勤前に経費を確認した。", cat: "生活" },
  { en: "stationery", pos: "名詞", kana: "ステーショナリー", ja: "文房具", ex: "I checked the stationery before leaving for work.", exJa: "出勤前に文房具を確認した。", cat: "生活" },
  { en: "printer", pos: "名詞", kana: "プリンター", ja: "印刷機", ex: "I checked the printer before leaving for work.", exJa: "出勤前に印刷機を確認した。", cat: "生活" },
  { en: "photocopier", pos: "名詞", kana: "フォトコピア", ja: "コピー機", ex: "I checked the photocopier before leaving for work.", exJa: "出勤前にコピー機を確認した。", cat: "生活" },
  { en: "badge", pos: "名詞", kana: "バッジ", ja: "社員証", ex: "I checked the badge before leaving for work.", exJa: "出勤前に社員証を確認した。", cat: "生活" },
  { en: "password reset", pos: "名詞", kana: "パスワードリセット", ja: "パスワード再設定", ex: "I checked the password reset before leaving for work.", exJa: "出勤前にパスワード再設定を確認した。", cat: "生活" },
  { en: "login", pos: "名詞", kana: "ログイン", ja: "ログイン", ex: "I checked the login before leaving for work.", exJa: "出勤前にログインを確認した。", cat: "生活" },
  { en: "logout", pos: "名詞", kana: "ログアウト", ja: "ログアウト", ex: "I checked the logout before leaving for work.", exJa: "出勤前にログアウトを確認した。", cat: "生活" },
  { en: "attachment", pos: "名詞", kana: "アタッチメント", ja: "添付ファイル", ex: "I checked the attachment before leaving for work.", exJa: "出勤前に添付ファイルを確認した。", cat: "生活" },
  { en: "spreadsheet", pos: "名詞", kana: "スプレッドシート", ja: "表計算ファイル", ex: "I checked the spreadsheet before leaving for work.", exJa: "出勤前に表計算ファイルを確認した。", cat: "生活" },
  { en: "presentation", pos: "名詞", kana: "プレゼンテーション", ja: "発表資料", ex: "I checked the presentation before leaving for work.", exJa: "出勤前に発表資料を確認した。", cat: "生活" },
  { en: "handout", pos: "名詞", kana: "ハンドアウト", ja: "配布資料", ex: "I checked the handout before leaving for work.", exJa: "出勤前に配布資料を確認した。", cat: "生活" },
  { en: "checklist", pos: "名詞", kana: "チェックリスト", ja: "確認表", ex: "I checked the checklist before leaving for work.", exJa: "出勤前に確認表を確認した。", cat: "生活" },
  { en: "laundry", pos: "名詞", kana: "ランドリー", ja: "洗濯", ex: "I checked the laundry before leaving for work.", exJa: "出勤前に洗濯を確認した。", cat: "生活" },
  { en: "detergent", pos: "名詞", kana: "ディタージェント", ja: "洗剤", ex: "I checked the detergent before leaving for work.", exJa: "出勤前に洗剤を確認した。", cat: "生活" },
  { en: "dishwasher", pos: "名詞", kana: "ディッシュウォッシャー", ja: "食洗機", ex: "I checked the dishwasher before leaving for work.", exJa: "出勤前に食洗機を確認した。", cat: "生活" },
  { en: "microwave", pos: "名詞", kana: "マイクロウェーブ", ja: "電子レンジ", ex: "I checked the microwave before leaving for work.", exJa: "出勤前に電子レンジを確認した。", cat: "生活" },
  { en: "freezer", pos: "名詞", kana: "フリーザー", ja: "冷凍庫", ex: "I checked the freezer before leaving for work.", exJa: "出勤前に冷凍庫を確認した。", cat: "生活" },
  { en: "pantry", pos: "名詞", kana: "パントリー", ja: "食品庫", ex: "I checked the pantry before leaving for work.", exJa: "出勤前に食品庫を確認した。", cat: "生活" },
  { en: "groceries", pos: "名詞", kana: "グロサリーズ", ja: "食料品", ex: "I checked the groceries before leaving for work.", exJa: "出勤前に食料品を確認した。", cat: "生活" },
  { en: "shopping cart", pos: "名詞", kana: "ショッピングカート", ja: "買い物かご", ex: "I checked the shopping cart before leaving for work.", exJa: "出勤前に買い物かごを確認した。", cat: "生活" },
  { en: "checkout", pos: "名詞", kana: "チェックアウト", ja: "会計", ex: "I checked the checkout before leaving for work.", exJa: "出勤前に会計を確認した。", cat: "生活" },
  { en: "cashier", pos: "名詞", kana: "キャッシャー", ja: "レジ係", ex: "I checked the cashier before leaving for work.", exJa: "出勤前にレジ係を確認した。", cat: "生活" },
  { en: "discount", pos: "名詞", kana: "ディスカウント", ja: "割引", ex: "I checked the discount before leaving for work.", exJa: "出勤前に割引を確認した。", cat: "生活" },
  { en: "coupon", pos: "名詞", kana: "クーポン", ja: "割引券", ex: "I checked the coupon before leaving for work.", exJa: "出勤前に割引券を確認した。", cat: "生活" },
  { en: "loyalty card", pos: "名詞", kana: "ロイヤルティカード", ja: "ポイントカード", ex: "I checked the loyalty card before leaving for work.", exJa: "出勤前にポイントカードを確認した。", cat: "生活" },
  { en: "warranty", pos: "名詞", kana: "ワランティ", ja: "保証", ex: "I checked the warranty before leaving for work.", exJa: "出勤前に保証を確認した。", cat: "生活" },
  { en: "exchange", pos: "名詞", kana: "エクスチェンジ", ja: "交換", ex: "I checked the exchange before leaving for work.", exJa: "出勤前に交換を確認した。", cat: "生活" },
  { en: "customer desk", pos: "名詞", kana: "カスタマーデスク", ja: "案内窓口", ex: "I checked the customer desk before leaving for work.", exJa: "出勤前に案内窓口を確認した。", cat: "生活" },
  { en: "fitting room", pos: "名詞", kana: "フィッティングルーム", ja: "試着室", ex: "I checked the fitting room before leaving for work.", exJa: "出勤前に試着室を確認した。", cat: "生活" },
  { en: "size chart", pos: "名詞", kana: "サイズチャート", ja: "サイズ表", ex: "I checked the size chart before leaving for work.", exJa: "出勤前にサイズ表を確認した。", cat: "生活" },
  { en: "delivery", pos: "名詞", kana: "デリバリー", ja: "配達", ex: "I checked the delivery before leaving for work.", exJa: "出勤前に配達を確認した。", cat: "生活" },
  { en: "tracking number", pos: "名詞", kana: "トラッキングナンバー", ja: "追跡番号", ex: "I checked the tracking number before leaving for work.", exJa: "出勤前に追跡番号を確認した。", cat: "生活" },
  { en: "mailbox", pos: "名詞", kana: "メールボックス", ja: "郵便受け", ex: "I checked the mailbox before leaving for work.", exJa: "出勤前に郵便受けを確認した。", cat: "生活" },
  { en: "parcel", pos: "名詞", kana: "パーセル", ja: "小包", ex: "I checked the parcel before leaving for work.", exJa: "出勤前に小包を確認した。", cat: "生活" },
  { en: "courier", pos: "名詞", kana: "クーリエ", ja: "宅配便", ex: "I checked the courier before leaving for work.", exJa: "出勤前に宅配便を確認した。", cat: "生活" },
  { en: "pickup", pos: "名詞", kana: "ピックアップ", ja: "受け取り", ex: "I checked the pickup before leaving for work.", exJa: "出勤前に受け取りを確認した。", cat: "生活" },
  { en: "drop-off", pos: "名詞", kana: "ドロップオフ", ja: "預け入れ", ex: "I checked the drop-off before leaving for work.", exJa: "出勤前に預け入れを確認した。", cat: "生活" },
  { en: "commuter pass", pos: "名詞", kana: "コミューターパス", ja: "定期券", ex: "I checked the commuter pass before leaving for work.", exJa: "出勤前に定期券を確認した。", cat: "生活" },
  { en: "one-way ticket", pos: "名詞", kana: "ワンウェイチケット", ja: "片道切符", ex: "I checked the one-way ticket before leaving for work.", exJa: "出勤前に片道切符を確認した。", cat: "生活" },
  { en: "round-trip ticket", pos: "名詞", kana: "ラウンドトリップチケット", ja: "往復切符", ex: "I checked the round-trip ticket before leaving for work.", exJa: "出勤前に往復切符を確認した。", cat: "生活" },
  { en: "seat assignment", pos: "名詞", kana: "シートアサインメント", ja: "座席指定", ex: "I checked the seat assignment before leaving for work.", exJa: "出勤前に座席指定を確認した。", cat: "生活" },
  { en: "window seat", pos: "名詞", kana: "ウィンドウシート", ja: "窓側席", ex: "I checked the window seat before leaving for work.", exJa: "出勤前に窓側席を確認した。", cat: "生活" },
  { en: "aisle seat", pos: "名詞", kana: "アイルシート", ja: "通路側席", ex: "I checked the aisle seat before leaving for work.", exJa: "出勤前に通路側席を確認した。", cat: "生活" },
  { en: "overhead bin", pos: "名詞", kana: "オーバーヘッドビン", ja: "手荷物棚", ex: "I checked the overhead bin before leaving for work.", exJa: "出勤前に手荷物棚を確認した。", cat: "生活" },
  { en: "carry-on", pos: "名詞", kana: "キャリーオン", ja: "機内持ち込み荷物", ex: "I checked the carry-on before leaving for work.", exJa: "出勤前に機内持ち込み荷物を確認した。", cat: "生活" },
  { en: "checked baggage", pos: "名詞", kana: "チェックドバゲージ", ja: "預け荷物", ex: "I checked the checked baggage before leaving for work.", exJa: "出勤前に預け荷物を確認した。", cat: "生活" },
  { en: "luggage tag", pos: "名詞", kana: "ラゲッジタグ", ja: "手荷物タグ", ex: "I checked the luggage tag before leaving for work.", exJa: "出勤前に手荷物タグを確認した。", cat: "生活" },
  { en: "hotel lobby", pos: "名詞", kana: "ホテルロビー", ja: "ホテルのロビー", ex: "I checked the hotel lobby before leaving for work.", exJa: "出勤前にホテルのロビーを確認した。", cat: "生活" },
  { en: "front desk", pos: "名詞", kana: "フロントデスク", ja: "受付", ex: "I checked the front desk before leaving for work.", exJa: "出勤前に受付を確認した。", cat: "生活" },
  { en: "room key", pos: "名詞", kana: "ルームキー", ja: "部屋の鍵", ex: "I checked the room key before leaving for work.", exJa: "出勤前に部屋の鍵を確認した。", cat: "生活" },
  { en: "wake-up call", pos: "名詞", kana: "ウェイクアップコール", ja: "モーニングコール", ex: "I checked the wake-up call before leaving for work.", exJa: "出勤前にモーニングコールを確認した。", cat: "生活" },
  { en: "housekeeping", pos: "名詞", kana: "ハウスキーピング", ja: "客室清掃", ex: "I checked the housekeeping before leaving for work.", exJa: "出勤前に客室清掃を確認した。", cat: "生活" },
  { en: "room service", pos: "名詞", kana: "ルームサービス", ja: "部屋サービス", ex: "I checked the room service before leaving for work.", exJa: "出勤前に部屋サービスを確認した。", cat: "生活" },
  { en: "check-in", pos: "名詞", kana: "チェックイン", ja: "宿泊手続き", ex: "I checked the check-in before leaving for work.", exJa: "出勤前に宿泊手続きを確認した。", cat: "生活" },
  { en: "late checkout", pos: "名詞", kana: "レイトチェックアウト", ja: "遅めの退室", ex: "I checked the late checkout before leaving for work.", exJa: "出勤前に遅めの退室を確認した。", cat: "生活" },
  { en: "vacancy", pos: "名詞", kana: "ベイカンシー", ja: "空室", ex: "I checked the vacancy before leaving for work.", exJa: "出勤前に空室を確認した。", cat: "生活" },
  { en: "amenity", pos: "名詞", kana: "アメニティ", ja: "備品", ex: "I checked the amenity before leaving for work.", exJa: "出勤前に備品を確認した。", cat: "生活" },
  { en: "toiletries", pos: "名詞", kana: "トイレタリーズ", ja: "洗面用品", ex: "I checked the toiletries before leaving for work.", exJa: "出勤前に洗面用品を確認した。", cat: "生活" },
  { en: "prescription", pos: "名詞", kana: "プリスクリプション", ja: "処方箋", ex: "I checked the prescription before leaving for work.", exJa: "出勤前に処方箋を確認した。", cat: "生活" },
  { en: "pharmacy", pos: "名詞", kana: "ファーマシー", ja: "薬局", ex: "I checked the pharmacy before leaving for work.", exJa: "出勤前に薬局を確認した。", cat: "生活" },
  { en: "clinic", pos: "名詞", kana: "クリニック", ja: "診療所", ex: "I checked the clinic before leaving for work.", exJa: "出勤前に診療所を確認した。", cat: "生活" },
  { en: "checkup", pos: "名詞", kana: "チェックアップ", ja: "健康診断", ex: "I checked the checkup before leaving for work.", exJa: "出勤前に健康診断を確認した。", cat: "生活" },
  { en: "symptom log", pos: "名詞", kana: "シンプトムログ", ja: "症状記録", ex: "I checked the symptom log before leaving for work.", exJa: "出勤前に症状記録を確認した。", cat: "生活" },
  { en: "allergy", pos: "名詞", kana: "アレルジー", ja: "アレルギー", ex: "I checked the allergy before leaving for work.", exJa: "出勤前にアレルギーを確認した。", cat: "生活" },
  { en: "bandage", pos: "名詞", kana: "バンデージ", ja: "包帯", ex: "I checked the bandage before leaving for work.", exJa: "出勤前に包帯を確認した。", cat: "生活" },
  { en: "thermometer", pos: "名詞", kana: "サーモメーター", ja: "体温計", ex: "I checked the thermometer before leaving for work.", exJa: "出勤前に体温計を確認した。", cat: "生活" },
  { en: "insurance card", pos: "名詞", kana: "インシュアランスカード", ja: "保険証", ex: "I checked the insurance card before leaving for work.", exJa: "出勤前に保険証を確認した。", cat: "生活" },
  { en: "copayment", pos: "名詞", kana: "コーペイメント", ja: "自己負担額", ex: "I checked the copayment before leaving for work.", exJa: "出勤前に自己負担額を確認した。", cat: "生活" },
  { en: "utility bill", pos: "名詞", kana: "ユーティリティビル", ja: "公共料金請求書", ex: "I checked the utility bill before leaving for work.", exJa: "出勤前に公共料金請求書を確認した。", cat: "生活" },
  { en: "rent", pos: "名詞", kana: "レント", ja: "家賃", ex: "I checked the rent before leaving for work.", exJa: "出勤前に家賃を確認した。", cat: "生活" },
  { en: "lease", pos: "名詞", kana: "リース", ja: "賃貸契約", ex: "I checked the lease before leaving for work.", exJa: "出勤前に賃貸契約を確認した。", cat: "生活" },
  { en: "landlord", pos: "名詞", kana: "ランドロード", ja: "家主", ex: "I checked the landlord before leaving for work.", exJa: "出勤前に家主を確認した。", cat: "生活" },
  { en: "tenant", pos: "名詞", kana: "テナント", ja: "入居者", ex: "I checked the tenant before leaving for work.", exJa: "出勤前に入居者を確認した。", cat: "生活" },
  { en: "maintenance", pos: "名詞", kana: "メンテナンス", ja: "修理対応", ex: "I checked the maintenance before leaving for work.", exJa: "出勤前に修理対応を確認した。", cat: "生活" },
  { en: "repair request", pos: "名詞", kana: "リペアリクエスト", ja: "修理依頼", ex: "I checked the repair request before leaving for work.", exJa: "出勤前に修理依頼を確認した。", cat: "生活" },
  { en: "furniture", pos: "名詞", kana: "ファニチャー", ja: "家具", ex: "I checked the furniture before leaving for work.", exJa: "出勤前に家具を確認した。", cat: "生活" },
  { en: "appliance", pos: "名詞", kana: "アプライアンス", ja: "家電", ex: "I checked the appliance before leaving for work.", exJa: "出勤前に家電を確認した。", cat: "生活" },
  { en: "vacuum cleaner", pos: "名詞", kana: "バキュームクリーナー", ja: "掃除機", ex: "I checked the vacuum cleaner before leaving for work.", exJa: "出勤前に掃除機を確認した。", cat: "生活" },
  { en: "air conditioner", pos: "名詞", kana: "エアコンディショナー", ja: "エアコン", ex: "I checked the air conditioner before leaving for work.", exJa: "出勤前にエアコンを確認した。", cat: "生活" },
  { en: "heater", pos: "名詞", kana: "ヒーター", ja: "暖房", ex: "I checked the heater before leaving for work.", exJa: "出勤前に暖房を確認した。", cat: "生活" },
  { en: "curtain", pos: "名詞", kana: "カーテン", ja: "カーテン", ex: "I checked the curtain before leaving for work.", exJa: "出勤前にカーテンを確認した。", cat: "生活" },
  { en: "closet", pos: "名詞", kana: "クローゼット", ja: "収納", ex: "I checked the closet before leaving for work.", exJa: "出勤前に収納を確認した。", cat: "生活" },
  { en: "neighborhood", pos: "名詞", kana: "ネイバーフッド", ja: "近所", ex: "I checked the neighborhood before leaving for work.", exJa: "出勤前に近所を確認した。", cat: "生活" },
  { en: "community center", pos: "名詞", kana: "コミュニティセンター", ja: "地域センター", ex: "I checked the community center before leaving for work.", exJa: "出勤前に地域センターを確認した。", cat: "生活" },
  { en: "membership", pos: "名詞", kana: "メンバーシップ", ja: "会員資格", ex: "I checked the membership before leaving for work.", exJa: "出勤前に会員資格を確認した。", cat: "生活" },
  { en: "subscription plan", pos: "名詞", kana: "サブスクリプションプラン", ja: "定期契約プラン", ex: "I checked the subscription plan before leaving for work.", exJa: "出勤前に定期契約プランを確認した。", cat: "生活" },
  { en: "renewal", pos: "名詞", kana: "リニューアル", ja: "更新", ex: "I checked the renewal before leaving for work.", exJa: "出勤前に更新を確認した。", cat: "生活" },
  { en: "cancellation fee", pos: "名詞", kana: "キャンセレーションフィー", ja: "解約手数料", ex: "I checked the cancellation fee before leaving for work.", exJa: "出勤前に解約手数料を確認した。", cat: "生活" },
  { en: "bank transfer", pos: "名詞", kana: "バンクトランスファー", ja: "銀行振込", ex: "I checked the bank transfer before leaving for work.", exJa: "出勤前に銀行振込を確認した。", cat: "生活" },
  { en: "account balance", pos: "名詞", kana: "アカウントバランス", ja: "口座残高", ex: "I checked the account balance before leaving for work.", exJa: "出勤前に口座残高を確認した。", cat: "生活" },
  { en: "withdrawal slip", pos: "名詞", kana: "ウィズドローアルスリップ", ja: "出金票", ex: "I checked the withdrawal slip before leaving for work.", exJa: "出勤前に出金票を確認した。", cat: "生活" },
  { en: "deposit slip", pos: "名詞", kana: "デポジットスリップ", ja: "入金票", ex: "I checked the deposit slip before leaving for work.", exJa: "出勤前に入金票を確認した。", cat: "生活" },
  { en: "passbook", pos: "名詞", kana: "パスブック", ja: "通帳", ex: "I checked the passbook before leaving for work.", exJa: "出勤前に通帳を確認した。", cat: "生活" },
  { en: "credit limit", pos: "名詞", kana: "クレジットリミット", ja: "利用限度額", ex: "I checked the credit limit before leaving for work.", exJa: "出勤前に利用限度額を確認した。", cat: "生活" },
  { en: "installment", pos: "名詞", kana: "インストールメント", ja: "分割払い", ex: "I checked the installment before leaving for work.", exJa: "出勤前に分割払いを確認した。", cat: "生活" },
  { en: "contactless payment", pos: "名詞", kana: "コンタクトレスペイメント", ja: "タッチ決済", ex: "I checked the contactless payment before leaving for work.", exJa: "出勤前にタッチ決済を確認した。", cat: "生活" },
  { en: "notification", pos: "名詞", kana: "ノーティフィケーション", ja: "通知メッセージ", ex: "I checked the notification before leaving for work.", exJa: "出勤前に通知メッセージを確認した。", cat: "生活" },
  { en: "settings", pos: "名詞", kana: "セッティングス", ja: "設定", ex: "I checked the settings before leaving for work.", exJa: "出勤前に設定を確認した。", cat: "生活" },
  { en: "language option", pos: "名詞", kana: "ランゲージオプション", ja: "言語設定", ex: "I checked the language option before leaving for work.", exJa: "出勤前に言語設定を確認した。", cat: "生活" },
  { en: "update notice", pos: "名詞", kana: "アップデートノーティス", ja: "更新案内", ex: "I checked the update notice before leaving for work.", exJa: "出勤前に更新案内を確認した。", cat: "生活" },
  { en: "user guide", pos: "名詞", kana: "ユーザーガイド", ja: "利用案内", ex: "I checked the user guide before leaving for work.", exJa: "出勤前に利用案内を確認した。", cat: "生活" },
  { en: "help desk", pos: "名詞", kana: "ヘルプデスク", ja: "問い合わせ窓口", ex: "I checked the help desk before leaving for work.", exJa: "出勤前に問い合わせ窓口を確認した。", cat: "生活" },
  { en: "feedback form", pos: "名詞", kana: "フィードバックフォーム", ja: "意見フォーム", ex: "I checked the feedback form before leaving for work.", exJa: "出勤前に意見フォームを確認した。", cat: "生活" },
  { en: "satisfaction survey", pos: "名詞", kana: "サティスファクションサーベイ", ja: "満足度調査", ex: "I checked the satisfaction survey before leaving for work.", exJa: "出勤前に満足度調査を確認した。", cat: "生活" },
  { en: "onboarding", pos: "名詞", kana: "オンボーディング", ja: "導入手続き", ex: "I checked the onboarding before leaving for work.", exJa: "出勤前に導入手続きを確認した。", cat: "生活" },
  { en: "offboarding", pos: "名詞", kana: "オフボーディング", ja: "退職手続き", ex: "I checked the offboarding before leaving for work.", exJa: "出勤前に退職手続きを確認した。", cat: "生活" },
];
