// ============================================================
// 英単語データ（英語ニュース頻出・中級／AI・戦争の話題を中心に）
// ------------------------------------------------------------
// 形式:
//   en   : 英単語
//   pos  : 品詞（名詞・動詞 など）
//   kana : カタカナ発音
//   ja   : 単語の意味
//   ex   : 例文（英語）
//   exJa : 例文の和訳
//   cat  : 属性（省略時は自動判定）
//   etym : 語源（省略時は語根から自動判定）
//
// ★ここに追記すれば単語を増やせます（最終的に3000語などへ拡張可）。
// ============================================================
const DEFAULT_WORDS = [
  // ---------- AI・テクノロジー ----------
  { en: "artificial", pos: "形容詞", kana: "アーティフィシャル", ja: "人工の", ex: "Artificial intelligence is changing many industries.", exJa: "人工知能は多くの産業を変えつつある。" },
  { en: "intelligence", pos: "名詞", kana: "インテリジェンス", ja: "知能・情報", ex: "The system uses artificial intelligence to make decisions.", exJa: "そのシステムは判断のために人工知能を使う。" },
  { en: "algorithm", pos: "名詞", kana: "アルゴリズム", ja: "アルゴリズム・計算手順", ex: "The algorithm recommends videos based on your history.", exJa: "そのアルゴリズムは履歴をもとに動画を勧める。" },
  { en: "data", pos: "名詞", kana: "デイタ／データ", ja: "データ・資料", ex: "The model was trained on a huge amount of data.", exJa: "そのモデルは膨大なデータで訓練された。" },
  { en: "model", pos: "名詞・動詞", kana: "モデル", ja: "モデル・模型／模型を作る", ex: "The new language model can write essays.", exJa: "その新しい言語モデルは小論文を書ける。" },
  { en: "train", pos: "動詞・名詞", kana: "トレイン", ja: "訓練する・学習させる／列車", ex: "Engineers train the AI on millions of images.", exJa: "技術者は何百万もの画像でそのAIを学習させる。" },
  { en: "generate", pos: "動詞", kana: "ジェネレイト", ja: "生成する・生み出す", ex: "The tool can generate text and images.", exJa: "そのツールはテキストや画像を生成できる。" },
  { en: "automate", pos: "動詞", kana: "オートメイト", ja: "自動化する", ex: "Companies use AI to automate boring tasks.", exJa: "企業は退屈な作業を自動化するためにAIを使う。" },
  { en: "automation", pos: "名詞", kana: "オートメイション", ja: "自動化", ex: "Automation may replace some factory jobs.", exJa: "自動化は一部の工場の仕事に取って代わるかもしれない。" },
  { en: "robot", pos: "名詞", kana: "ロウボット", ja: "ロボット", ex: "The factory uses robots to build cars.", exJa: "その工場は車を作るのにロボットを使う。" },
  { en: "device", pos: "名詞", kana: "ディヴァイス", ja: "機器・装置", ex: "Smartphones are powerful computing devices.", exJa: "スマホは強力なコンピューティング機器だ。" },
  { en: "software", pos: "名詞", kana: "ソフトウェア", ja: "ソフトウェア", ex: "They released new software for the system.", exJa: "彼らはそのシステム用の新しいソフトを公開した。" },
  { en: "network", pos: "名詞・動詞", kana: "ネットワーク", ja: "ネットワーク・網／交流する", ex: "A neural network mimics the human brain.", exJa: "ニューラルネットワークは人間の脳をまねる。" },
  { en: "process", pos: "名詞・動詞", kana: "プロセス", ja: "過程／処理する", ex: "The chip can process data very quickly.", exJa: "そのチップはデータを非常に速く処理できる。" },
  { en: "predict", pos: "動詞", kana: "プリディクト", ja: "予測する", ex: "AI can predict the weather more accurately.", exJa: "AIはより正確に天気を予測できる。" },
  { en: "analyze", pos: "動詞", kana: "アナライズ", ja: "分析する", ex: "Scientists analyze the data with computers.", exJa: "科学者はコンピューターでデータを分析する。" },
  { en: "innovation", pos: "名詞", kana: "イノヴェイション", ja: "革新", ex: "AI is driving innovation in medicine.", exJa: "AIは医療における革新を推し進めている。" },
  { en: "technology", pos: "名詞", kana: "テクノロジー", ja: "技術", ex: "New technology spreads around the world fast.", exJa: "新しい技術は世界中に速く広まる。" },
  { en: "digital", pos: "形容詞", kana: "ディジタル", ja: "デジタルの", ex: "We live in a digital age.", exJa: "私たちはデジタル時代に生きている。" },
  { en: "virtual", pos: "形容詞", kana: "ヴァーチャル", ja: "仮想の・事実上の", ex: "They held a virtual meeting online.", exJa: "彼らはオンラインで仮想会議を開いた。" },
  { en: "platform", pos: "名詞", kana: "プラットフォーム", ja: "プラットフォーム・基盤", ex: "Social media platforms reach billions of users.", exJa: "SNSプラットフォームは何十億ものユーザーに届く。" },
  { en: "regulate", pos: "動詞", kana: "レギュレイト", ja: "規制する", ex: "Governments want to regulate AI companies.", exJa: "各国政府はAI企業を規制したがっている。" },
  { en: "regulation", pos: "名詞", kana: "レギュレイション", ja: "規制・規則", ex: "New regulations will affect tech firms.", exJa: "新しい規制はテック企業に影響する。" },
  { en: "privacy", pos: "名詞", kana: "プライヴァシー", ja: "プライバシー", ex: "People worry about their privacy online.", exJa: "人々はオンラインでのプライバシーを心配している。" },
  { en: "security", pos: "名詞", kana: "セキュリティ", ja: "安全・警備・保障", ex: "Cyber security is a growing concern.", exJa: "サイバーセキュリティは増大する懸念だ。" },
  { en: "threat", pos: "名詞", kana: "スレット", ja: "脅威・脅し", ex: "Hackers pose a serious threat to companies.", exJa: "ハッカーは企業に深刻な脅威をもたらす。" },
  { en: "impact", pos: "名詞・動詞", kana: "インパクト", ja: "影響／影響を与える", ex: "AI will have a huge impact on jobs.", exJa: "AIは雇用に大きな影響を与えるだろう。" },
  { en: "replace", pos: "動詞", kana: "リプレイス", ja: "取って代わる・交換する", ex: "Machines may replace many human workers.", exJa: "機械は多くの人間の労働者に取って代わるかもしれない。" },
  { en: "efficient", pos: "形容詞", kana: "イフィシェント", ja: "効率的な", ex: "The new method is faster and more efficient.", exJa: "その新しい方法はより速く効率的だ。" },
  { en: "develop", pos: "動詞", kana: "ディヴェロップ", ja: "開発する・発展させる", ex: "Researchers develop new AI tools every year.", exJa: "研究者は毎年新しいAIツールを開発する。" },
  { en: "research", pos: "名詞・動詞", kana: "リサーチ", ja: "研究／研究する", ex: "The lab does research on machine learning.", exJa: "その研究室は機械学習の研究をしている。" },

  // ---------- 戦争・紛争・軍事 ----------
  { en: "war", pos: "名詞", kana: "ウォー", ja: "戦争", ex: "The war has lasted for several years.", exJa: "その戦争は数年続いている。" },
  { en: "conflict", pos: "名詞・動詞", kana: "コンフリクト", ja: "紛争・対立／対立する", ex: "The conflict forced many people to flee.", exJa: "その紛争は多くの人々を避難させた。" },
  { en: "military", pos: "名詞・形容詞", kana: "ミリタリー", ja: "軍・軍の", ex: "The military launched a new operation.", exJa: "軍は新たな作戦を開始した。" },
  { en: "weapon", pos: "名詞", kana: "ウェポン", ja: "兵器・武器", ex: "Both sides used heavy weapons.", exJa: "双方が重火器を使用した。" },
  { en: "attack", pos: "名詞・動詞", kana: "アタック", ja: "攻撃／攻撃する", ex: "The city was hit by a missile attack.", exJa: "その都市はミサイル攻撃を受けた。" },
  { en: "defense", pos: "名詞", kana: "ディフェンス", ja: "防衛・守り", ex: "The country increased its defense budget.", exJa: "その国は防衛予算を増やした。" },
  { en: "invade", pos: "動詞", kana: "インヴェイド", ja: "侵略する", ex: "Troops invaded the neighboring country.", exJa: "軍隊が隣国に侵攻した。" },
  { en: "invasion", pos: "名詞", kana: "インヴェイジョン", ja: "侵略・侵攻", ex: "The invasion shocked the whole world.", exJa: "その侵攻は世界中に衝撃を与えた。" },
  { en: "troops", pos: "名詞", kana: "トゥループス", ja: "軍隊・部隊", ex: "Thousands of troops were sent to the border.", exJa: "数千の部隊が国境に送られた。" },
  { en: "soldier", pos: "名詞", kana: "ソウルジャー", ja: "兵士", ex: "Many soldiers were wounded in the battle.", exJa: "多くの兵士がその戦闘で負傷した。" },
  { en: "civilian", pos: "名詞・形容詞", kana: "シヴィリアン", ja: "民間人・一般市民／民間の", ex: "The attack killed many civilians.", exJa: "その攻撃で多くの民間人が亡くなった。" },
  { en: "ceasefire", pos: "名詞", kana: "シースファイア", ja: "停戦", ex: "Both sides agreed to a ceasefire.", exJa: "双方が停戦に合意した。" },
  { en: "negotiate", pos: "動詞", kana: "ネゴシエイト", ja: "交渉する", ex: "The leaders met to negotiate peace.", exJa: "首脳たちは和平を交渉するために会った。" },
  { en: "negotiation", pos: "名詞", kana: "ネゴシエイション", ja: "交渉", ex: "Peace negotiations are still ongoing.", exJa: "和平交渉はまだ続いている。" },
  { en: "treaty", pos: "名詞", kana: "トリーティ", ja: "条約", ex: "The two nations signed a peace treaty.", exJa: "両国は和平条約に署名した。" },
  { en: "alliance", pos: "名詞", kana: "アライアンス", ja: "同盟", ex: "The military alliance held joint drills.", exJa: "その軍事同盟は合同演習を行った。" },
  { en: "tension", pos: "名詞", kana: "テンション", ja: "緊張", ex: "Tensions rose between the two countries.", exJa: "両国間の緊張が高まった。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "The region faces a humanitarian crisis.", exJa: "その地域は人道危機に直面している。" },
  { en: "refugee", pos: "名詞", kana: "レフュジー", ja: "難民", ex: "Millions of refugees fled the war.", exJa: "何百万もの難民が戦争から逃れた。" },
  { en: "casualty", pos: "名詞", kana: "キャジュアルティ", ja: "死傷者", ex: "The number of casualties keeps rising.", exJa: "死傷者の数は増え続けている。" },
  { en: "sanction", pos: "名詞・動詞", kana: "サンクション", ja: "制裁／制裁を科す", ex: "The government imposed new sanctions on the regime.", exJa: "政府はその政権に新たな制裁を科した。" },
  { en: "regime", pos: "名詞", kana: "レジーム", ja: "政権・体制", ex: "The regime was accused of human rights abuses.", exJa: "その政権は人権侵害で非難された。" },
  { en: "border", pos: "名詞", kana: "ボーダー", ja: "国境・境界", ex: "Soldiers guarded the border day and night.", exJa: "兵士たちは昼夜国境を守った。" },
  { en: "missile", pos: "名詞", kana: "ミサイル", ja: "ミサイル", ex: "The country tested a long-range missile.", exJa: "その国は長距離ミサイルを試射した。" },
  { en: "nuclear", pos: "形容詞", kana: "ニュークリア", ja: "核の・原子力の", ex: "Talks focused on nuclear weapons.", exJa: "協議は核兵器に焦点を当てた。" },
  { en: "destroy", pos: "動詞", kana: "ディストロイ", ja: "破壊する", ex: "The bombs destroyed several buildings.", exJa: "爆弾がいくつかの建物を破壊した。" },
  { en: "evacuate", pos: "動詞", kana: "イヴァキュエイト", ja: "避難させる・避難する", ex: "Families were told to evacuate the area.", exJa: "家族たちはその地域から避難するよう告げられた。" },
  { en: "withdraw", pos: "動詞", kana: "ウィズドロー", ja: "撤退する・引き出す", ex: "The army agreed to withdraw its troops.", exJa: "軍は部隊を撤退させることに同意した。" },
  { en: "hostage", pos: "名詞", kana: "ホステッジ", ja: "人質", ex: "The group released several hostages.", exJa: "その集団は数人の人質を解放した。" },
  { en: "violence", pos: "名詞", kana: "ヴァイオレンス", ja: "暴力", ex: "The protest turned into violence.", exJa: "その抗議は暴力に発展した。" },

  // ---------- 政治・経済・社会ニュース ----------
  { en: "government", pos: "名詞", kana: "ガヴァメント", ja: "政府", ex: "The government announced a new policy.", exJa: "政府は新しい政策を発表した。" },
  { en: "policy", pos: "名詞", kana: "ポリシー", ja: "政策・方針", ex: "The new policy aims to reduce poverty.", exJa: "その新政策は貧困削減を目指している。" },
  { en: "president", pos: "名詞", kana: "プレジデント", ja: "大統領・社長", ex: "The president gave a speech on TV.", exJa: "大統領はテレビで演説した。" },
  { en: "election", pos: "名詞", kana: "イレクション", ja: "選挙", ex: "The election will be held next month.", exJa: "選挙は来月行われる。" },
  { en: "economy", pos: "名詞", kana: "イコノミー", ja: "経済", ex: "The economy grew faster than expected.", exJa: "経済は予想より速く成長した。" },
  { en: "economic", pos: "形容詞", kana: "イコノミック", ja: "経済の", ex: "Economic growth slowed down this year.", exJa: "今年は経済成長が鈍化した。" },
  { en: "inflation", pos: "名詞", kana: "インフレイション", ja: "インフレ・物価上昇", ex: "High inflation hurts ordinary families.", exJa: "高いインフレは一般家庭を苦しめる。" },
  { en: "recession", pos: "名詞", kana: "リセッション", ja: "景気後退", ex: "Experts fear a global recession.", exJa: "専門家は世界的な景気後退を懸念している。" },
  { en: "market", pos: "名詞", kana: "マーケット", ja: "市場", ex: "The stock market fell sharply.", exJa: "株式市場は急落した。" },
  { en: "trade", pos: "名詞・動詞", kana: "トレイド", ja: "貿易・取引／取引する", ex: "The two countries signed a trade deal.", exJa: "両国は貿易協定に署名した。" },
  { en: "industry", pos: "名詞", kana: "インダストリー", ja: "産業・業界", ex: "The tech industry is growing rapidly.", exJa: "テック産業は急速に成長している。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "The energy crisis raised fuel prices.", exJa: "エネルギー危機は燃料価格を引き上げた。" },
  { en: "protest", pos: "名詞・動詞", kana: "プロテスト", ja: "抗議／抗議する", ex: "Thousands joined the protest downtown.", exJa: "何千人もが繁華街の抗議に加わった。" },
  { en: "election", pos: "名詞", kana: "イレクション", ja: "選挙", ex: "Voters lined up early for the election.", exJa: "有権者は選挙のため早くから並んだ。" },
  { en: "official", pos: "名詞・形容詞", kana: "オフィシャル", ja: "当局者／公式の", ex: "A government official confirmed the news.", exJa: "政府当局者がそのニュースを認めた。" },
  { en: "announce", pos: "動詞", kana: "アナウンス", ja: "発表する", ex: "The company announced record profits.", exJa: "その会社は過去最高の利益を発表した。" },
  { en: "claim", pos: "動詞・名詞", kana: "クレイム", ja: "主張する／主張", ex: "Both sides claim they won the battle.", exJa: "双方がその戦いに勝ったと主張している。" },
  { en: "accuse", pos: "動詞", kana: "アキューズ", ja: "非難する・告発する", ex: "Critics accuse the company of fraud.", exJa: "批判する人々はその会社を詐欺だと非難する。" },
  { en: "investigate", pos: "動詞", kana: "インヴェスティゲイト", ja: "調査する", ex: "Police are investigating the incident.", exJa: "警察はその事件を調査している。" },
  { en: "incident", pos: "名詞", kana: "インシデント", ja: "出来事・事件", ex: "The incident raised safety concerns.", exJa: "その事件は安全上の懸念を高めた。" },
  { en: "authority", pos: "名詞", kana: "オーソリティ", ja: "当局・権限", ex: "Local authorities warned residents to stay home.", exJa: "地元当局は住民に在宅を呼びかけた。" },
  { en: "concern", pos: "名詞・動詞", kana: "コンサーン", ja: "懸念／心配させる", ex: "There is growing concern about the economy.", exJa: "経済に対する懸念が高まっている。" },
  { en: "demand", pos: "名詞・動詞", kana: "ディマンド", ja: "要求・需要／要求する", ex: "Protesters demand higher wages.", exJa: "抗議者たちはより高い賃金を要求している。" },
  { en: "supply", pos: "名詞・動詞", kana: "サプライ", ja: "供給／供給する", ex: "The war disrupted the food supply.", exJa: "戦争は食料供給を混乱させた。" },
  { en: "agreement", pos: "名詞", kana: "アグリーメント", ja: "合意・協定", ex: "They finally reached an agreement.", exJa: "彼らはついに合意に達した。" },
  { en: "support", pos: "名詞・動詞", kana: "サポート", ja: "支援／支援する", ex: "Many countries offered support to the victims.", exJa: "多くの国が被災者に支援を申し出た。" },
  { en: "victim", pos: "名詞", kana: "ヴィクティム", ja: "被害者・犠牲者", ex: "Aid was sent to the victims of the disaster.", exJa: "支援が災害の被災者に送られた。" },
  { en: "humanitarian", pos: "形容詞", kana: "ヒューマニテリアン", ja: "人道的な", ex: "The UN called for humanitarian aid.", exJa: "国連は人道支援を呼びかけた。" },
  { en: "global", pos: "形容詞", kana: "グローバル", ja: "世界的な", ex: "Climate change is a global problem.", exJa: "気候変動は世界的な問題だ。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "World leaders met to discuss the crisis.", exJa: "世界の指導者たちが危機を議論するため集まった。" },

  // ---------- 報道・議論でよく使う動詞・形容詞 ----------
  { en: "increase", pos: "動詞・名詞", kana: "インクリース", ja: "増える・増やす／増加", ex: "Fuel prices increased last month.", exJa: "燃料価格は先月上昇した。" },
  { en: "decrease", pos: "動詞・名詞", kana: "ディクリース", ja: "減る・減らす／減少", ex: "Unemployment decreased this year.", exJa: "失業率は今年低下した。" },
  { en: "reduce", pos: "動詞", kana: "リデュース", ja: "減らす", ex: "The plan aims to reduce carbon emissions.", exJa: "その計画は炭素排出を減らすことを目指す。" },
  { en: "release", pos: "動詞・名詞", kana: "リリース", ja: "公開する・解放する／発表", ex: "The company released a new product.", exJa: "その会社は新製品を発表した。" },
  { en: "report", pos: "名詞・動詞", kana: "リポート", ja: "報告／報道する", ex: "The report warned about rising prices.", exJa: "その報告は物価上昇について警告した。" },
  { en: "warn", pos: "動詞", kana: "ウォーン", ja: "警告する", ex: "Experts warn of more flooding.", exJa: "専門家はさらなる洪水を警告している。" },
  { en: "estimate", pos: "動詞・名詞", kana: "エスティメイト", ja: "見積もる／見積もり", ex: "Officials estimate the damage at billions.", exJa: "当局は被害を数十億と見積もっている。" },
  { en: "reveal", pos: "動詞", kana: "リヴィール", ja: "明らかにする", ex: "The study revealed surprising results.", exJa: "その研究は驚くべき結果を明らかにした。" },
  { en: "expand", pos: "動詞", kana: "イクスパンド", ja: "拡大する", ex: "The company plans to expand into Asia.", exJa: "その会社はアジアへの進出を計画している。" },
  { en: "significant", pos: "形容詞", kana: "シグニフィカント", ja: "重要な・著しい", ex: "There was a significant rise in sales.", exJa: "売上に著しい増加があった。" },
  { en: "potential", pos: "名詞・形容詞", kana: "ポテンシャル", ja: "可能性／潜在的な", ex: "AI has huge potential in healthcare.", exJa: "AIは医療に大きな可能性を持つ。" },
  { en: "current", pos: "形容詞", kana: "カレント", ja: "現在の", ex: "The current situation is very serious.", exJa: "現在の状況は非常に深刻だ。" },
  { en: "recent", pos: "形容詞", kana: "リーセント", ja: "最近の", ex: "A recent survey shows rising prices.", exJa: "最近の調査は物価上昇を示している。" },
  { en: "major", pos: "形容詞", kana: "メイジャー", ja: "主要な・大きな", ex: "The storm caused major damage.", exJa: "その嵐は大きな被害を引き起こした。" },
  { en: "severe", pos: "形容詞", kana: "シヴィア", ja: "深刻な・厳しい", ex: "The region suffered a severe drought.", exJa: "その地域は深刻な干ばつに見舞われた。" },
  { en: "spread", pos: "動詞・名詞", kana: "スプレッド", ja: "広がる・広げる／広がり", ex: "Fake news spreads quickly online.", exJa: "フェイクニュースはネット上で素早く広がる。" },
  { en: "affect", pos: "動詞", kana: "アフェクト", ja: "影響を与える", ex: "The drought affected millions of people.", exJa: "その干ばつは何百万もの人々に影響を与えた。" },
  { en: "cause", pos: "動詞・名詞", kana: "コーズ", ja: "引き起こす／原因", ex: "The fire caused serious damage.", exJa: "その火事は深刻な被害を引き起こした。" },
  { en: "prevent", pos: "動詞", kana: "プリヴェント", ja: "防ぐ", ex: "New rules aim to prevent accidents.", exJa: "新しい規則は事故を防ぐことを目指す。" },
  { en: "respond", pos: "動詞", kana: "リスポンド", ja: "対応する・反応する", ex: "The government responded to the crisis quickly.", exJa: "政府はその危機に素早く対応した。" },
  { en: "establish", pos: "動詞", kana: "イスタブリッシュ", ja: "設立する・確立する", ex: "They established a new committee.", exJa: "彼らは新しい委員会を設立した。" },
  { en: "achieve", pos: "動詞", kana: "アチーヴ", ja: "達成する", ex: "The team achieved its main goal.", exJa: "そのチームは主な目標を達成した。" },
  { en: "consider", pos: "動詞", kana: "コンシダー", ja: "検討する・考慮する", ex: "Leaders are considering new measures.", exJa: "指導者たちは新たな対策を検討している。" },
  { en: "measure", pos: "名詞・動詞", kana: "メジャー", ja: "対策・手段／測る", ex: "The government took emergency measures.", exJa: "政府は緊急措置をとった。" },
  { en: "policy", pos: "名詞", kana: "ポリシー", ja: "政策・方針", ex: "The bank changed its interest rate policy.", exJa: "その銀行は金利政策を変更した。" },
  { en: "issue", pos: "名詞・動詞", kana: "イシュー", ja: "問題・争点／発行する", ex: "Climate change is a serious issue.", exJa: "気候変動は深刻な問題だ。" },
  { en: "solution", pos: "名詞", kana: "ソルーション", ja: "解決策", ex: "There is no easy solution to the problem.", exJa: "その問題に簡単な解決策はない。" },
  { en: "benefit", pos: "名詞・動詞", kana: "ベネフィット", ja: "利益・恩恵／利益を得る", ex: "New technology benefits many people.", exJa: "新しい技術は多くの人に恩恵を与える。" },
  { en: "risk", pos: "名詞・動詞", kana: "リスク", ja: "危険・リスク／危険にさらす", ex: "There is a high risk of conflict.", exJa: "紛争の高い危険がある。" },
  { en: "ban", pos: "動詞・名詞", kana: "バン", ja: "禁止する／禁止", ex: "The country banned the use of the app.", exJa: "その国はそのアプリの使用を禁止した。" },

  // ============================================================
  // 上級寄り（ニュース・AI・戦争で頻出する歯ごたえのある語）
  // ============================================================

  // ---------- AI・テクノロジー（上級） ----------
  { en: "surveillance", pos: "名詞", kana: "サヴェイランス", ja: "監視", ex: "Critics warn that AI enables mass surveillance.", exJa: "批判する人々は、AIが大規模な監視を可能にすると警告している。" },
  { en: "autonomous", pos: "形容詞", kana: "オートノマス", ja: "自律した・自動運転の", ex: "Autonomous vehicles are being tested on public roads.", exJa: "自動運転車が公道で試験されている。" },
  { en: "algorithmic", pos: "形容詞", kana: "アルゴリズミック", ja: "アルゴリズムの", ex: "Researchers found algorithmic bias in the hiring tool.", exJa: "研究者はその採用ツールにアルゴリズムの偏りを見つけた。" },
  { en: "bias", pos: "名詞・動詞", kana: "バイアス", ja: "偏り・先入観／偏らせる", ex: "The model showed a clear bias against some groups.", exJa: "そのモデルは一部の集団に対する明らかな偏りを示した。" },
  { en: "deploy", pos: "動詞", kana: "ディプロイ", ja: "展開する・配備する・運用開始する", ex: "The company deployed the new AI system worldwide.", exJa: "その会社は新しいAIシステムを世界中で運用開始した。" },
  { en: "scalable", pos: "形容詞", kana: "スケーラブル", ja: "拡張可能な", ex: "The platform is scalable to millions of users.", exJa: "そのプラットフォームは数百万人規模に拡張できる。" },
  { en: "infrastructure", pos: "名詞", kana: "インフラストラクチャー", ja: "基盤・インフラ", ex: "Training large models requires huge computing infrastructure.", exJa: "大規模モデルの学習には巨大な計算インフラが必要だ。" },
  { en: "breakthrough", pos: "名詞", kana: "ブレイクスルー", ja: "大きな進展・突破口", ex: "The discovery was hailed as a major breakthrough.", exJa: "その発見は大きな突破口として称賛された。" },
  { en: "disrupt", pos: "動詞", kana: "ディスラプト", ja: "混乱させる・大きく変える", ex: "Generative AI could disrupt the entire industry.", exJa: "生成AIは業界全体を一変させる可能性がある。" },
  { en: "ethical", pos: "形容詞", kana: "エシカル", ja: "倫理的な", ex: "There are ethical concerns about facial recognition.", exJa: "顔認識には倫理的な懸念がある。" },
  { en: "transparency", pos: "名詞", kana: "トランスパレンシー", ja: "透明性", ex: "Users demand more transparency from tech firms.", exJa: "ユーザーはテック企業にさらなる透明性を求めている。" },
  { en: "accountability", pos: "名詞", kana: "アカウンタビリティ", ja: "説明責任", ex: "Lawmakers called for greater accountability in AI use.", exJa: "議員たちはAI利用におけるより大きな説明責任を求めた。" },
  { en: "exploit", pos: "動詞・名詞", kana: "エクスプロイト", ja: "悪用する・活用する／脆弱性", ex: "Hackers exploited a flaw in the software.", exJa: "ハッカーはそのソフトの欠陥を悪用した。" },
  { en: "vulnerability", pos: "名詞", kana: "ヴァルネラビリティ", ja: "脆弱性・弱点", ex: "The report revealed a serious security vulnerability.", exJa: "その報告は深刻なセキュリティ上の脆弱性を明らかにした。" },
  { en: "misinformation", pos: "名詞", kana: "ミスインフォメイション", ja: "誤情報", ex: "AI can spread misinformation at scale.", exJa: "AIは誤情報を大規模に拡散しうる。" },
  { en: "unprecedented", pos: "形容詞", kana: "アンプレシデンテッド", ja: "前例のない", ex: "The technology is advancing at an unprecedented pace.", exJa: "その技術は前例のない速さで進歩している。" },

  // ---------- 戦争・安全保障（上級） ----------
  { en: "escalate", pos: "動詞", kana: "エスカレイト", ja: "激化する・拡大させる", ex: "Fears grow that the conflict could escalate further.", exJa: "紛争がさらに激化しうるという懸念が高まっている。" },
  { en: "escalation", pos: "名詞", kana: "エスカレイション", ja: "激化・段階的拡大", ex: "Diplomats are working to prevent further escalation.", exJa: "外交官たちはさらなる激化を防ごうとしている。" },
  { en: "deterrence", pos: "名詞", kana: "ディターレンス", ja: "抑止（力）", ex: "Nuclear deterrence shaped the Cold War.", exJa: "核抑止は冷戦を形づくった。" },
  { en: "sovereignty", pos: "名詞", kana: "ソヴリンティ", ja: "主権", ex: "The invasion violated the country's sovereignty.", exJa: "その侵攻はその国の主権を侵害した。" },
  { en: "annex", pos: "動詞", kana: "アネックス", ja: "併合する", ex: "The state tried to annex the disputed region.", exJa: "その国家は係争地域を併合しようとした。" },
  { en: "insurgency", pos: "名詞", kana: "インサージェンシー", ja: "反乱・武装蜂起", ex: "The army struggled to contain the insurgency.", exJa: "軍はその反乱を抑え込むのに苦労した。" },
  { en: "militant", pos: "名詞・形容詞", kana: "ミリタント", ja: "武装勢力・過激派／好戦的な", ex: "Militants attacked a military base overnight.", exJa: "武装勢力が夜間に軍事基地を攻撃した。" },
  { en: "atrocity", pos: "名詞", kana: "アトロシティ", ja: "残虐行為", ex: "Investigators documented atrocities against civilians.", exJa: "調査官は民間人に対する残虐行為を記録した。" },
  { en: "retaliate", pos: "動詞", kana: "リタリエイト", ja: "報復する", ex: "The government vowed to retaliate against the strike.", exJa: "政府はその攻撃に報復すると誓った。" },
  { en: "retaliation", pos: "名詞", kana: "リタリエイション", ja: "報復", ex: "The attack was launched in retaliation.", exJa: "その攻撃は報復として行われた。" },
  { en: "offensive", pos: "名詞・形容詞", kana: "オフェンシブ", ja: "攻勢／攻撃的な", ex: "The army launched a major ground offensive.", exJa: "軍は大規模な地上攻勢を開始した。" },
  { en: "siege", pos: "名詞", kana: "シージ", ja: "包囲", ex: "The city has been under siege for weeks.", exJa: "その都市は数週間にわたり包囲されている。" },
  { en: "deploy", pos: "動詞", kana: "ディプロイ", ja: "配備する・展開する", ex: "More troops were deployed to the front line.", exJa: "より多くの部隊が前線に配備された。" },
  { en: "proliferation", pos: "名詞", kana: "プロリファレイション", ja: "拡散・急増", ex: "The treaty aims to stop nuclear proliferation.", exJa: "その条約は核拡散を止めることを目指している。" },
  { en: "displaced", pos: "形容詞", kana: "ディスプレイスト", ja: "(住む場所を)追われた", ex: "Millions of people have been displaced by the war.", exJa: "何百万もの人々が戦争で住む場所を追われた。" },
  { en: "diplomacy", pos: "名詞", kana: "ディプロマシー", ja: "外交", ex: "They hope diplomacy can end the crisis.", exJa: "彼らは外交がその危機を終わらせられると期待している。" },
  { en: "intervention", pos: "名詞", kana: "インターヴェンション", ja: "介入", ex: "Critics oppose military intervention abroad.", exJa: "批判する人々は海外への軍事介入に反対している。" },
  { en: "condemn", pos: "動詞", kana: "コンデム", ja: "非難する", ex: "World leaders condemned the attack.", exJa: "世界の指導者たちはその攻撃を非難した。" },

  // ---------- 政治・経済・社会（上級） ----------
  { en: "allegation", pos: "名詞", kana: "アリゲイション", ja: "(証拠のない)主張・申し立て", ex: "The company denied all the allegations.", exJa: "その会社はすべての申し立てを否定した。" },
  { en: "sanction", pos: "名詞・動詞", kana: "サンクション", ja: "制裁／認可する", ex: "Western nations tightened sanctions on the regime.", exJa: "西側諸国はその政権への制裁を強化した。" },
  { en: "coalition", pos: "名詞", kana: "コアリション", ja: "連立・連合", ex: "A new coalition government was formed.", exJa: "新しい連立政権が発足した。" },
  { en: "legislation", pos: "名詞", kana: "レジスレイション", ja: "法律・立法", ex: "Parliament passed new legislation on data privacy.", exJa: "議会はデータ保護に関する新法を可決した。" },
  { en: "mandate", pos: "名詞・動詞", kana: "マンデイト", ja: "権限・指令／義務づける", ex: "Voters gave the party a strong mandate.", exJa: "有権者はその政党に強い信任を与えた。" },
  { en: "scrutiny", pos: "名詞", kana: "スクルーティニー", ja: "綿密な調査・精査", ex: "The deal is under intense scrutiny.", exJa: "その取引は厳しい精査を受けている。" },
  { en: "controversial", pos: "形容詞", kana: "コントロヴァーシャル", ja: "物議をかもす", ex: "The decision proved highly controversial.", exJa: "その決定は非常に物議をかもした。" },
  { en: "implement", pos: "動詞", kana: "インプリメント", ja: "実施する", ex: "The government will implement the reforms next year.", exJa: "政府は来年その改革を実施する。" },
  { en: "undermine", pos: "動詞", kana: "アンダーマイン", ja: "弱体化させる・損なう", ex: "Corruption can undermine public trust.", exJa: "汚職は国民の信頼を損ないうる。" },
  { en: "advocate", pos: "動詞・名詞", kana: "アドヴォケイト", ja: "提唱する／支持者", ex: "She advocates for stronger climate policies.", exJa: "彼女はより強力な気候政策を提唱している。" },
  { en: "subsidy", pos: "名詞", kana: "サブシディ", ja: "補助金", ex: "The government cut subsidies for fuel.", exJa: "政府は燃料への補助金を削減した。" },
  { en: "volatile", pos: "形容詞", kana: "ヴォラタイル", ja: "不安定な・変動の激しい", ex: "Oil prices remain highly volatile.", exJa: "原油価格は依然として非常に不安定だ。" },
  { en: "plummet", pos: "動詞", kana: "プラメット", ja: "急落する", ex: "Stock prices plummeted after the news.", exJa: "そのニュースの後、株価は急落した。" },
  { en: "surge", pos: "名詞・動詞", kana: "サージ", ja: "急増／急増する", ex: "There was a surge in energy demand.", exJa: "エネルギー需要に急増があった。" },
  { en: "disparity", pos: "名詞", kana: "ディスパリティ", ja: "格差・不均衡", ex: "The report highlights wide income disparity.", exJa: "その報告は大きな所得格差を浮き彫りにしている。" },
  { en: "resilience", pos: "名詞", kana: "リジリエンス", ja: "回復力・強靱さ", ex: "The economy showed surprising resilience.", exJa: "経済は驚くべき回復力を見せた。" },
  { en: "unanimous", pos: "形容詞", kana: "ユナニマス", ja: "全員一致の", ex: "The council reached a unanimous decision.", exJa: "評議会は全員一致の決定に達した。" },
  { en: "imminent", pos: "形容詞", kana: "イミネント", ja: "差し迫った", ex: "Officials warned of an imminent threat.", exJa: "当局は差し迫った脅威を警告した。" },
  { en: "deteriorate", pos: "動詞", kana: "ディティアリオレイト", ja: "悪化する", ex: "The situation continues to deteriorate.", exJa: "状況は悪化し続けている。" },
  { en: "mitigate", pos: "動詞", kana: "ミティゲイト", ja: "緩和する・軽減する", ex: "New rules aim to mitigate the damage.", exJa: "新しい規則は被害を軽減することを目指している。" },

  // ---------- 中級・追加（約200語）AI・テクノロジー ----------
  { en: "neural", pos: "形容詞", kana: "ニューラル", ja: "神経の・ニューラル", ex: "Neural networks learn patterns from data.", exJa: "ニューラルネットワークはデータからパターンを学習する。" },
  { en: "computing", pos: "名詞", kana: "コンピューティング", ja: "計算・コンピューティング", ex: "Cloud computing powers many online services.", exJa: "クラウドコンピューティングは多くのオンラインサービスを支える。" },
  { en: "semiconductor", pos: "名詞", kana: "セミコンダクター", ja: "半導体", ex: "The world faces a shortage of semiconductors.", exJa: "世界は半導体不足に直面している。" },
  { en: "chip", pos: "名詞", kana: "チップ", ja: "チップ・半導体チップ", ex: "The new chip processes data much faster.", exJa: "その新チップはデータをはるかに速く処理する。" },
  { en: "startup", pos: "名詞", kana: "スタートアップ", ja: "新興企業", ex: "The AI startup raised millions in funding.", exJa: "そのAIスタートアップは何百万ドルもの資金を調達した。" },
  { en: "interface", pos: "名詞", kana: "インターフェース", ja: "操作画面・界面", ex: "The app has a simple user interface.", exJa: "そのアプリはシンプルなユーザー界面を持つ。" },
  { en: "database", pos: "名詞", kana: "データベース", ja: "データベース", ex: "Customer data is stored in a secure database.", exJa: "顧客データは安全なデータベースに保存されている。" },
  { en: "cloud", pos: "名詞", kana: "クラウド", ja: "クラウド", ex: "Files are saved in the cloud automatically.", exJa: "ファイルは自動的にクラウドに保存される。" },
  { en: "parameter", pos: "名詞", kana: "パラメーター", ja: "パラメーター", ex: "Engineers adjusted the model parameters.", exJa: "技術者はモデルのパラメーターを調整した。" },
  { en: "optimize", pos: "動詞", kana: "オプティマイズ", ja: "最適化する", ex: "The system optimizes energy use in real time.", exJa: "そのシステムはリアルタイムでエネルギー使用を最適化する。" },
  { en: "accuracy", pos: "名詞", kana: "アキュラシー", ja: "正確さ", ex: "The tool improved the accuracy of diagnoses.", exJa: "そのツールは診断の正確さを向上させた。" },
  { en: "processor", pos: "名詞", kana: "プロセッサー", ja: "プロセッサー", ex: "A faster processor speeds up the computer.", exJa: "より速いプロセッサーはコンピューターを高速化する。" },
  { en: "sensor", pos: "名詞", kana: "センサー", ja: "センサー", ex: "Sensors detect motion in the room.", exJa: "センサーは部屋の動きを検知する。" },
  { en: "drone", pos: "名詞", kana: "ドローン", ja: "ドローン", ex: "Drones delivered supplies to remote areas.", exJa: "ドローンが僻地に物資を届けた。" },
  { en: "satellite", pos: "名詞", kana: "サテライト", ja: "衛星", ex: "Satellites provide images of the battlefield.", exJa: "衛星は戦場の画像を提供する。" },
  { en: "encryption", pos: "名詞", kana: "エンクリプション", ja: "暗号化", ex: "Strong encryption protects user messages.", exJa: "強力な暗号化はユーザーのメッセージを守る。" },
  { en: "hacker", pos: "名詞", kana: "ハッカー", ja: "ハッカー", ex: "Hackers stole data from the hospital.", exJa: "ハッカーが病院からデータを盗んだ。" },
  { en: "malware", pos: "名詞", kana: "マルウェア", ja: "マルウェア", ex: "Malware can damage your computer files.", exJa: "マルウェアはコンピューターのファイルを損なうことがある。" },
  { en: "breach", pos: "名詞", kana: "ブリーチ", ja: "侵害・突破", ex: "The company reported a major data breach.", exJa: "その会社は大規模なデータ侵害を報告した。" },
  { en: "cognitive", pos: "形容詞", kana: "コグニティブ", ja: "認知の", ex: "AI aims to mimic cognitive human abilities.", exJa: "AIは人間の認知能力を模倣することを目指す。" },
  { en: "synthetic", pos: "形容詞", kana: "シンセティック", ja: "合成の・人工の", ex: "Synthetic media can spread false videos.", exJa: "合成メディアは偽の動画を広めることがある。" },
  { en: "chatbot", pos: "名詞", kana: "チャットボット", ja: "チャットボット", ex: "Many websites use a chatbot for support.", exJa: "多くのウェブサイトがサポートにチャットボットを使う。" },
  { en: "prompt", pos: "名詞", kana: "プロンプト", ja: "指示文", ex: "A clear prompt helps the AI give better answers.", exJa: "明確な指示文はAIにより良い回答を得るのに役立つ。" },
  { en: "dataset", pos: "名詞", kana: "データセット", ja: "データセット", ex: "The team built a large training dataset.", exJa: "チームは大規模な学習用データセットを構築した。" },
  { en: "feedback", pos: "名詞", kana: "フィードバック", ja: "フィードバック", ex: "User feedback improved the new feature.", exJa: "ユーザーのフィードバックが新機能を改善した。" },
  { en: "recognition", pos: "名詞", kana: "レコグニション", ja: "認識", ex: "Facial recognition raises privacy concerns.", exJa: "顔認識はプライバシーの懸念を呼ぶ。" },
  { en: "quantum", pos: "形容詞", kana: "クァンタム", ja: "量子の", ex: "Quantum computers could change cryptography.", exJa: "量子コンピューターは暗号技術を変える可能性がある。" },
  { en: "broadband", pos: "名詞", kana: "ブロードバンド", ja: "ブロードバンド", ex: "Rural areas still lack fast broadband.", exJa: "農村地域には依然として高速ブロードバンドが不足している。" },
  { en: "connectivity", pos: "名詞", kana: "コネクティヴィティ", ja: "接続性", ex: "Internet connectivity is vital for education.", exJa: "インターネット接続は教育に不可欠だ。" },
  { en: "integrate", pos: "動詞", kana: "インテグレイト", ja: "統合する", ex: "Schools plan to integrate AI into classes.", exJa: "学校はAIを授業に統合する計画だ。" },
  { en: "patent", pos: "名詞", kana: "パテント", ja: "特許", ex: "The firm filed a patent for the invention.", exJa: "その会社は発明の特許を出願した。" },
  { en: "subscription", pos: "名詞", kana: "サブスクリプション", ja: "定期購読", ex: "The service runs on a monthly subscription.", exJa: "そのサービスは月額サブスクリプションで運営される。" },
  { en: "storage", pos: "名詞", kana: "ストレージ", ja: "ストレージ", ex: "Cloud storage makes sharing files easier.", exJa: "クラウドストレージはファイル共有を容易にする。" },
  { en: "upgrade", pos: "動詞・名詞", kana: "アップグレード", ja: "アップグレードする／改良", ex: "Users were asked to upgrade the software.", exJa: "ユーザーはソフトのアップグレードを求められた。" },
  { en: "compatible", pos: "形容詞", kana: "コンパティブル", ja: "互換性のある", ex: "The app is compatible with older phones.", exJa: "そのアプリは古いスマホとも互換性がある。" },
  { en: "prototype", pos: "名詞", kana: "プロトタイプ", ja: "試作品", ex: "Engineers tested a working prototype.", exJa: "技術者は動作する試作品を試験した。" },
  { en: "simulation", pos: "名詞", kana: "シミュレーション", ja: "シミュレーション", ex: "The simulation predicted traffic congestion.", exJa: "そのシミュレーションは交通渋滞を予測した。" },
  { en: "hardware", pos: "名詞", kana: "ハードウェア", ja: "ハードウェア", ex: "The company also sells computer hardware.", exJa: "その会社はコンピューターハードウェアも販売する。" },
  { en: "bandwidth", pos: "名詞", kana: "バンドウィズ", ja: "帯域幅", ex: "Video calls require more bandwidth.", exJa: "ビデオ通話はより多くの帯域幅を必要とする。" },
  { en: "cyber", pos: "形容詞", kana: "サイバー", ja: "サイバーの", ex: "The nation faces growing cyber threats.", exJa: "その国は増大するサイバー脅威に直面している。" },
  { en: "blockchain", pos: "名詞", kana: "ブロックチェーン", ja: "ブロックチェーン", ex: "Blockchain technology tracks digital transactions.", exJa: "ブロックチェーン技術はデジタル取引を追跡する。" },
  { en: "compile", pos: "動詞", kana: "コンパイル", ja: "編集する・コンパイルする", ex: "Researchers compile data from many sources.", exJa: "研究者は多くの情報源からデータを編集する。" },
  { en: "calibrate", pos: "動詞", kana: "キャリブレイト", ja: "調整する・校正する", ex: "Technicians calibrate the sensors every month.", exJa: "技術者は毎月センサーを校正する。" },
  { en: "download", pos: "動詞・名詞", kana: "ダウンロード", ja: "ダウンロードする／ダウンロード", ex: "Users can download the update for free.", exJa: "ユーザーは無料で更新をダウンロードできる。" },
  { en: "upload", pos: "動詞", kana: "アップロード", ja: "アップロードする", ex: "Please upload your documents to the portal.", exJa: "書類をポータルにアップロードしてください。" },
  { en: "wireless", pos: "形容詞", kana: "ワイアレス", ja: "無線の", ex: "Wireless networks connect devices without cables.", exJa: "無線ネットワークはケーブルなしで機器を接続する。" },
  { en: "mainframe", pos: "名詞", kana: "メインフレーム", ja: "大型コンピュータ", ex: "Banks still rely on mainframe systems.", exJa: "銀行は依然として大型コンピュータシステムに依存している。" },
  { en: "debug", pos: "動詞", kana: "デバッグ", ja: "デバッグする", ex: "Engineers spent days debugging the code.", exJa: "技術者はコードのデバッグに数日を費やした。" },
  { en: "render", pos: "動詞", kana: "レンダー", ja: "描画する・生成する", ex: "The software can render images in seconds.", exJa: "そのソフトは数秒で画像を生成できる。" },
  { en: "latency", pos: "名詞", kana: "レイテンシー", ja: "遅延", ex: "High latency makes video calls frustrating.", exJa: "高い遅延はビデオ通話をいらだたしくする。" },
  { en: "metadata", pos: "名詞", kana: "メタデータ", ja: "メタデータ", ex: "Metadata reveals when the photo was taken.", exJa: "メタデータは写真がいつ撮られたかを示す。" },
  { en: "open-source", pos: "形容詞", kana: "オープンソース", ja: "オープンソースの", ex: "The open-source model attracted many developers.", exJa: "そのオープンソースモデルは多くの開発者を引き付けた。" },

  // ---------- 中級・追加 戦争・軍事・外交 ----------
  { en: "combat", pos: "名詞・動詞", kana: "コンバット", ja: "戦闘／戦う", ex: "Combat continued through the night.", exJa: "戦闘は夜通し続いた。" },
  { en: "battlefield", pos: "名詞", kana: "バトルフィールド", ja: "戦場", ex: "Aid workers could not reach the battlefield.", exJa: "援助工作者は戦場に到達できなかった。" },
  { en: "artillery", pos: "名詞", kana: "アーティレリー", ja: "大砲・砲撃", ex: "Artillery fire shook the nearby town.", exJa: "砲撃が近くの町を揺らした。" },
  { en: "ammunition", pos: "名詞", kana: "アミュニション", ja: "弾薬", ex: "Troops were running low on ammunition.", exJa: "部隊の弾薬が残り少なくなっていた。" },
  { en: "strategy", pos: "名詞", kana: "ストラテジー", ja: "戦略", ex: "Military strategy changed after the defeat.", exJa: "敗北後に軍事戦略が変わった。" },
  { en: "tactical", pos: "形容詞", kana: "タクティカル", ja: "戦術的な", ex: "The army made a tactical retreat.", exJa: "軍は戦術的撤退を行った。" },
  { en: "logistics", pos: "名詞", kana: "ロジスティックス", ja: "兵站・物流", ex: "Poor logistics slowed the relief effort.", exJa: "兵站の不備が救援活動を遅らせた。" },
  { en: "reinforce", pos: "動詞", kana: "リインフォース", ja: "増援する・強化する", ex: "The government sent troops to reinforce the border.", exJa: "政府は国境を強化するため部隊を送った。" },
  { en: "occupation", pos: "名詞", kana: "オキュペイション", ja: "占領", ex: "The occupation lasted more than a decade.", exJa: "その占領は10年以上続いた。" },
  { en: "resistance", pos: "名詞", kana: "レジスタンス", ja: "抵抗", ex: "Local resistance grew against the invaders.", exJa: "侵略者に対する地元の抵抗が強まった。" },
  { en: "rebellion", pos: "名詞", kana: "リベリオン", ja: "反乱", ex: "The rebellion was crushed within weeks.", exJa: "その反乱は数週間で鎮圧された。" },
  { en: "coup", pos: "名詞", kana: "クー", ja: "クーデター", ex: "A military coup toppled the president.", exJa: "軍事クーデターが大統領を倒した。" },
  { en: "truce", pos: "名詞", kana: "トゥルース", ja: "休戦", ex: "The two sides agreed to a temporary truce.", exJa: "双方は一時的な休戦に合意した。" },
  { en: "armistice", pos: "名詞", kana: "アーミスティス", ja: "休戦協定", ex: "An armistice ended the fighting.", exJa: "休戦協定が戦闘を終わらせた。" },
  { en: "prisoner", pos: "名詞", kana: "プリズナー", ja: "囚人・捕虜", ex: "Prisoners were exchanged after the talks.", exJa: "協議の後に捕虜が交換された。" },
  { en: "ambush", pos: "名詞・動詞", kana: "アンブッシュ", ja: "待ち伏せ／待ち伏せする", ex: "Rebels ambushed a military convoy.", exJa: "反乱軍が軍の護送隊を待ち伏せした。" },
  { en: "bombard", pos: "動詞", kana: "ボンバード", ja: "砲撃する", ex: "Forces bombarded the port for hours.", exJa: "軍は何時間も港を砲撃した。" },
  { en: "airstrike", pos: "名詞", kana: "エアストライク", ja: "空爆", ex: "An airstrike hit a residential area.", exJa: "空爆が住宅地を襲った。" },
  { en: "navy", pos: "名詞", kana: "ネイヴィ", ja: "海軍", ex: "The navy patrolled the coastal waters.", exJa: "海軍が沿岸海域をパトロールした。" },
  { en: "battalion", pos: "名詞", kana: "バタリオン", ja: "大隊", ex: "A battalion was deployed to the front.", exJa: "大隊が前線に配備された。" },
  { en: "commander", pos: "名詞", kana: "コマンダー", ja: "司令官", ex: "The commander ordered a full retreat.", exJa: "司令官は全面撤退を命じた。" },
  { en: "veteran", pos: "名詞", kana: "ヴェテラン", ja: "退役軍人・ベテラン", ex: "Veterans marched to honor the fallen.", exJa: "退役軍人たちが戦死者を悼んで行進した。" },
  { en: "wounded", pos: "形容詞", kana: "ウーンデッド", ja: "負傷した", ex: "Wounded soldiers were rushed to hospitals.", exJa: "負傷した兵士が病院に急送された。" },
  { en: "fatality", pos: "名詞", kana: "ファタリティ", ja: "死亡者", ex: "Officials confirmed three fatalities.", exJa: "当局は3名の死亡を確認した。" },
  { en: "rubble", pos: "名詞", kana: "ラブル", ja: "がれき", ex: "Rescuers searched through the rubble.", exJa: "救助隊ががれきの中を捜索した。" },
  { en: "blockade", pos: "名詞・動詞", kana: "ブロッケード", ja: "封鎖／封鎖する", ex: "A naval blockade cut off food supplies.", exJa: "海上封鎖が食料供給を断った。" },
  { en: "embargo", pos: "名詞", kana: "エンバーゴ", ja: "禁輸", ex: "The UN imposed an arms embargo.", exJa: "国連は武器禁輸を課した。" },
  { en: "territory", pos: "名詞", kana: "テリトリー", ja: "領土・地域", ex: "Both sides claim the same territory.", exJa: "双方が同じ領土を主張している。" },
  { en: "territorial", pos: "形容詞", kana: "テリトリアル", ja: "領土の", ex: "Territorial disputes fuel regional tension.", exJa: "領土問題が地域の緊張を煽る。" },
  { en: "cease", pos: "動詞", kana: "シース", ja: "やめる・停止する", ex: "Both armies agreed to cease hostilities.", exJa: "両軍は敵対行為を停止することに同意した。" },
  { en: "disarm", pos: "動詞", kana: "ディサーム", ja: "武装解除する", ex: "Peace talks aim to disarm rebel groups.", exJa: "和平交渉は反乱グループの武装解除を目指す。" },
  { en: "reconnaissance", pos: "名詞", kana: "リコネッサンス", ja: "偵察", ex: "Drones flew reconnaissance missions overnight.", exJa: "ドローンが夜間に偵察任務を飛んだ。" },
  { en: "fortify", pos: "動詞", kana: "フォーティファイ", ja: "要塞化する・強化する", ex: "Troops fortified positions along the river.", exJa: "部隊は川沿いの陣地を強化した。" },
  { en: "surrender", pos: "動詞・名詞", kana: "サレンダー", ja: "降伏する／降伏", ex: "The unit refused to surrender.", exJa: "その部隊は降伏を拒んだ。" },
  { en: "raid", pos: "名詞・動詞", kana: "レイド", ja: "襲撃／襲撃する", ex: "Police conducted a raid on the warehouse.", exJa: "警察が倉庫への襲撃を行った。" },
  { en: "sniper", pos: "名詞", kana: "スナイパー", ja: "狙撃兵", ex: "A sniper targeted officers near the square.", exJa: "狙撃兵が広場近くの将校を狙った。" },
  { en: "minefield", pos: "名詞", kana: "マインフィールド", ja: "地雷原", ex: "The road was blocked by a minefield.", exJa: "道路は地雷原によって遮断された。" },
  { en: "armored", pos: "形容詞", kana: "アーマード", ja: "装甲の", ex: "Armored vehicles rolled into the city.", exJa: "装甲車が都市に入った。" },
  { en: "peacekeeping", pos: "名詞", kana: "ピースキーピング", ja: "平和維持", ex: "UN peacekeeping forces monitored the area.", exJa: "国連平和維持軍が地域を監視した。" },
  { en: "mediator", pos: "名詞", kana: "メディエイター", ja: "仲介者", ex: "A mediator helped restart the talks.", exJa: "仲介者が協議の再開を助けた。" },
  { en: "summit", pos: "名詞", kana: "サミット", ja: "首脳会議", ex: "Leaders met at an emergency summit.", exJa: "首脳たちが緊急首脳会議で会った。" },
  { en: "ally", pos: "名詞", kana: "アライ", ja: "同盟国・味方", ex: "The country asked its allies for help.", exJa: "その国は同盟国に支援を求めた。" },
  { en: "adversary", pos: "名詞", kana: "アドヴァーサリー", ja: "敵対者", ex: "The two adversaries finally held talks.", exJa: "二人の敵対者がついに会談を持った。" },
  { en: "militia", pos: "名詞", kana: "ミリシア", ja: "民兵", ex: "Local militias control parts of the region.", exJa: "地元の民兵が地域の一部を支配している。" },
  { en: "guerrilla", pos: "名詞", kana: "ゲリラ", ja: "ゲリラ", ex: "Guerrilla fighters attacked the convoy.", exJa: "ゲリラ戦士が護送隊を攻撃した。" },
  { en: "rebel", pos: "名詞", kana: "レベル", ja: "反乱者", ex: "Rebels seized control of the airport.", exJa: "反乱者が空港の支配権を奪った。" },
  { en: "patrol", pos: "名詞・動詞", kana: "パトロール", ja: "パトロール／巡回する", ex: "Soldiers patrol the streets at night.", exJa: "兵士が夜に通りをパトロールする。" },
  { en: "convoy", pos: "名詞", kana: "コンヴォイ", ja: "護送隊", ex: "A convoy brought food to the besieged city.", exJa: "護送隊が包囲された都市に食料を運んだ。" },

  // ---------- 中級・追加 政治・経済・社会 ----------
  { en: "parliament", pos: "名詞", kana: "パーラメント", ja: "議会", ex: "Parliament debated the new budget.", exJa: "議会は新予算を議論した。" },
  { en: "congress", pos: "名詞", kana: "コングレス", ja: "議会（米）", ex: "Congress passed the spending bill.", exJa: "議会は支出法案を可決した。" },
  { en: "senator", pos: "名詞", kana: "セネター", ja: "上院議員", ex: "The senator criticized the foreign policy.", exJa: "上院議員が外交政策を批判した。" },
  { en: "minister", pos: "名詞", kana: "ミニスター", ja: "大臣", ex: "The finance minister resigned yesterday.", exJa: "財務大臣が昨日辞任した。" },
  { en: "cabinet", pos: "名詞", kana: "キャビネット", ja: "内閣", ex: "The cabinet approved the emergency plan.", exJa: "内閣は緊急計画を承認した。" },
  { en: "democracy", pos: "名詞", kana: "デモクラシー", ja: "民主主義", ex: "Voters defended democracy at the polls.", exJa: "有権者は投票所で民主主義を守った。" },
  { en: "constitution", pos: "名詞", kana: "コンスティテューション", ja: "憲法", ex: "The court upheld the constitution.", exJa: "裁判所は憲法を支持した。" },
  { en: "amendment", pos: "名詞", kana: "アメンドメント", ja: "修正条項", ex: "Lawmakers proposed a constitutional amendment.", exJa: "議員が憲法修正条項を提案した。" },
  { en: "referendum", pos: "名詞", kana: "レファレンダム", ja: "国民投票", ex: "A referendum will decide the issue.", exJa: "国民投票がその問題を決める。" },
  { en: "ballot", pos: "名詞", kana: "バロット", ja: "投票用紙", ex: "Millions cast their ballots early.", exJa: "何百万もの人が早期投票した。" },
  { en: "voter", pos: "名詞", kana: "ヴォーター", ja: "有権者", ex: "Voters lined up before polls opened.", exJa: "有権者は投票開始前に並んだ。" },
  { en: "campaign", pos: "名詞・動詞", kana: "キャンペーン", ja: "選挙運動／運動する", ex: "The campaign focused on economic reform.", exJa: "選挙運動は経済改革に焦点を当てた。" },
  { en: "candidate", pos: "名詞", kana: "キャンディデイト", ja: "候補者", ex: "Three candidates entered the race.", exJa: "3人の候補者が選挙に参加した。" },
  { en: "opposition", pos: "名詞", kana: "オポジション", ja: "野党・反対", ex: "The opposition blocked the bill.", exJa: "野党が法案を阻止した。" },
  { en: "majority", pos: "名詞", kana: "マジョリティ", ja: "多数", ex: "The party won a clear majority.", exJa: "その政党は明確な多数を獲得した。" },
  { en: "minority", pos: "名詞", kana: "マイノリティ", ja: "少数", ex: "Minority groups demanded equal rights.", exJa: "少数派グループが平等な権利を求めた。" },
  { en: "verdict", pos: "名詞", kana: "ヴァーディクト", ja: "評決", ex: "The jury reached a guilty verdict.", exJa: "陪審は有罪の評決に達した。" },
  { en: "trial", pos: "名詞", kana: "トライアル", ja: "裁判", ex: "The trial is expected to last months.", exJa: "裁判は数か月続く見込みだ。" },
  { en: "defendant", pos: "名詞", kana: "ディフェンダント", ja: "被告", ex: "The defendant denied all charges.", exJa: "被告はすべての罪状を否定した。" },
  { en: "prosecutor", pos: "名詞", kana: "プロセキューター", ja: "検察官", ex: "The prosecutor presented new evidence.", exJa: "検察官が新しい証拠を提示した。" },
  { en: "witness", pos: "名詞", kana: "ウィットネス", ja: "証人", ex: "A key witness testified in court.", exJa: "重要な証人が法廷で証言した。" },
  { en: "corruption", pos: "名詞", kana: "コラプション", ja: "汚職", ex: "Corruption scandals shook the government.", exJa: "汚職スキャンダルが政府を揺るがした。" },
  { en: "scandal", pos: "名詞", kana: "スキャンダル", ja: "スキャンダル", ex: "The scandal forced the CEO to resign.", exJa: "スキャンダルがCEOの辞任を余儀なくした。" },
  { en: "tax", pos: "名詞・動詞", kana: "タックス", ja: "税／課税する", ex: "The government raised taxes on imports.", exJa: "政府は輸入税を引き上げた。" },
  { en: "tariff", pos: "名詞", kana: "タリフ", ja: "関税", ex: "New tariffs raised the price of steel.", exJa: "新関税が鉄鋼の価格を押し上げた。" },
  { en: "deficit", pos: "名詞", kana: "デフィシット", ja: "赤字", ex: "The budget deficit widened this year.", exJa: "財政赤字は今年拡大した。" },
  { en: "debt", pos: "名詞", kana: "デット", ja: "借金・債務", ex: "National debt reached a record high.", exJa: "国債が過去最高に達した。" },
  { en: "budget", pos: "名詞", kana: "バジェット", ja: "予算", ex: "Lawmakers approved the annual budget.", exJa: "議員は年間予算を承認した。" },
  { en: "unemployment", pos: "名詞", kana: "アンモイメント", ja: "失業", ex: "Unemployment rose in rural areas.", exJa: "農村地域で失業が増えた。" },
  { en: "wage", pos: "名詞", kana: "ウェイジ", ja: "賃金", ex: "Workers demanded higher wages.", exJa: "労働者はより高い賃金を求めた。" },
  { en: "pension", pos: "名詞", kana: "ペンション", ja: "年金", ex: "Reforms will affect public pensions.", exJa: "改革は公的年金に影響する。" },
  { en: "welfare", pos: "名詞", kana: "ウェルフェア", ja: "福祉", ex: "Welfare spending increased during the crisis.", exJa: "危機の間に福祉支出が増えた。" },
  { en: "poverty", pos: "名詞", kana: "ポヴァティ", ja: "貧困", ex: "Poverty rates climbed after the recession.", exJa: "景気後退後に貧困率が上昇した。" },
  { en: "inequality", pos: "名詞", kana: "イニクァリティ", ja: "不平等", ex: "Inequality remains a political issue.", exJa: "不平等は依然として政治問題だ。" },
  { en: "statistic", pos: "名詞", kana: "スタティスティック", ja: "統計", ex: "Official statistics show slower growth.", exJa: "公式統計は成長の鈍化を示している。" },
  { en: "survey", pos: "名詞・動詞", kana: "サーベイ", ja: "調査／調査する", ex: "A survey found rising public anxiety.", exJa: "調査は国民の不安の高まりを見つけた。" },
  { en: "poll", pos: "名詞", kana: "ポール", ja: "世論調査", ex: "The latest poll shows a tight race.", exJa: "最新の世論調査は接戦を示している。" },
  { en: "forecast", pos: "名詞・動詞", kana: "フォーキャスト", ja: "予測／予測する", ex: "Analysts forecast stronger growth next year.", exJa: "アナリストは来年の成長加速を予測している。" },
  { en: "index", pos: "名詞", kana: "インデックス", ja: "指数", ex: "The consumer price index rose again.", exJa: "消費者物価指数が再び上昇した。" },
  { en: "currency", pos: "名詞", kana: "カレンシー", ja: "通貨", ex: "The currency weakened against the dollar.", exJa: "通貨がドルに対して弱くなった。" },
  { en: "invest", pos: "動詞", kana: "インヴェスト", ja: "投資する", ex: "Firms invest heavily in renewable energy.", exJa: "企業は再生可能エネルギーに多額を投資する。" },
  { en: "investor", pos: "名詞", kana: "インヴェスター", ja: "投資家", ex: "Investors reacted to the earnings report.", exJa: "投資家は決算報告に反応した。" },
  { en: "bankruptcy", pos: "名詞", kana: "バンクラプシー", ja: "破産", ex: "The retailer filed for bankruptcy.", exJa: "その小売業者は破産を申請した。" },
  { en: "merger", pos: "名詞", kana: "マージャー", ja: "合併", ex: "The merger created the largest airline.", exJa: "合併が最大の航空会社を生んだ。" },
  { en: "acquisition", pos: "名詞", kana: "アクイジション", ja: "買収", ex: "The acquisition cost over ten billion.", exJa: "その買収は100億ドル以上かかった。" },
  { en: "shareholder", pos: "名詞", kana: "シェアホルダー", ja: "株主", ex: "Shareholders voted against the proposal.", exJa: "株主はその提案に反対票を投じた。" },
  { en: "dividend", pos: "名詞", kana: "ディヴィデンド", ja: "配当", ex: "The company raised its dividend.", exJa: "その会社は配当を増やした。" },
  { en: "revenue", pos: "名詞", kana: "レヴェニュー", ja: "収益", ex: "Quarterly revenue beat expectations.", exJa: "四半期収益は予想を上回った。" },
  { en: "profit", pos: "名詞", kana: "プロフィット", ja: "利益", ex: "Profits fell due to higher costs.", exJa: "コスト増で利益が減った。" },
  { en: "consumer", pos: "名詞", kana: "コンシューマー", ja: "消費者", ex: "Consumers are spending less on luxury goods.", exJa: "消費者は奢侈品への支出を減らしている。" },

  // ---------- 中級・追加 気候・健康・報道・一般動詞 ----------
  { en: "climate", pos: "名詞", kana: "クライメット", ja: "気候", ex: "Climate change threatens coastal cities.", exJa: "気候変動が沿岸都市を脅かす。" },
  { en: "emission", pos: "名詞", kana: "エミッション", ja: "排出", ex: "The law caps carbon emissions.", exJa: "法律は炭素排出に上限を設ける。" },
  { en: "renewable", pos: "形容詞", kana: "リニューアブル", ja: "再生可能な", ex: "Renewable energy now powers half the grid.", exJa: "再生可能エネルギーが送電網の半分を賄う。" },
  { en: "sustainability", pos: "名詞", kana: "サステイナビリティ", ja: "持続可能性", ex: "Firms promote sustainability in supply chains.", exJa: "企業はサプライチェーンの持続可能性を推進する。" },
  { en: "drought", pos: "名詞", kana: "ドラウト", ja: "干ばつ", ex: "A severe drought destroyed the harvest.", exJa: "深刻な干ばつが収穫を台無しにした。" },
  { en: "flood", pos: "名詞・動詞", kana: "フラッド", ja: "洪水／氾濫する", ex: "Floods displaced thousands of families.", exJa: "洪水が何千もの家族を避難させた。" },
  { en: "hurricane", pos: "名詞", kana: "ハリケーン", ja: "ハリケーン", ex: "The hurricane knocked out power for days.", exJa: "ハリケーンが数日間停電を引き起こした。" },
  { en: "earthquake", pos: "名詞", kana: "アースクエイク", ja: "地震", ex: "The earthquake damaged roads and bridges.", exJa: "地震が道路と橋を損傷した。" },
  { en: "wildfire", pos: "名詞", kana: "ワイルドファイア", ja: "山火事", ex: "Wildfires spread across the dry hills.", exJa: "山火事が乾いた丘陵地帯に広がった。" },
  { en: "carbon", pos: "名詞", kana: "カーボン", ja: "炭素", ex: "Nations pledged to cut carbon output.", exJa: "各国は炭素排出削減を約束した。" },
  { en: "fossil", pos: "名詞", kana: "フォッシル", ja: "化石燃料", ex: "The plan phases out fossil fuels.", exJa: "その計画は化石燃料を段階的に廃止する。" },
  { en: "habitat", pos: "名詞", kana: "ハビタット", ja: "生息地", ex: "Logging destroyed critical wildlife habitat.", exJa: "伐採が重要な野生動物の生息地を破壊した。" },
  { en: "species", pos: "名詞", kana: "スピーシーズ", ja: "種", ex: "Many species face extinction.", exJa: "多くの種が絶滅の危機に直面している。" },
  { en: "biodiversity", pos: "名詞", kana: "バイオダイバーシティ", ja: "生物多様性", ex: "The park protects local biodiversity.", exJa: "その公園は地域の生物多様性を守る。" },
  { en: "pandemic", pos: "名詞", kana: "パンデミック", ja: "パンデミック", ex: "The pandemic disrupted global travel.", exJa: "パンデミックが世界の旅を混乱させた。" },
  { en: "vaccine", pos: "名詞", kana: "ヴァクシーン", ja: "ワクチン", ex: "A new vaccine was approved for children.", exJa: "子ども向けの新ワクチンが承認された。" },
  { en: "outbreak", pos: "名詞", kana: "アウトブレイク", ja: "発生・流行", ex: "An outbreak was reported at the factory.", exJa: "工場で感染の発生が報告された。" },
  { en: "infection", pos: "名詞", kana: "インフェクション", ja: "感染", ex: "Infection rates fell after the campaign.", exJa: "感染率はキャンペーン後に低下した。" },
  { en: "epidemic", pos: "名詞", kana: "エピデミック", ja: "流行病", ex: "The epidemic overwhelmed local hospitals.", exJa: "流行病が地元の病院を圧倒した。" },
  { en: "symptom", pos: "名詞", kana: "シンプトム", ja: "症状", ex: "Fever is a common symptom of the illness.", exJa: "発熱はその病気の一般的な症状だ。" },
  { en: "treatment", pos: "名詞", kana: "トリートメント", ja: "治療", ex: "Early treatment saves lives.", exJa: "早期治療が命を救う。" },
  { en: "healthcare", pos: "名詞", kana: "ヘルスケア", ja: "医療・ヘルスケア", ex: "Healthcare costs continue to rise.", exJa: "医療費は上昇し続けている。" },
  { en: "pharmaceutical", pos: "形容詞", kana: "ファーマシューティカル", ja: "製薬の", ex: "A pharmaceutical firm developed the drug.", exJa: "製薬会社がその薬を開発した。" },
  { en: "journalism", pos: "名詞", kana: "ジャーナリズム", ja: "ジャーナリズム", ex: "Independent journalism is under pressure.", exJa: "独立系ジャーナリズムは圧力を受けている。" },
  { en: "journalist", pos: "名詞", kana: "ジャーナリスト", ja: "記者", ex: "Journalists reported from the front line.", exJa: "記者たちが前線から報道した。" },
  { en: "headline", pos: "名詞", kana: "ヘッドライン", ja: "見出し", ex: "The headline dominated the morning news.", exJa: "その見出しが朝のニュースを占めた。" },
  { en: "editorial", pos: "名詞", kana: "エディトリアル", ja: "社説", ex: "The editorial urged leaders to act.", exJa: "社説は指導者たちの行動を促した。" },
  { en: "censorship", pos: "名詞", kana: "センサーシップ", ja: "検閲", ex: "Critics condemned online censorship.", exJa: "批判する人々はオンライン検閲を非難した。" },
  { en: "freedom", pos: "名詞", kana: "フリーダム", ja: "自由", ex: "Protesters demanded freedom of speech.", exJa: "抗議者は言論の自由を求めた。" },
  { en: "justice", pos: "名詞", kana: "ジャスティス", ja: "正義・司法", ex: "Families called for justice after the attack.", exJa: "家族たちは攻撃後の正義を求めた。" },
  { en: "equality", pos: "名詞", kana: "イコールリティ", ja: "平等", ex: "The law promotes gender equality.", exJa: "法律は男女平等を推進する。" },
  { en: "discrimination", pos: "名詞", kana: "ディスクリミネイション", ja: "差別", ex: "The firm was sued for discrimination.", exJa: "その会社は差別で訴えられた。" },
  { en: "immigrant", pos: "名詞", kana: "イミグラント", ja: "移民", ex: "Immigrants built many of the nation's cities.", exJa: "移民が国の多くの都市を築いた。" },
  { en: "citizenship", pos: "名詞", kana: "シティズンシップ", ja: "市民権", ex: "She applied for citizenship last year.", exJa: "彼女は昨年市民権を申請した。" },
  { en: "asylum", pos: "名詞", kana: "アサイラム", ja: "亡命", ex: "Thousands sought asylum at the border.", exJa: "何千人もの人が国境で亡命を求めた。" },
  { en: "deport", pos: "動詞", kana: "ディポート", ja: "国外退去させる", ex: "Authorities plan to deport illegal workers.", exJa: "当局は不法労働者の国外退去を計画している。" },
  { en: "confirm", pos: "動詞", kana: "コンファーム", ja: "確認する", ex: "Officials confirmed the death toll.", exJa: "当局は死者数を確認した。" },
  { en: "deny", pos: "動詞", kana: "ディナイ", ja: "否定する", ex: "The company denied any wrongdoing.", exJa: "その会社は不正行為を否定した。" },
  { en: "reject", pos: "動詞", kana: "リジェクト", ja: "拒否する", ex: "Lawmakers rejected the peace proposal.", exJa: "議員は和平提案を拒否した。" },
  { en: "approve", pos: "動詞", kana: "アプルーブ", ja: "承認する", ex: "Regulators approved the new drug.", exJa: "規制当局が新薬を承認した。" },
  { en: "oppose", pos: "動詞", kana: "オポーズ", ja: "反対する", ex: "Residents oppose the new highway.", exJa: "住民は新高速道路に反対している。" },
  { en: "urge", pos: "動詞", kana: "アージ", ja: "強く勧める", ex: "Doctors urge people to get vaccinated.", exJa: "医師は人々にワクチン接種を強く勧める。" },
  { en: "acknowledge", pos: "動詞", kana: "アクノレッジ", ja: "認める", ex: "The CEO acknowledged serious mistakes.", exJa: "CEOは深刻な過ちを認めた。" },
  { en: "postpone", pos: "動詞", kana: "ポストポーン", ja: "延期する", ex: "Elections were postponed due to flooding.", exJa: "洪水のため選挙が延期された。" },
  { en: "suspend", pos: "動詞", kana: "サスペンド", ja: "一時停止する", ex: "The airline suspended flights to the region.", exJa: "航空会社はその地域への便を一時停止した。" },
  { en: "restore", pos: "動詞", kana: "リストア", ja: "回復させる", ex: "Workers restored power within hours.", exJa: "作業員は数時間以内に電力を回復した。" },
  { en: "recover", pos: "動詞", kana: "リカバー", ja: "回復する", ex: "The economy may recover next year.", exJa: "経済は来年回復するかもしれない。" },
  { en: "stabilize", pos: "動詞", kana: "ステイブライズ", ja: "安定させる", ex: "Central banks moved to stabilize markets.", exJa: "中央銀行が市場を安定させる動きを見せた。" },
  { en: "collapse", pos: "動詞・名詞", kana: "コラプス", ja: "崩壊する／崩壊", ex: "The bridge collapsed during the storm.", exJa: "橋が嵐の間に崩壊した。" },
  { en: "strengthen", pos: "動詞", kana: "ストレングスン", ja: "強化する", ex: "Allies strengthened their defense ties.", exJa: "同盟国は防衛協力を強化した。" },
  { en: "weaken", pos: "動詞", kana: "ウィーケン", ja: "弱める", ex: "The scandal weakened public trust.", exJa: "スキャンダルが国民の信頼を弱めた。" },
  { en: "dominate", pos: "動詞", kana: "ドミネイト", ja: "支配する", ex: "One company dominates the online market.", exJa: "一社がオンライン市場を支配している。" },
  { en: "emerge", pos: "動詞", kana: "イマージ", ja: "浮上する・出現する", ex: "New details emerged after the raid.", exJa: "襲撃後に新たな詳細が浮上した。" },
  { en: "tackle", pos: "動詞", kana: "タックル", ja: "取り組む", ex: "Leaders met to tackle climate change.", exJa: "指導者たちが気候変動に取り組むため会った。" },
  { en: "confront", pos: "動詞", kana: "コンフロント", ja: "直面する・立ち向かう", ex: "Nations must confront shared threats.", exJa: "各国は共通の脅威に立ち向かわなければならない。" },
  { en: "ensure", pos: "動詞", kana: "エンシュア", ja: "確実にする", ex: "Laws ensure fair access to healthcare.", exJa: "法律は公平な医療アクセスを確実にする。" },
  { en: "guarantee", pos: "動詞・名詞", kana: "ギャランティー", ja: "保証する／保証", ex: "The treaty cannot guarantee lasting peace.", exJa: "条約は永続的な平和を保証できない。" },
  { en: "violate", pos: "動詞", kana: "ヴァイオレイト", ja: "違反する", ex: "The strike violated the ceasefire.", exJa: "その攻撃は停戦に違反した。" },
  { en: "enforce", pos: "動詞", kana: "エンフォース", ja: "施行する・強制する", ex: "Police enforce the new traffic rules.", exJa: "警察は新しい交通規則を施行する。" },
  { en: "legitimate", pos: "形容詞", kana: "レジティメイト", ja: "正当な", ex: "Voters questioned the legitimate result.", exJa: "有権者は正当な結果に疑問を持った。" },
  { en: "crucial", pos: "形容詞", kana: "クルーシャル", ja: "極めて重要な", ex: "Aid is crucial for surviving winter.", exJa: "援助は冬を乗り切るために極めて重要だ。" },
  { en: "inevitable", pos: "形容詞", kana: "イネヴィタブル", ja: "避けられない", ex: "Some job losses seemed inevitable.", exJa: "一部の失業は避けられないように見えた。" },
  { en: "widespread", pos: "形容詞", kana: "ワイドスプレッド", ja: "広範囲の", ex: "Widespread protests erupted nationwide.", exJa: "全国で広範囲の抗議が勃発した。" },
  { en: "ongoing", pos: "形容詞", kana: "オンゴーイング", ja: "進行中の", ex: "An ongoing investigation slowed the deal.", exJa: "進行中の捜査が取引を遅らせた。" },
  { en: "substantial", pos: "形容詞", kana: "サブスタンシャル", ja: "かなりの・実質的な", ex: "The deal brought substantial economic benefits.", exJa: "その取引はかなりの経済的利益をもたらした。" }
];
