// ============================================================
// 英単語データ（英語ニュース頻出・中級／AI・戦争の話題を中心に）
// ------------------------------------------------------------
// 形式:
//   en   : 英単語
//   pos  : 品詞（名詞・動詞 など）
//   kana : カタカナ発音
//   ja   : 単語の意味
//   ex   : 例文（英語）
//   exJa : 例文の和訳
//
// ★ここに追記すれば単語を増やせます（最終的に3000語などへ拡張可）。
// ============================================================
const DEFAULT_WORDS = [
  // ---------- AI・テクノロジー ----------
  { en: "artificial", pos: "形容詞", kana: "アーティフィシャル", ja: "人工の", ex: "Artificial intelligence is changing many industries.", exJa: "人工知能は多くの産業を変えつつある。" },
  { en: "intelligence", pos: "名詞", kana: "インテリジェンス", ja: "知能・情報", ex: "The system uses artificial intelligence to make decisions.", exJa: "そのシステムは判断のために人工知能を使う。" },
  { en: "algorithm", pos: "名詞", kana: "アルゴリズム", ja: "アルゴリズム・計算手順", ex: "The algorithm recommends videos based on your history.", exJa: "そのアルゴリズムは履歴をもとに動画を勧める。" },
  { en: "data", pos: "名詞", kana: "デイタ／データ", ja: "データ・資料", ex: "The model was trained on a huge amount of data.", exJa: "そのモデルは膨大なデータで訓練された。" },
  { en: "model", pos: "名詞・動詞", kana: "モデル", ja: "モデル・模型／模型を作る", ex: "The new language model can write essays.", exJa: "その新しい言語モデルは小論文を書ける。" },
  { en: "train", pos: "動詞・名詞", kana: "トレイン", ja: "訓練する・学習させる／列車", ex: "Engineers train the AI on millions of images.", exJa: "技術者は何百万もの画像でそのAIを学習させる。" },
  { en: "generate", pos: "動詞", kana: "ジェネレイト", ja: "生成する・生み出す", ex: "The tool can generate text and images.", exJa: "そのツールはテキストや画像を生成できる。" },
  { en: "automate", pos: "動詞", kana: "オートメイト", ja: "自動化する", ex: "Companies use AI to automate boring tasks.", exJa: "企業は退屈な作業を自動化するためにAIを使う。" },
  { en: "automation", pos: "名詞", kana: "オートメイション", ja: "自動化", ex: "Automation may replace some factory jobs.", exJa: "自動化は一部の工場の仕事に取って代わるかもしれない。" },
  { en: "robot", pos: "名詞", kana: "ロウボット", ja: "ロボット", ex: "The factory uses robots to build cars.", exJa: "その工場は車を作るのにロボットを使う。" },
  { en: "device", pos: "名詞", kana: "ディヴァイス", ja: "機器・装置", ex: "Smartphones are powerful computing devices.", exJa: "スマホは強力なコンピューティング機器だ。" },
  { en: "software", pos: "名詞", kana: "ソフトウェア", ja: "ソフトウェア", ex: "They released new software for the system.", exJa: "彼らはそのシステム用の新しいソフトを公開した。" },
  { en: "network", pos: "名詞・動詞", kana: "ネットワーク", ja: "ネットワーク・網／交流する", ex: "A neural network mimics the human brain.", exJa: "ニューラルネットワークは人間の脳をまねる。" },
  { en: "process", pos: "名詞・動詞", kana: "プロセス", ja: "過程／処理する", ex: "The chip can process data very quickly.", exJa: "そのチップはデータを非常に速く処理できる。" },
  { en: "predict", pos: "動詞", kana: "プリディクト", ja: "予測する", ex: "AI can predict the weather more accurately.", exJa: "AIはより正確に天気を予測できる。" },
  { en: "analyze", pos: "動詞", kana: "アナライズ", ja: "分析する", ex: "Scientists analyze the data with computers.", exJa: "科学者はコンピューターでデータを分析する。" },
  { en: "innovation", pos: "名詞", kana: "イノヴェイション", ja: "革新", ex: "AI is driving innovation in medicine.", exJa: "AIは医療における革新を推し進めている。" },
  { en: "technology", pos: "名詞", kana: "テクノロジー", ja: "技術", ex: "New technology spreads around the world fast.", exJa: "新しい技術は世界中に速く広まる。" },
  { en: "digital", pos: "形容詞", kana: "ディジタル", ja: "デジタルの", ex: "We live in a digital age.", exJa: "私たちはデジタル時代に生きている。" },
  { en: "virtual", pos: "形容詞", kana: "ヴァーチャル", ja: "仮想の・事実上の", ex: "They held a virtual meeting online.", exJa: "彼らはオンラインで仮想会議を開いた。" },
  { en: "platform", pos: "名詞", kana: "プラットフォーム", ja: "プラットフォーム・基盤", ex: "Social media platforms reach billions of users.", exJa: "SNSプラットフォームは何十億ものユーザーに届く。" },
  { en: "regulate", pos: "動詞", kana: "レギュレイト", ja: "規制する", ex: "Governments want to regulate AI companies.", exJa: "各国政府はAI企業を規制したがっている。" },
  { en: "regulation", pos: "名詞", kana: "レギュレイション", ja: "規制・規則", ex: "New regulations will affect tech firms.", exJa: "新しい規制はテック企業に影響する。" },
  { en: "privacy", pos: "名詞", kana: "プライヴァシー", ja: "プライバシー", ex: "People worry about their privacy online.", exJa: "人々はオンラインでのプライバシーを心配している。" },
  { en: "security", pos: "名詞", kana: "セキュリティ", ja: "安全・警備・保障", ex: "Cyber security is a growing concern.", exJa: "サイバーセキュリティは増大する懸念だ。" },
  { en: "threat", pos: "名詞", kana: "スレット", ja: "脅威・脅し", ex: "Hackers pose a serious threat to companies.", exJa: "ハッカーは企業に深刻な脅威をもたらす。" },
  { en: "impact", pos: "名詞・動詞", kana: "インパクト", ja: "影響／影響を与える", ex: "AI will have a huge impact on jobs.", exJa: "AIは雇用に大きな影響を与えるだろう。" },
  { en: "replace", pos: "動詞", kana: "リプレイス", ja: "取って代わる・交換する", ex: "Machines may replace many human workers.", exJa: "機械は多くの人間の労働者に取って代わるかもしれない。" },
  { en: "efficient", pos: "形容詞", kana: "イフィシェント", ja: "効率的な", ex: "The new method is faster and more efficient.", exJa: "その新しい方法はより速く効率的だ。" },
  { en: "develop", pos: "動詞", kana: "ディヴェロップ", ja: "開発する・発展させる", ex: "Researchers develop new AI tools every year.", exJa: "研究者は毎年新しいAIツールを開発する。" },
  { en: "research", pos: "名詞・動詞", kana: "リサーチ", ja: "研究／研究する", ex: "The lab does research on machine learning.", exJa: "その研究室は機械学習の研究をしている。" },

  // ---------- 戦争・紛争・軍事 ----------
  { en: "war", pos: "名詞", kana: "ウォー", ja: "戦争", ex: "The war has lasted for several years.", exJa: "その戦争は数年続いている。" },
  { en: "conflict", pos: "名詞・動詞", kana: "コンフリクト", ja: "紛争・対立／対立する", ex: "The conflict forced many people to flee.", exJa: "その紛争は多くの人々を避難させた。" },
  { en: "military", pos: "名詞・形容詞", kana: "ミリタリー", ja: "軍・軍の", ex: "The military launched a new operation.", exJa: "軍は新たな作戦を開始した。" },
  { en: "weapon", pos: "名詞", kana: "ウェポン", ja: "兵器・武器", ex: "Both sides used heavy weapons.", exJa: "双方が重火器を使用した。" },
  { en: "attack", pos: "名詞・動詞", kana: "アタック", ja: "攻撃／攻撃する", ex: "The city was hit by a missile attack.", exJa: "その都市はミサイル攻撃を受けた。" },
  { en: "defense", pos: "名詞", kana: "ディフェンス", ja: "防衛・守り", ex: "The country increased its defense budget.", exJa: "その国は防衛予算を増やした。" },
  { en: "invade", pos: "動詞", kana: "インヴェイド", ja: "侵略する", ex: "Troops invaded the neighboring country.", exJa: "軍隊が隣国に侵攻した。" },
  { en: "invasion", pos: "名詞", kana: "インヴェイジョン", ja: "侵略・侵攻", ex: "The invasion shocked the whole world.", exJa: "その侵攻は世界中に衝撃を与えた。" },
  { en: "troops", pos: "名詞", kana: "トゥループス", ja: "軍隊・部隊", ex: "Thousands of troops were sent to the border.", exJa: "数千の部隊が国境に送られた。" },
  { en: "soldier", pos: "名詞", kana: "ソウルジャー", ja: "兵士", ex: "Many soldiers were wounded in the battle.", exJa: "多くの兵士がその戦闘で負傷した。" },
  { en: "civilian", pos: "名詞・形容詞", kana: "シヴィリアン", ja: "民間人・一般市民／民間の", ex: "The attack killed many civilians.", exJa: "その攻撃で多くの民間人が亡くなった。" },
  { en: "ceasefire", pos: "名詞", kana: "シースファイア", ja: "停戦", ex: "Both sides agreed to a ceasefire.", exJa: "双方が停戦に合意した。" },
  { en: "negotiate", pos: "動詞", kana: "ネゴシエイト", ja: "交渉する", ex: "The leaders met to negotiate peace.", exJa: "首脳たちは和平を交渉するために会った。" },
  { en: "negotiation", pos: "名詞", kana: "ネゴシエイション", ja: "交渉", ex: "Peace negotiations are still ongoing.", exJa: "和平交渉はまだ続いている。" },
  { en: "treaty", pos: "名詞", kana: "トリーティ", ja: "条約", ex: "The two nations signed a peace treaty.", exJa: "両国は和平条約に署名した。" },
  { en: "alliance", pos: "名詞", kana: "アライアンス", ja: "同盟", ex: "The military alliance held joint drills.", exJa: "その軍事同盟は合同演習を行った。" },
  { en: "tension", pos: "名詞", kana: "テンション", ja: "緊張", ex: "Tensions rose between the two countries.", exJa: "両国間の緊張が高まった。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "The region faces a humanitarian crisis.", exJa: "その地域は人道危機に直面している。" },
  { en: "refugee", pos: "名詞", kana: "レフュジー", ja: "難民", ex: "Millions of refugees fled the war.", exJa: "何百万もの難民が戦争から逃れた。" },
  { en: "casualty", pos: "名詞", kana: "キャジュアルティ", ja: "死傷者", ex: "The number of casualties keeps rising.", exJa: "死傷者の数は増え続けている。" },
  { en: "sanction", pos: "名詞・動詞", kana: "サンクション", ja: "制裁／制裁を科す", ex: "The government imposed new sanctions on the regime.", exJa: "政府はその政権に新たな制裁を科した。" },
  { en: "regime", pos: "名詞", kana: "レジーム", ja: "政権・体制", ex: "The regime was accused of human rights abuses.", exJa: "その政権は人権侵害で非難された。" },
  { en: "border", pos: "名詞", kana: "ボーダー", ja: "国境・境界", ex: "Soldiers guarded the border day and night.", exJa: "兵士たちは昼夜国境を守った。" },
  { en: "missile", pos: "名詞", kana: "ミサイル", ja: "ミサイル", ex: "The country tested a long-range missile.", exJa: "その国は長距離ミサイルを試射した。" },
  { en: "nuclear", pos: "形容詞", kana: "ニュークリア", ja: "核の・原子力の", ex: "Talks focused on nuclear weapons.", exJa: "協議は核兵器に焦点を当てた。" },
  { en: "destroy", pos: "動詞", kana: "ディストロイ", ja: "破壊する", ex: "The bombs destroyed several buildings.", exJa: "爆弾がいくつかの建物を破壊した。" },
  { en: "evacuate", pos: "動詞", kana: "イヴァキュエイト", ja: "避難させる・避難する", ex: "Families were told to evacuate the area.", exJa: "家族たちはその地域から避難するよう告げられた。" },
  { en: "withdraw", pos: "動詞", kana: "ウィズドロー", ja: "撤退する・引き出す", ex: "The army agreed to withdraw its troops.", exJa: "軍は部隊を撤退させることに同意した。" },
  { en: "hostage", pos: "名詞", kana: "ホステッジ", ja: "人質", ex: "The group released several hostages.", exJa: "その集団は数人の人質を解放した。" },
  { en: "violence", pos: "名詞", kana: "ヴァイオレンス", ja: "暴力", ex: "The protest turned into violence.", exJa: "その抗議は暴力に発展した。" },

  // ---------- 政治・経済・社会ニュース ----------
  { en: "government", pos: "名詞", kana: "ガヴァメント", ja: "政府", ex: "The government announced a new policy.", exJa: "政府は新しい政策を発表した。" },
  { en: "policy", pos: "名詞", kana: "ポリシー", ja: "政策・方針", ex: "The new policy aims to reduce poverty.", exJa: "その新政策は貧困削減を目指している。" },
  { en: "president", pos: "名詞", kana: "プレジデント", ja: "大統領・社長", ex: "The president gave a speech on TV.", exJa: "大統領はテレビで演説した。" },
  { en: "election", pos: "名詞", kana: "イレクション", ja: "選挙", ex: "The election will be held next month.", exJa: "選挙は来月行われる。" },
  { en: "economy", pos: "名詞", kana: "イコノミー", ja: "経済", ex: "The economy grew faster than expected.", exJa: "経済は予想より速く成長した。" },
  { en: "economic", pos: "形容詞", kana: "イコノミック", ja: "経済の", ex: "Economic growth slowed down this year.", exJa: "今年は経済成長が鈍化した。" },
  { en: "inflation", pos: "名詞", kana: "インフレイション", ja: "インフレ・物価上昇", ex: "High inflation hurts ordinary families.", exJa: "高いインフレは一般家庭を苦しめる。" },
  { en: "recession", pos: "名詞", kana: "リセッション", ja: "景気後退", ex: "Experts fear a global recession.", exJa: "専門家は世界的な景気後退を懸念している。" },
  { en: "market", pos: "名詞", kana: "マーケット", ja: "市場", ex: "The stock market fell sharply.", exJa: "株式市場は急落した。" },
  { en: "trade", pos: "名詞・動詞", kana: "トレイド", ja: "貿易・取引／取引する", ex: "The two countries signed a trade deal.", exJa: "両国は貿易協定に署名した。" },
  { en: "industry", pos: "名詞", kana: "インダストリー", ja: "産業・業界", ex: "The tech industry is growing rapidly.", exJa: "テック産業は急速に成長している。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "The energy crisis raised fuel prices.", exJa: "エネルギー危機は燃料価格を引き上げた。" },
  { en: "protest", pos: "名詞・動詞", kana: "プロテスト", ja: "抗議／抗議する", ex: "Thousands joined the protest downtown.", exJa: "何千人もが繁華街の抗議に加わった。" },
  { en: "election", pos: "名詞", kana: "イレクション", ja: "選挙", ex: "Voters lined up early for the election.", exJa: "有権者は選挙のため早くから並んだ。" },
  { en: "official", pos: "名詞・形容詞", kana: "オフィシャル", ja: "当局者／公式の", ex: "A government official confirmed the news.", exJa: "政府当局者がそのニュースを認めた。" },
  { en: "announce", pos: "動詞", kana: "アナウンス", ja: "発表する", ex: "The company announced record profits.", exJa: "その会社は過去最高の利益を発表した。" },
  { en: "claim", pos: "動詞・名詞", kana: "クレイム", ja: "主張する／主張", ex: "Both sides claim they won the battle.", exJa: "双方がその戦いに勝ったと主張している。" },
  { en: "accuse", pos: "動詞", kana: "アキューズ", ja: "非難する・告発する", ex: "Critics accuse the company of fraud.", exJa: "批判する人々はその会社を詐欺だと非難する。" },
  { en: "investigate", pos: "動詞", kana: "インヴェスティゲイト", ja: "調査する", ex: "Police are investigating the incident.", exJa: "警察はその事件を調査している。" },
  { en: "incident", pos: "名詞", kana: "インシデント", ja: "出来事・事件", ex: "The incident raised safety concerns.", exJa: "その事件は安全上の懸念を高めた。" },
  { en: "authority", pos: "名詞", kana: "オーソリティ", ja: "当局・権限", ex: "Local authorities warned residents to stay home.", exJa: "地元当局は住民に在宅を呼びかけた。" },
  { en: "concern", pos: "名詞・動詞", kana: "コンサーン", ja: "懸念／心配させる", ex: "There is growing concern about the economy.", exJa: "経済に対する懸念が高まっている。" },
  { en: "demand", pos: "名詞・動詞", kana: "ディマンド", ja: "要求・需要／要求する", ex: "Protesters demand higher wages.", exJa: "抗議者たちはより高い賃金を要求している。" },
  { en: "supply", pos: "名詞・動詞", kana: "サプライ", ja: "供給／供給する", ex: "The war disrupted the food supply.", exJa: "戦争は食料供給を混乱させた。" },
  { en: "agreement", pos: "名詞", kana: "アグリーメント", ja: "合意・協定", ex: "They finally reached an agreement.", exJa: "彼らはついに合意に達した。" },
  { en: "support", pos: "名詞・動詞", kana: "サポート", ja: "支援／支援する", ex: "Many countries offered support to the victims.", exJa: "多くの国が被災者に支援を申し出た。" },
  { en: "victim", pos: "名詞", kana: "ヴィクティム", ja: "被害者・犠牲者", ex: "Aid was sent to the victims of the disaster.", exJa: "支援が災害の被災者に送られた。" },
  { en: "humanitarian", pos: "形容詞", kana: "ヒューマニテリアン", ja: "人道的な", ex: "The UN called for humanitarian aid.", exJa: "国連は人道支援を呼びかけた。" },
  { en: "global", pos: "形容詞", kana: "グローバル", ja: "世界的な", ex: "Climate change is a global problem.", exJa: "気候変動は世界的な問題だ。" },
  { en: "crisis", pos: "名詞", kana: "クライシス", ja: "危機", ex: "World leaders met to discuss the crisis.", exJa: "世界の指導者たちが危機を議論するため集まった。" },

  // ---------- 報道・議論でよく使う動詞・形容詞 ----------
  { en: "increase", pos: "動詞・名詞", kana: "インクリース", ja: "増える・増やす／増加", ex: "Fuel prices increased last month.", exJa: "燃料価格は先月上昇した。" },
  { en: "decrease", pos: "動詞・名詞", kana: "ディクリース", ja: "減る・減らす／減少", ex: "Unemployment decreased this year.", exJa: "失業率は今年低下した。" },
  { en: "reduce", pos: "動詞", kana: "リデュース", ja: "減らす", ex: "The plan aims to reduce carbon emissions.", exJa: "その計画は炭素排出を減らすことを目指す。" },
  { en: "release", pos: "動詞・名詞", kana: "リリース", ja: "公開する・解放する／発表", ex: "The company released a new product.", exJa: "その会社は新製品を発表した。" },
  { en: "report", pos: "名詞・動詞", kana: "リポート", ja: "報告／報道する", ex: "The report warned about rising prices.", exJa: "その報告は物価上昇について警告した。" },
  { en: "warn", pos: "動詞", kana: "ウォーン", ja: "警告する", ex: "Experts warn of more flooding.", exJa: "専門家はさらなる洪水を警告している。" },
  { en: "estimate", pos: "動詞・名詞", kana: "エスティメイト", ja: "見積もる／見積もり", ex: "Officials estimate the damage at billions.", exJa: "当局は被害を数十億と見積もっている。" },
  { en: "reveal", pos: "動詞", kana: "リヴィール", ja: "明らかにする", ex: "The study revealed surprising results.", exJa: "その研究は驚くべき結果を明らかにした。" },
  { en: "expand", pos: "動詞", kana: "イクスパンド", ja: "拡大する", ex: "The company plans to expand into Asia.", exJa: "その会社はアジアへの進出を計画している。" },
  { en: "significant", pos: "形容詞", kana: "シグニフィカント", ja: "重要な・著しい", ex: "There was a significant rise in sales.", exJa: "売上に著しい増加があった。" },
  { en: "potential", pos: "名詞・形容詞", kana: "ポテンシャル", ja: "可能性／潜在的な", ex: "AI has huge potential in healthcare.", exJa: "AIは医療に大きな可能性を持つ。" },
  { en: "current", pos: "形容詞", kana: "カレント", ja: "現在の", ex: "The current situation is very serious.", exJa: "現在の状況は非常に深刻だ。" },
  { en: "recent", pos: "形容詞", kana: "リーセント", ja: "最近の", ex: "A recent survey shows rising prices.", exJa: "最近の調査は物価上昇を示している。" },
  { en: "major", pos: "形容詞", kana: "メイジャー", ja: "主要な・大きな", ex: "The storm caused major damage.", exJa: "その嵐は大きな被害を引き起こした。" },
  { en: "severe", pos: "形容詞", kana: "シヴィア", ja: "深刻な・厳しい", ex: "The region suffered a severe drought.", exJa: "その地域は深刻な干ばつに見舞われた。" },
  { en: "spread", pos: "動詞・名詞", kana: "スプレッド", ja: "広がる・広げる／広がり", ex: "Fake news spreads quickly online.", exJa: "フェイクニュースはネット上で素早く広がる。" },
  { en: "affect", pos: "動詞", kana: "アフェクト", ja: "影響を与える", ex: "The drought affected millions of people.", exJa: "その干ばつは何百万もの人々に影響を与えた。" },
  { en: "cause", pos: "動詞・名詞", kana: "コーズ", ja: "引き起こす／原因", ex: "The fire caused serious damage.", exJa: "その火事は深刻な被害を引き起こした。" },
  { en: "prevent", pos: "動詞", kana: "プリヴェント", ja: "防ぐ", ex: "New rules aim to prevent accidents.", exJa: "新しい規則は事故を防ぐことを目指す。" },
  { en: "respond", pos: "動詞", kana: "リスポンド", ja: "対応する・反応する", ex: "The government responded to the crisis quickly.", exJa: "政府はその危機に素早く対応した。" },
  { en: "establish", pos: "動詞", kana: "イスタブリッシュ", ja: "設立する・確立する", ex: "They established a new committee.", exJa: "彼らは新しい委員会を設立した。" },
  { en: "achieve", pos: "動詞", kana: "アチーヴ", ja: "達成する", ex: "The team achieved its main goal.", exJa: "そのチームは主な目標を達成した。" },
  { en: "consider", pos: "動詞", kana: "コンシダー", ja: "検討する・考慮する", ex: "Leaders are considering new measures.", exJa: "指導者たちは新たな対策を検討している。" },
  { en: "measure", pos: "名詞・動詞", kana: "メジャー", ja: "対策・手段／測る", ex: "The government took emergency measures.", exJa: "政府は緊急措置をとった。" },
  { en: "policy", pos: "名詞", kana: "ポリシー", ja: "政策・方針", ex: "The bank changed its interest rate policy.", exJa: "その銀行は金利政策を変更した。" },
  { en: "issue", pos: "名詞・動詞", kana: "イシュー", ja: "問題・争点／発行する", ex: "Climate change is a serious issue.", exJa: "気候変動は深刻な問題だ。" },
  { en: "solution", pos: "名詞", kana: "ソルーション", ja: "解決策", ex: "There is no easy solution to the problem.", exJa: "その問題に簡単な解決策はない。" },
  { en: "benefit", pos: "名詞・動詞", kana: "ベネフィット", ja: "利益・恩恵／利益を得る", ex: "New technology benefits many people.", exJa: "新しい技術は多くの人に恩恵を与える。" },
  { en: "risk", pos: "名詞・動詞", kana: "リスク", ja: "危険・リスク／危険にさらす", ex: "There is a high risk of conflict.", exJa: "紛争の高い危険がある。" },
  { en: "ban", pos: "動詞・名詞", kana: "バン", ja: "禁止する／禁止", ex: "The country banned the use of the app.", exJa: "その国はそのアプリの使用を禁止した。" },

  // ============================================================
  // 上級寄り（ニュース・AI・戦争で頻出する歯ごたえのある語）
  // ============================================================

  // ---------- AI・テクノロジー（上級） ----------
  { en: "surveillance", pos: "名詞", kana: "サヴェイランス", ja: "監視", ex: "Critics warn that AI enables mass surveillance.", exJa: "批判する人々は、AIが大規模な監視を可能にすると警告している。" },
  { en: "autonomous", pos: "形容詞", kana: "オートノマス", ja: "自律した・自動運転の", ex: "Autonomous vehicles are being tested on public roads.", exJa: "自動運転車が公道で試験されている。" },
  { en: "algorithmic", pos: "形容詞", kana: "アルゴリズミック", ja: "アルゴリズムの", ex: "Researchers found algorithmic bias in the hiring tool.", exJa: "研究者はその採用ツールにアルゴリズムの偏りを見つけた。" },
  { en: "bias", pos: "名詞・動詞", kana: "バイアス", ja: "偏り・先入観／偏らせる", ex: "The model showed a clear bias against some groups.", exJa: "そのモデルは一部の集団に対する明らかな偏りを示した。" },
  { en: "deploy", pos: "動詞", kana: "ディプロイ", ja: "展開する・配備する・運用開始する", ex: "The company deployed the new AI system worldwide.", exJa: "その会社は新しいAIシステムを世界中で運用開始した。" },
  { en: "scalable", pos: "形容詞", kana: "スケーラブル", ja: "拡張可能な", ex: "The platform is scalable to millions of users.", exJa: "そのプラットフォームは数百万人規模に拡張できる。" },
  { en: "infrastructure", pos: "名詞", kana: "インフラストラクチャー", ja: "基盤・インフラ", ex: "Training large models requires huge computing infrastructure.", exJa: "大規模モデルの学習には巨大な計算インフラが必要だ。" },
  { en: "breakthrough", pos: "名詞", kana: "ブレイクスルー", ja: "大きな進展・突破口", ex: "The discovery was hailed as a major breakthrough.", exJa: "その発見は大きな突破口として称賛された。" },
  { en: "disrupt", pos: "動詞", kana: "ディスラプト", ja: "混乱させる・大きく変える", ex: "Generative AI could disrupt the entire industry.", exJa: "生成AIは業界全体を一変させる可能性がある。" },
  { en: "ethical", pos: "形容詞", kana: "エシカル", ja: "倫理的な", ex: "There are ethical concerns about facial recognition.", exJa: "顔認識には倫理的な懸念がある。" },
  { en: "transparency", pos: "名詞", kana: "トランスパレンシー", ja: "透明性", ex: "Users demand more transparency from tech firms.", exJa: "ユーザーはテック企業にさらなる透明性を求めている。" },
  { en: "accountability", pos: "名詞", kana: "アカウンタビリティ", ja: "説明責任", ex: "Lawmakers called for greater accountability in AI use.", exJa: "議員たちはAI利用におけるより大きな説明責任を求めた。" },
  { en: "exploit", pos: "動詞・名詞", kana: "エクスプロイト", ja: "悪用する・活用する／脆弱性", ex: "Hackers exploited a flaw in the software.", exJa: "ハッカーはそのソフトの欠陥を悪用した。" },
  { en: "vulnerability", pos: "名詞", kana: "ヴァルネラビリティ", ja: "脆弱性・弱点", ex: "The report revealed a serious security vulnerability.", exJa: "その報告は深刻なセキュリティ上の脆弱性を明らかにした。" },
  { en: "misinformation", pos: "名詞", kana: "ミスインフォメイション", ja: "誤情報", ex: "AI can spread misinformation at scale.", exJa: "AIは誤情報を大規模に拡散しうる。" },
  { en: "unprecedented", pos: "形容詞", kana: "アンプレシデンテッド", ja: "前例のない", ex: "The technology is advancing at an unprecedented pace.", exJa: "その技術は前例のない速さで進歩している。" },

  // ---------- 戦争・安全保障（上級） ----------
  { en: "escalate", pos: "動詞", kana: "エスカレイト", ja: "激化する・拡大させる", ex: "Fears grow that the conflict could escalate further.", exJa: "紛争がさらに激化しうるという懸念が高まっている。" },
  { en: "escalation", pos: "名詞", kana: "エスカレイション", ja: "激化・段階的拡大", ex: "Diplomats are working to prevent further escalation.", exJa: "外交官たちはさらなる激化を防ごうとしている。" },
  { en: "deterrence", pos: "名詞", kana: "ディターレンス", ja: "抑止（力）", ex: "Nuclear deterrence shaped the Cold War.", exJa: "核抑止は冷戦を形づくった。" },
  { en: "sovereignty", pos: "名詞", kana: "ソヴリンティ", ja: "主権", ex: "The invasion violated the country's sovereignty.", exJa: "その侵攻はその国の主権を侵害した。" },
  { en: "annex", pos: "動詞", kana: "アネックス", ja: "併合する", ex: "The state tried to annex the disputed region.", exJa: "その国家は係争地域を併合しようとした。" },
  { en: "insurgency", pos: "名詞", kana: "インサージェンシー", ja: "反乱・武装蜂起", ex: "The army struggled to contain the insurgency.", exJa: "軍はその反乱を抑え込むのに苦労した。" },
  { en: "militant", pos: "名詞・形容詞", kana: "ミリタント", ja: "武装勢力・過激派／好戦的な", ex: "Militants attacked a military base overnight.", exJa: "武装勢力が夜間に軍事基地を攻撃した。" },
  { en: "atrocity", pos: "名詞", kana: "アトロシティ", ja: "残虐行為", ex: "Investigators documented atrocities against civilians.", exJa: "調査官は民間人に対する残虐行為を記録した。" },
  { en: "retaliate", pos: "動詞", kana: "リタリエイト", ja: "報復する", ex: "The government vowed to retaliate against the strike.", exJa: "政府はその攻撃に報復すると誓った。" },
  { en: "retaliation", pos: "名詞", kana: "リタリエイション", ja: "報復", ex: "The attack was launched in retaliation.", exJa: "その攻撃は報復として行われた。" },
  { en: "offensive", pos: "名詞・形容詞", kana: "オフェンシブ", ja: "攻勢／攻撃的な", ex: "The army launched a major ground offensive.", exJa: "軍は大規模な地上攻勢を開始した。" },
  { en: "siege", pos: "名詞", kana: "シージ", ja: "包囲", ex: "The city has been under siege for weeks.", exJa: "その都市は数週間にわたり包囲されている。" },
  { en: "deploy", pos: "動詞", kana: "ディプロイ", ja: "配備する・展開する", ex: "More troops were deployed to the front line.", exJa: "より多くの部隊が前線に配備された。" },
  { en: "proliferation", pos: "名詞", kana: "プロリファレイション", ja: "拡散・急増", ex: "The treaty aims to stop nuclear proliferation.", exJa: "その条約は核拡散を止めることを目指している。" },
  { en: "displaced", pos: "形容詞", kana: "ディスプレイスト", ja: "(住む場所を)追われた", ex: "Millions of people have been displaced by the war.", exJa: "何百万もの人々が戦争で住む場所を追われた。" },
  { en: "diplomacy", pos: "名詞", kana: "ディプロマシー", ja: "外交", ex: "They hope diplomacy can end the crisis.", exJa: "彼らは外交がその危機を終わらせられると期待している。" },
  { en: "intervention", pos: "名詞", kana: "インターヴェンション", ja: "介入", ex: "Critics oppose military intervention abroad.", exJa: "批判する人々は海外への軍事介入に反対している。" },
  { en: "condemn", pos: "動詞", kana: "コンデム", ja: "非難する", ex: "World leaders condemned the attack.", exJa: "世界の指導者たちはその攻撃を非難した。" },

  // ---------- 政治・経済・社会（上級） ----------
  { en: "allegation", pos: "名詞", kana: "アリゲイション", ja: "(証拠のない)主張・申し立て", ex: "The company denied all the allegations.", exJa: "その会社はすべての申し立てを否定した。" },
  { en: "sanction", pos: "名詞・動詞", kana: "サンクション", ja: "制裁／認可する", ex: "Western nations tightened sanctions on the regime.", exJa: "西側諸国はその政権への制裁を強化した。" },
  { en: "coalition", pos: "名詞", kana: "コアリション", ja: "連立・連合", ex: "A new coalition government was formed.", exJa: "新しい連立政権が発足した。" },
  { en: "legislation", pos: "名詞", kana: "レジスレイション", ja: "法律・立法", ex: "Parliament passed new legislation on data privacy.", exJa: "議会はデータ保護に関する新法を可決した。" },
  { en: "mandate", pos: "名詞・動詞", kana: "マンデイト", ja: "権限・指令／義務づける", ex: "Voters gave the party a strong mandate.", exJa: "有権者はその政党に強い信任を与えた。" },
  { en: "scrutiny", pos: "名詞", kana: "スクルーティニー", ja: "綿密な調査・精査", ex: "The deal is under intense scrutiny.", exJa: "その取引は厳しい精査を受けている。" },
  { en: "controversial", pos: "形容詞", kana: "コントロヴァーシャル", ja: "物議をかもす", ex: "The decision proved highly controversial.", exJa: "その決定は非常に物議をかもした。" },
  { en: "implement", pos: "動詞", kana: "インプリメント", ja: "実施する", ex: "The government will implement the reforms next year.", exJa: "政府は来年その改革を実施する。" },
  { en: "undermine", pos: "動詞", kana: "アンダーマイン", ja: "弱体化させる・損なう", ex: "Corruption can undermine public trust.", exJa: "汚職は国民の信頼を損ないうる。" },
  { en: "advocate", pos: "動詞・名詞", kana: "アドヴォケイト", ja: "提唱する／支持者", ex: "She advocates for stronger climate policies.", exJa: "彼女はより強力な気候政策を提唱している。" },
  { en: "subsidy", pos: "名詞", kana: "サブシディ", ja: "補助金", ex: "The government cut subsidies for fuel.", exJa: "政府は燃料への補助金を削減した。" },
  { en: "volatile", pos: "形容詞", kana: "ヴォラタイル", ja: "不安定な・変動の激しい", ex: "Oil prices remain highly volatile.", exJa: "原油価格は依然として非常に不安定だ。" },
  { en: "plummet", pos: "動詞", kana: "プラメット", ja: "急落する", ex: "Stock prices plummeted after the news.", exJa: "そのニュースの後、株価は急落した。" },
  { en: "surge", pos: "名詞・動詞", kana: "サージ", ja: "急増／急増する", ex: "There was a surge in energy demand.", exJa: "エネルギー需要に急増があった。" },
  { en: "disparity", pos: "名詞", kana: "ディスパリティ", ja: "格差・不均衡", ex: "The report highlights wide income disparity.", exJa: "その報告は大きな所得格差を浮き彫りにしている。" },
  { en: "resilience", pos: "名詞", kana: "リジリエンス", ja: "回復力・強靱さ", ex: "The economy showed surprising resilience.", exJa: "経済は驚くべき回復力を見せた。" },
  { en: "unanimous", pos: "形容詞", kana: "ユナニマス", ja: "全員一致の", ex: "The council reached a unanimous decision.", exJa: "評議会は全員一致の決定に達した。" },
  { en: "imminent", pos: "形容詞", kana: "イミネント", ja: "差し迫った", ex: "Officials warned of an imminent threat.", exJa: "当局は差し迫った脅威を警告した。" },
  { en: "deteriorate", pos: "動詞", kana: "ディティアリオレイト", ja: "悪化する", ex: "The situation continues to deteriorate.", exJa: "状況は悪化し続けている。" },
  { en: "mitigate", pos: "動詞", kana: "ミティゲイト", ja: "緩和する・軽減する", ex: "New rules aim to mitigate the damage.", exJa: "新しい規則は被害を軽減することを目指している。" }
];
