// 追加200語（日常会話・中級）
const WORDS_EXTRA2 = [
  { en: "greet", pos: "動詞", kana: "グリート", ja: "挨拶する", ex: "She greeted her neighbor with a warm smile.", exJa: "彼女は隣人に温かい笑顔で挨拶した。", cat: "日常会話" },
  { en: "introduce", pos: "動詞", kana: "イントロデュース", ja: "紹介する", ex: "Let me introduce you to my sister.", exJa: "妹を紹介させてください。", cat: "日常会話" },
  { en: "chat", pos: "動詞・名詞", kana: "チャット", ja: "おしゃべりする／雑談", ex: "We had a quick chat before the meeting started.", exJa: "会議が始まる前に少しおしゃべりした。", cat: "日常会話" },
  { en: "small talk", pos: "名詞", kana: "スモールトーク", ja: "世間話", ex: "He is good at making small talk with strangers.", exJa: "彼は初対面の人と世間話をするのが上手だ。", cat: "日常会話" },
  { en: "mention", pos: "動詞", kana: "メンション", ja: "言及する・ちょっと話す", ex: "She mentioned that she might move next year.", exJa: "彼女は来年引っ越すかもしれないと言っていた。", cat: "日常会話" },
  { en: "gossip", pos: "名詞・動詞", kana: "ゴシップ", ja: "うわさ話／うわさ話をする", ex: "They were gossiping about the new coworker.", exJa: "彼らは新しい同僚のうわさ話をしていた。", cat: "日常会話" },
  { en: "rumor", pos: "名詞", kana: "ルーマー", ja: "うわさ", ex: "There's a rumor that the store is closing.", exJa: "その店が閉店するといううわさがある。", cat: "日常会話" },
  { en: "joke", pos: "名詞・動詞", kana: "ジョーク", ja: "冗談／冗談を言う", ex: "He always jokes around during lunch break.", exJa: "彼は昼休みにいつも冗談を言っている。", cat: "日常会話" },
  { en: "tease", pos: "動詞", kana: "ティーズ", ja: "からかう", ex: "Stop teasing your little brother.", exJa: "弟をからかうのはやめなさい。", cat: "日常会話" },
  { en: "compliment", pos: "名詞・動詞", kana: "コンプリメント", ja: "褒め言葉／褒める", ex: "She gave me a nice compliment on my haircut.", exJa: "彼女は私の髪型を素敵だと褒めてくれた。", cat: "日常会話" },
  { en: "flatter", pos: "動詞", kana: "フラター", ja: "お世辞を言う", ex: "He was just flattering the boss to get a raise.", exJa: "彼は昇給のために上司にお世辞を言っていただけだ。", cat: "日常会話" },
  { en: "criticize", pos: "動詞", kana: "クリティサイズ", ja: "批判する", ex: "Try not to criticize him in front of everyone.", exJa: "みんなの前で彼を批判しないようにして。", cat: "日常会話" },
  { en: "complain", pos: "動詞", kana: "コンプレイン", ja: "文句を言う", ex: "Customers complained about the slow service.", exJa: "客たちは遅いサービスに文句を言った。", cat: "日常会話" },
  { en: "apologize", pos: "動詞", kana: "アポロジャイズ", ja: "謝る", ex: "He apologized for being late again.", exJa: "彼はまた遅刻したことを謝った。", cat: "日常会話" },
  { en: "forgive", pos: "動詞", kana: "フォーギブ", ja: "許す", ex: "I forgave her once she explained the mistake.", exJa: "彼女が間違いを説明してくれたので許した。", cat: "日常会話" },
  { en: "excuse", pos: "名詞・動詞", kana: "イクスキューズ", ja: "言い訳／許す", ex: "He made an excuse for missing the appointment.", exJa: "彼は約束をすっぽかしたことに言い訳をした。", cat: "日常会話" },
  { en: "hesitate", pos: "動詞", kana: "ヘズィテイト", ja: "ためらう", ex: "Don't hesitate to ask if you have questions.", exJa: "質問があればためらわずに聞いてください。", cat: "日常会話" },
  { en: "assume", pos: "動詞", kana: "アシューム", ja: "思い込む・仮定する", ex: "I assumed you already knew about the change.", exJa: "あなたはもうその変更を知っていると思い込んでいた。", cat: "日常会話" },
  { en: "admit", pos: "動詞", kana: "アドミット", ja: "認める", ex: "He finally admitted he forgot the meeting.", exJa: "彼はついに会議を忘れたことを認めた。", cat: "日常会話" },
  { en: "respond", pos: "動詞", kana: "リスポンド", ja: "応答する", ex: "She didn't respond to my text until the next day.", exJa: "彼女は翌日まで私のメッセージに応答しなかった。", cat: "日常会話" },
  { en: "reply", pos: "動詞・名詞", kana: "リプライ", ja: "返事する／返事", ex: "He replied to the invitation right away.", exJa: "彼はその招待にすぐに返事をした。", cat: "日常会話" },
  { en: "clarify", pos: "動詞", kana: "クラリファイ", ja: "明確にする", ex: "Let me clarify what I meant earlier.", exJa: "先ほど言った意味をはっきりさせておきます。", cat: "日常会話" },
  { en: "misunderstand", pos: "動詞", kana: "ミスアンダースタンド", ja: "誤解する", ex: "I think you misunderstood my message.", exJa: "あなたは私のメッセージを誤解したと思う。", cat: "日常会話" },
  { en: "explain", pos: "動詞", kana: "イクスプレイン", ja: "説明する", ex: "Could you explain the rules one more time?", exJa: "もう一度ルールを説明してもらえますか。", cat: "日常会話" },
  { en: "describe", pos: "動詞", kana: "ディスクライブ", ja: "描写する・説明する", ex: "Can you describe what the man looked like?", exJa: "その男性がどんな見た目だったか説明してもらえますか。", cat: "日常会話" },
  { en: "discuss", pos: "動詞", kana: "ディスカス", ja: "話し合う", ex: "We discussed our plans for the weekend.", exJa: "週末の予定について話し合った。", cat: "日常会話" },
  { en: "double-check", pos: "動詞", kana: "ダブル・チェック", ja: "再確認する", ex: "Let's double-check the address before we leave.", exJa: "出発する前に住所を再確認しよう。", cat: "日常会話" },
  { en: "compromise", pos: "名詞・動詞", kana: "コンプロマイズ", ja: "妥協／妥協する", ex: "We reached a compromise after a long talk.", exJa: "長い話し合いの末、妥協点に至った。", cat: "日常会話" },
  { en: "convince", pos: "動詞", kana: "コンヴィンス", ja: "納得させる", ex: "It took a while to convince him to come.", exJa: "彼を来させるよう納得させるのに時間がかかった。", cat: "日常会話" },
  { en: "persuade", pos: "動詞", kana: "パースエイド", ja: "説得する", ex: "She persuaded her parents to let her travel alone.", exJa: "彼女は一人旅を許してもらえるよう両親を説得した。", cat: "日常会話" },
  { en: "insist", pos: "動詞", kana: "インシスト", ja: "言い張る", ex: "He insisted on paying for dinner.", exJa: "彼は夕食代を自分が払うと言い張った。", cat: "日常会話" },
  { en: "agree", pos: "動詞", kana: "アグリー", ja: "同意する", ex: "We all agreed to meet at six.", exJa: "私たちは全員6時に会うことで同意した。", cat: "日常会話" },
  { en: "disagree", pos: "動詞", kana: "ディスアグリー", ja: "反対する", ex: "I disagree with your opinion on this.", exJa: "この件に関するあなたの意見には反対だ。", cat: "日常会話" },
  { en: "argue", pos: "動詞", kana: "アーギュー", ja: "口論する・主張する", ex: "They argued about whose turn it was to cook.", exJa: "彼らは誰が料理をする番かで口論した。", cat: "日常会話" },
  { en: "opinion", pos: "名詞", kana: "オピニオン", ja: "意見", ex: "What's your opinion on the new schedule?", exJa: "新しいスケジュールについてどう思いますか。", cat: "日常会話" },
  { en: "suggest", pos: "動詞", kana: "サジェスト", ja: "提案する", ex: "I suggest we leave a bit earlier.", exJa: "もう少し早く出発することを提案します。", cat: "日常会話" },
  { en: "recommend", pos: "動詞", kana: "レコメンド", ja: "勧める", ex: "My friend recommended this restaurant to me.", exJa: "友人がこのレストランを勧めてくれた。", cat: "日常会話" },
  { en: "prefer", pos: "動詞", kana: "プリファー", ja: "むしろ好む", ex: "I prefer tea to coffee in the morning.", exJa: "朝はコーヒーよりお茶の方が好きだ。", cat: "日常会話" },
  { en: "decide", pos: "動詞", kana: "ディサイド", ja: "決める", ex: "We haven't decided where to go yet.", exJa: "どこに行くかまだ決めていない。", cat: "日常会話" },
  { en: "point of view", pos: "名詞", kana: "ポイント・オブ・ビュー", ja: "見方・視点", ex: "Try to see it from her point of view.", exJa: "彼女の視点からそれを見るようにしてみて。", cat: "日常会話" },
  { en: "arrange", pos: "動詞", kana: "アレンジ", ja: "手配する", ex: "I'll arrange a table for four at seven.", exJa: "7時に4人分のテーブルを手配しておきます。", cat: "日常会話" },
  { en: "invite", pos: "動詞", kana: "インヴァイト", ja: "招待する", ex: "We invited a few close friends to the party.", exJa: "親しい友人を数人パーティーに招待した。", cat: "日常会話" },
  { en: "decline", pos: "動詞", kana: "ディクライン", ja: "断る", ex: "She politely declined the invitation.", exJa: "彼女はその招待を丁寧に断った。", cat: "日常会話" },
  { en: "accept", pos: "動詞", kana: "アクセプト", ja: "受け入れる", ex: "He gladly accepted our offer to help.", exJa: "彼は手伝うという申し出を喜んで受け入れた。", cat: "日常会話" },
  { en: "refuse", pos: "動詞", kana: "リフューズ", ja: "拒否する", ex: "She refused to sign the agreement.", exJa: "彼女はその合意書への署名を拒否した。", cat: "日常会話" },
  { en: "cancel", pos: "動詞", kana: "キャンセル", ja: "取り消す", ex: "We had to cancel the trip because of the storm.", exJa: "嵐のせいで旅行を取り消さなければならなかった。", cat: "日常会話" },
  { en: "follow up", pos: "動詞句", kana: "フォロー・アップ", ja: "後で確認する・フォローアップする", ex: "I'll follow up with an email tomorrow.", exJa: "明日メールでフォローアップします。", cat: "日常会話" },
  { en: "reschedule", pos: "動詞", kana: "リスケジュール", ja: "予定を変更する", ex: "Can we reschedule our call to Friday?", exJa: "電話の予定を金曜日に変更できますか。", cat: "日常会話" },
  { en: "availability", pos: "名詞", kana: "アヴェイラビリティ", ja: "都合・空き状況", ex: "Let me check my availability this week.", exJa: "今週の私の都合を確認させてください。", cat: "日常会話" },
  { en: "day off", pos: "名詞", kana: "デイ・オフ", ja: "休みの日", ex: "I'm taking a day off to relax next Friday.", exJa: "来週の金曜日はゆっくりするために休みを取る。", cat: "日常会話" },
  { en: "errand", pos: "名詞", kana: "エランド", ja: "用事・使い", ex: "I need to run a few errands after work.", exJa: "仕事の後にいくつか用事を済ませる必要がある。", cat: "日常会話" },
  { en: "favor", pos: "名詞", kana: "フェイヴァー", ja: "頼み事", ex: "Can I ask you a small favor?", exJa: "ちょっとしたお願いをしてもいいですか。", cat: "日常会話" },
  { en: "borrow", pos: "動詞", kana: "ボロウ", ja: "借りる", ex: "Could I borrow your umbrella for today?", exJa: "今日、あなたの傘を借りてもいいですか。", cat: "日常会話" },
  { en: "lend", pos: "動詞", kana: "レンド", ja: "貸す", ex: "He lent me his bike for the weekend.", exJa: "彼は週末の間、自転車を貸してくれた。", cat: "日常会話" },
  { en: "remind", pos: "動詞", kana: "リマインド", ja: "思い出させる", ex: "Please remind me to call her later.", exJa: "後で彼女に電話することを思い出させてください。", cat: "日常会話" },
  { en: "forget", pos: "動詞", kana: "フォーゲット", ja: "忘れる", ex: "I always forget where I put my keys.", exJa: "私はいつも鍵をどこに置いたか忘れてしまう。", cat: "日常会話" },
  { en: "notice", pos: "動詞・名詞", kana: "ノーティス", ja: "気づく／通知", ex: "I noticed you looked tired this morning.", exJa: "今朝、あなたが疲れているように見えることに気づいた。", cat: "日常会話" },
  { en: "realize", pos: "動詞", kana: "リアライズ", ja: "気づく・悟る", ex: "She realized she had left her phone at home.", exJa: "彼女は携帯電話を家に忘れたことに気づいた。", cat: "日常会話" },
  { en: "wonder", pos: "動詞", kana: "ワンダー", ja: "疑問に思う", ex: "I wonder if he'll show up on time.", exJa: "彼が時間通りに来るかどうか気になる。", cat: "日常会話" },
  { en: "routine", pos: "名詞", kana: "ルーティーン", ja: "日課", ex: "Walking the dog is part of my morning routine.", exJa: "犬の散歩は私の朝の日課の一部だ。", cat: "日常会話" },
  { en: "habit", pos: "名詞", kana: "ハビット", ja: "習慣", ex: "Checking my phone first thing is a bad habit.", exJa: "起きてすぐ携帯を見るのは悪い習慣だ。", cat: "日常会話" },
  { en: "chore", pos: "名詞", kana: "チョア", ja: "家事", ex: "Doing the dishes is my least favorite chore.", exJa: "皿洗いは私が一番苦手な家事だ。", cat: "日常会話" },
  { en: "run behind", pos: "動詞句", kana: "ラン・ビハインド", ja: "予定より遅れる", ex: "We're running behind, so let's skip the coffee break.", exJa: "予定より遅れているので、コーヒー休憩は抜きにしよう。", cat: "日常会話" },
  { en: "drop a line", pos: "動詞句", kana: "ドロップ・ア・ライン", ja: "一言連絡する", ex: "Drop me a line when you land safely.", exJa: "無事に着いたら一言連絡してね。", cat: "日常会話" },
  { en: "plan", pos: "名詞・動詞", kana: "プラン", ja: "計画／計画する", ex: "Do you have any plans for the holiday?", exJa: "休みの予定は何かありますか。", cat: "日常会話" },
  { en: "relieved", pos: "形容詞", kana: "リリーヴド", ja: "ほっとした", ex: "I was relieved to hear the test results were fine.", exJa: "検査結果が良かったと聞いてほっとした。", cat: "日常会話" },
  { en: "disappointed", pos: "形容詞", kana: "ディサポインティッド", ja: "がっかりした", ex: "He looked disappointed when the trip was canceled.", exJa: "旅行が中止になって彼はがっかりしているようだった。", cat: "日常会話" },
  { en: "frustrated", pos: "形容詞", kana: "フラストレイティッド", ja: "苛立った", ex: "She got frustrated with the slow internet connection.", exJa: "彼女は遅いインターネット接続に苛立った。", cat: "日常会話" },
  { en: "embarrassed", pos: "形容詞", kana: "エンバラスト", ja: "恥ずかしい", ex: "I felt embarrassed when I forgot his name.", exJa: "彼の名前を忘れて恥ずかしかった。", cat: "日常会話" },
  { en: "nervous", pos: "形容詞", kana: "ナーヴァス", ja: "緊張した", ex: "She was nervous before her job interview.", exJa: "彼女は就職の面接前に緊張していた。", cat: "日常会話" },
  { en: "curious", pos: "形容詞", kana: "キュリアス", ja: "好奇心のある", ex: "The kids were curious about the new neighbor.", exJa: "子供たちは新しい隣人に興味津々だった。", cat: "日常会話" },
  { en: "jealous", pos: "形容詞", kana: "ジェラス", ja: "嫉妬した", ex: "He felt a little jealous of his friend's new car.", exJa: "彼は友人の新しい車に少し嫉妬した。", cat: "日常会話" },
  { en: "grateful", pos: "形容詞", kana: "グレイトフル", ja: "感謝している", ex: "I'm really grateful for your help today.", exJa: "今日は手伝ってくれて本当に感謝しています。", cat: "日常会話" },
  { en: "proud", pos: "形容詞", kana: "プラウド", ja: "誇りに思う", ex: "Her parents were proud of her graduation.", exJa: "彼女の両親は卒業を誇りに思っていた。", cat: "日常会話" },
  { en: "bored", pos: "形容詞", kana: "ボアード", ja: "退屈した", ex: "The children got bored during the long drive.", exJa: "子供たちは長いドライブの間に退屈した。", cat: "日常会話" },
  { en: "annoyed", pos: "形容詞", kana: "アノイド", ja: "苛立った・迷惑した", ex: "He was annoyed by the constant noise next door.", exJa: "彼は隣の絶え間ない騒音に苛立っていた。", cat: "日常会話" },
  { en: "relaxed", pos: "形容詞", kana: "リラックスト", ja: "リラックスした", ex: "I feel more relaxed after a hot bath.", exJa: "熱いお風呂に入るとリラックスできる。", cat: "日常会話" },
  { en: "confident", pos: "形容詞", kana: "コンフィデント", ja: "自信のある", ex: "She sounded confident during the presentation.", exJa: "彼女はプレゼンの間、自信ありげだった。", cat: "日常会話" },
  { en: "interrupt", pos: "動詞", kana: "インタラプト", ja: "遮る", ex: "Sorry to interrupt, but the phone is ringing.", exJa: "話を遮ってすみませんが、電話が鳴っています。", cat: "日常会話" },
  { en: "whisper", pos: "動詞・名詞", kana: "ウィスパー", ja: "ささやく／ささやき", ex: "She whispered the secret into my ear.", exJa: "彼女はその秘密を私の耳元でささやいた。", cat: "日常会話" },
  { en: "mumble", pos: "動詞", kana: "マンブル", ja: "口ごもる", ex: "He mumbled an answer and looked away.", exJa: "彼はもごもごと答えて視線をそらした。", cat: "日常会話" },
  { en: "shout", pos: "動詞・名詞", kana: "シャウト", ja: "叫ぶ／叫び声", ex: "He had to shout over the loud music.", exJa: "彼はうるさい音楽の中で叫ばなければならなかった。", cat: "日常会話" },
  { en: "exaggerate", pos: "動詞", kana: "イグザジェレイト", ja: "誇張する", ex: "I think he exaggerated how hard the exam was.", exJa: "彼はその試験がどれほど難しかったか誇張したと思う。", cat: "日常会話" },
  { en: "honest", pos: "形容詞", kana: "オネスト", ja: "正直な", ex: "To be honest, I don't really like the plan.", exJa: "正直に言うと、その計画はあまり好きではない。", cat: "日常会話" },
  { en: "sincere", pos: "形容詞", kana: "シンシア", ja: "誠実な", ex: "He gave a sincere apology to his coworker.", exJa: "彼は同僚に誠実な謝罪をした。", cat: "日常会話" },
  { en: "polite", pos: "形容詞", kana: "ポライト", ja: "礼儀正しい", ex: "The waiter was very polite to every guest.", exJa: "そのウェイターはどの客にもとても礼儀正しかった。", cat: "日常会話" },
  { en: "rude", pos: "形容詞", kana: "ルード", ja: "失礼な", ex: "It was rude of him to leave without saying goodbye.", exJa: "さよならも言わずに帰るなんて彼は失礼だった。", cat: "日常会話" },
  { en: "trust", pos: "名詞・動詞", kana: "トラスト", ja: "信頼／信頼する", ex: "It took years to build trust between them.", exJa: "二人の間に信頼を築くのに何年もかかった。", cat: "日常会話" },
  { en: "secret", pos: "名詞", kana: "シークレット", ja: "秘密", ex: "She promised to keep the secret to herself.", exJa: "彼女はその秘密を自分だけにとどめると約束した。", cat: "日常会話" },
  { en: "bargain", pos: "名詞・動詞", kana: "バーゲン", ja: "掘り出し物／値切る", ex: "He tried to bargain for a lower price at the market.", exJa: "彼は市場でもっと安くしてもらおうと値切ろうとした。", cat: "日常会話" },
  { en: "missed call", pos: "名詞", kana: "ミスト・コール", ja: "着信履歴", ex: "I noticed a missed call from my mother.", exJa: "母からの着信履歴に気づいた。", cat: "日常会話" },
  { en: "keep someone waiting", pos: "動詞句", kana: "キープ・サムワン・ウェイティング", ja: "人を待たせる", ex: "Sorry to keep you waiting so long.", exJa: "長い間待たせてしまってすみません。", cat: "日常会話" },
  { en: "pick up the phone", pos: "動詞句", kana: "ピック・アップ・ザ・フォン", ja: "電話に出る", ex: "He didn't pick up the phone, so I left a voicemail.", exJa: "彼は電話に出なかったので、留守番電話にメッセージを残した。", cat: "日常会話" },
  { en: "afford", pos: "動詞", kana: "アフォード", ja: "余裕がある", ex: "We can't really afford a big vacation this year.", exJa: "今年は大きな休暇をとる余裕は本当にない。", cat: "日常会話" },
  { en: "voicemail", pos: "名詞", kana: "ヴォイスメイル", ja: "留守番電話", ex: "She left a long voicemail explaining the delay.", exJa: "彼女は遅れの理由を説明する長い留守番電話を残した。", cat: "日常会話" },
  { en: "humid", pos: "形容詞", kana: "ヒューミッド", ja: "蒸し暑い", ex: "It gets really humid here in the summer.", exJa: "ここは夏になるととても蒸し暑くなる。", cat: "日常会話" },
  { en: "chilly", pos: "形容詞", kana: "チリー", ja: "肌寒い", ex: "It's a bit chilly tonight, so bring a jacket.", exJa: "今夜は少し肌寒いので上着を持っていって。", cat: "日常会話" },
  { en: "text message", pos: "名詞", kana: "テキスト・メッセージ", ja: "テキストメッセージ", ex: "He sent a quick text message to confirm the plan.", exJa: "彼は予定を確認するために手短なテキストメッセージを送った。", cat: "日常会話" },
  { en: "drizzle", pos: "名詞・動詞", kana: "ドリズル", ja: "小雨／小雨が降る", ex: "It started to drizzle just as we left the house.", exJa: "家を出たとたん小雨が降り出した。", cat: "日常会話" },
  { en: "run errands", pos: "動詞句", kana: "ラン・エランズ", ja: "用事を済ませる", ex: "I ran errands all morning before the trip.", exJa: "旅行の前、午前中ずっと用事を済ませていた。", cat: "日常会話" },
  { en: "apologetic", pos: "形容詞", kana: "アポロジェティック", ja: "申し訳なさそうな", ex: "He sounded apologetic on the phone.", exJa: "彼は電話口で申し訳なさそうだった。", cat: "日常会話" },
  { en: "awkward", pos: "形容詞", kana: "オークワード", ja: "気まずい", ex: "There was an awkward silence after his comment.", exJa: "彼の発言の後、気まずい沈黙が流れた。", cat: "日常会話" },
  { en: "casual", pos: "形容詞", kana: "キャジュアル", ja: "気軽な・カジュアルな", ex: "It's just a casual dinner, so don't dress up.", exJa: "ただの気軽な夕食だから着飾らなくていいよ。", cat: "日常会話" },
  { en: "formal", pos: "形容詞", kana: "フォーマル", ja: "正式な", ex: "The invitation asked for formal attire.", exJa: "その招待状では正式な服装が求められていた。", cat: "日常会話" },
  { en: "catch up", pos: "動詞句", kana: "キャッチ・アップ", ja: "近況を語り合う", ex: "Let's catch up over coffee sometime this week.", exJa: "今週どこかでコーヒーを飲みながら近況を話そう。", cat: "日常会話" },
  { en: "get along", pos: "動詞句", kana: "ゲット・アロング", ja: "仲良くやる", ex: "My roommate and I get along really well.", exJa: "ルームメイトと私はとても仲良くやっている。", cat: "日常会話" },
  { en: "hang out", pos: "動詞句", kana: "ハング・アウト", ja: "遊ぶ・過ごす", ex: "We usually hang out at the park on Sundays.", exJa: "私たちは日曜日にたいてい公園で過ごす。", cat: "日常会話" },
  { en: "show up", pos: "動詞句", kana: "ショー・アップ", ja: "現れる", ex: "He didn't show up to the meeting on time.", exJa: "彼は会議に時間通りに現れなかった。", cat: "日常会話" },
  { en: "run late", pos: "動詞句", kana: "ラン・レイト", ja: "遅れる", ex: "Sorry, I'm running late because of traffic.", exJa: "渋滞のせいで遅れています、すみません。", cat: "日常会話" },
  { en: "look forward to", pos: "動詞句", kana: "ルック・フォワード・トゥ", ja: "楽しみにする", ex: "I'm really looking forward to the weekend.", exJa: "週末を本当に楽しみにしている。", cat: "日常会話" },
  { en: "get in touch", pos: "動詞句", kana: "ゲット・イン・タッチ", ja: "連絡を取る", ex: "Please get in touch if anything changes.", exJa: "何か変更があれば連絡してください。", cat: "日常会話" },
  { en: "keep in touch", pos: "動詞句", kana: "キープ・イン・タッチ", ja: "連絡を取り続ける", ex: "We promised to keep in touch after graduation.", exJa: "私たちは卒業後も連絡を取り合うと約束した。", cat: "日常会話" },
  { en: "figure out", pos: "動詞句", kana: "フィギュア・アウト", ja: "解決する・理解する", ex: "It took a while to figure out the directions.", exJa: "道順を理解するのに時間がかかった。", cat: "日常会話" },
  { en: "put off", pos: "動詞句", kana: "プット・オフ", ja: "先延ばしにする", ex: "Don't put off your homework until the last minute.", exJa: "宿題をぎりぎりまで先延ばしにしないで。", cat: "日常会話" },
  { en: "bring up", pos: "動詞句", kana: "ブリング・アップ", ja: "話題に出す", ex: "She brought up the topic during dinner.", exJa: "彼女は夕食中にその話題を出した。", cat: "日常会話" },
  { en: "come up with", pos: "動詞句", kana: "カム・アップ・ウィズ", ja: "思いつく", ex: "He came up with a great idea for the trip.", exJa: "彼は旅行のための素晴らしいアイデアを思いついた。", cat: "日常会話" },
  { en: "get over", pos: "動詞句", kana: "ゲット・オーバー", ja: "乗り越える", ex: "It took her a while to get over the disappointment.", exJa: "彼女がその失望を乗り越えるには時間がかかった。", cat: "日常会話" },
  { en: "count on", pos: "動詞句", kana: "カウント・オン", ja: "頼りにする", ex: "You can always count on him for advice.", exJa: "アドバイスなら彼をいつでも頼りにできる。", cat: "日常会話" },
  { en: "go over", pos: "動詞句", kana: "ゴー・オーバー", ja: "確認する・見直す", ex: "Let's go over the plan one more time.", exJa: "もう一度計画を確認しましょう。", cat: "日常会話" },
  { en: "point out", pos: "動詞句", kana: "ポイント・アウト", ja: "指摘する", ex: "She politely pointed out my mistake.", exJa: "彼女は私の間違いを丁寧に指摘してくれた。", cat: "日常会話" },
  { en: "take turns", pos: "動詞句", kana: "テイク・ターンズ", ja: "交代でする", ex: "We took turns driving on the long trip.", exJa: "私たちは長い旅行で運転を交代でした。", cat: "日常会話" },
  { en: "make up", pos: "動詞句", kana: "メイク・アップ", ja: "仲直りする・でっち上げる", ex: "They finally made up after the argument.", exJa: "彼らは口論の後、ついに仲直りした。", cat: "日常会話" },
  { en: "break the ice", pos: "慣用句", kana: "ブレイク・ジ・アイス", ja: "打ち解ける", ex: "He told a joke to break the ice at the party.", exJa: "彼はパーティーで打ち解けるために冗談を言った。", cat: "日常会話" },
  { en: "get straight to the point", pos: "慣用句", kana: "ゲット・ストレート・トゥ・ザ・ポイント", ja: "単刀直入に言う", ex: "Let me get straight to the point about the schedule.", exJa: "スケジュールについて単刀直入に言わせてください。", cat: "日常会話" },
  { en: "change the subject", pos: "動詞句", kana: "チェンジ・ザ・サブジェクト", ja: "話題を変える", ex: "He tried to change the subject when asked about money.", exJa: "お金について聞かれると彼は話題を変えようとした。", cat: "日常会話" },
  { en: "keep an eye on", pos: "動詞句", kana: "キープ・アン・アイ・オン", ja: "気をつけて見る", ex: "Could you keep an eye on my bag for a minute?", exJa: "少しの間、私のバッグを見ていてもらえますか。", cat: "日常会話" },
  { en: "give someone a hand", pos: "慣用句", kana: "ギヴ・サムワン・ア・ハンド", ja: "手を貸す", ex: "Could you give me a hand with these boxes?", exJa: "この箱を運ぶのを手伝ってもらえますか。", cat: "日常会話" },
  { en: "small favor", pos: "名詞", kana: "スモール・フェイヴァー", ja: "ちょっとした頼み", ex: "It's just a small favor, so it won't take long.", exJa: "ちょっとした頼みだから時間はかからないよ。", cat: "日常会話" },
  { en: "polite request", pos: "名詞", kana: "ポライト・リクエスト", ja: "丁寧な頼み方", ex: "He made a polite request to leave early.", exJa: "彼は早退させてほしいと丁寧に頼んだ。", cat: "日常会話" },
  { en: "straightforward", pos: "形容詞", kana: "ストレートフォワード", ja: "率直な・分かりやすい", ex: "She gave a straightforward answer to the question.", exJa: "彼女はその質問に率直な答えをした。", cat: "日常会話" },
  { en: "vague", pos: "形容詞", kana: "ヴェイグ", ja: "曖昧な", ex: "His explanation was too vague to understand.", exJa: "彼の説明は理解するには曖昧すぎた。", cat: "日常会話" },
  { en: "specific", pos: "形容詞", kana: "スペシフィック", ja: "具体的な", ex: "Could you be more specific about the time?", exJa: "時間についてもっと具体的に言ってもらえますか。", cat: "日常会話" },
  { en: "brief", pos: "形容詞・動詞", kana: "ブリーフ", ja: "簡潔な／概要を伝える", ex: "He gave a brief summary of the meeting.", exJa: "彼は会議の簡潔な概要を伝えた。", cat: "日常会話" },
  { en: "mention in passing", pos: "動詞句", kana: "メンション・イン・パッシング", ja: "ついでに言う", ex: "She mentioned in passing that she was moving.", exJa: "彼女は引っ越すことをついでに言った。", cat: "日常会話" },
  { en: "bring someone up to date", pos: "動詞句", kana: "ブリング・アップ・トゥ・デイト", ja: "近況を伝える", ex: "Let me bring you up to date on the project.", exJa: "そのプロジェクトについて近況を伝えさせてください。", cat: "日常会話" },
  { en: "in a good mood", pos: "慣用句", kana: "イン・ア・グッド・ムード", ja: "機嫌がいい", ex: "He's always in a good mood on Fridays.", exJa: "彼は金曜日はいつも機嫌がいい。", cat: "日常会話" },
  { en: "in a bad mood", pos: "慣用句", kana: "イン・ア・バッド・ムード", ja: "機嫌が悪い", ex: "She's been in a bad mood since this morning.", exJa: "彼女は今朝からずっと機嫌が悪い。", cat: "日常会話" },
  { en: "patience", pos: "名詞", kana: "ペイシェンス", ja: "忍耐", ex: "It takes patience to teach young children.", exJa: "幼い子供を教えるには忍耐が必要だ。", cat: "日常会話" },
  { en: "patient", pos: "形容詞", kana: "ペイシェント", ja: "我慢強い", ex: "Please be patient; the food will arrive soon.", exJa: "少し待ってください。食べ物はすぐ届きます。", cat: "日常会話" },
  { en: "impatient", pos: "形容詞", kana: "インペイシェント", ja: "せっかちな", ex: "He got impatient waiting in the long line.", exJa: "彼は長い列に並んで待つのにせっかちになった。", cat: "日常会話" },
  { en: "sympathize", pos: "動詞", kana: "シンパサイズ", ja: "同情する", ex: "I really sympathize with what you're going through.", exJa: "あなたが経験していることに本当に同情する。", cat: "日常会話" },
  { en: "empathy", pos: "名詞", kana: "エンパシー", ja: "共感", ex: "Good listeners often show a lot of empathy.", exJa: "聞き上手な人はよく多くの共感を示す。", cat: "日常会話" },
  { en: "comfort", pos: "動詞・名詞", kana: "コンフォート", ja: "慰める／慰め", ex: "She tried to comfort her crying friend.", exJa: "彼女は泣いている友人を慰めようとした。", cat: "日常会話" },
  { en: "encourage", pos: "動詞", kana: "エンカレッジ", ja: "励ます", ex: "His coach encouraged him to keep trying.", exJa: "コーチは彼に挑戦し続けるよう励ました。", cat: "日常会話" },
  { en: "advise", pos: "動詞", kana: "アドヴァイズ", ja: "助言する", ex: "My doctor advised me to get more sleep.", exJa: "医者はもっと睡眠をとるよう私に助言した。", cat: "日常会話" },
  { en: "give someone a call", pos: "動詞句", kana: "ギヴ・サムワン・ア・コール", ja: "電話する", ex: "I'll give you a call once I get home.", exJa: "家に着いたら電話するね。", cat: "日常会話" },
  { en: "promise", pos: "名詞・動詞", kana: "プロミス", ja: "約束／約束する", ex: "He promised to call as soon as he arrived.", exJa: "彼は到着次第すぐに電話すると約束した。", cat: "日常会話" },
  { en: "keep a promise", pos: "動詞句", kana: "キープ・ア・プロミス", ja: "約束を守る", ex: "She always keeps her promises to her friends.", exJa: "彼女はいつも友人への約束を守る。", cat: "日常会話" },
  { en: "break a promise", pos: "動詞句", kana: "ブレイク・ア・プロミス", ja: "約束を破る", ex: "It hurt when he broke his promise again.", exJa: "彼がまた約束を破ったとき傷ついた。", cat: "日常会話" },
  { en: "gossip about", pos: "動詞句", kana: "ゴシップ・アバウト", ja: "うわさ話をする", ex: "It's not nice to gossip about coworkers.", exJa: "同僚のうわさ話をするのはよくない。", cat: "日常会話" },
  { en: "keep something to yourself", pos: "慣用句", kana: "キープ・サムシング・トゥ・ユアセルフ", ja: "自分の胸にしまっておく", ex: "Please keep this to yourself for now.", exJa: "今のところこれは自分の胸にしまっておいてください。", cat: "日常会話" },
  { en: "spill the beans", pos: "慣用句", kana: "スピル・ザ・ビーンズ", ja: "秘密をばらす", ex: "He accidentally spilled the beans about the surprise.", exJa: "彼はうっかりそのサプライズの秘密をばらしてしまった。", cat: "日常会話" },
  { en: "read between the lines", pos: "慣用句", kana: "リード・ビトゥイーン・ザ・ラインズ", ja: "行間を読む", ex: "You need to read between the lines with him.", exJa: "彼に関しては行間を読む必要がある。", cat: "日常会話" },
  { en: "beat around the bush", pos: "慣用句", kana: "ビート・アラウンド・ザ・ブッシュ", ja: "遠回しに言う", ex: "Stop beating around the bush and tell me the truth.", exJa: "遠回しに言うのはやめて本当のことを言って。", cat: "日常会話" },
  { en: "on the same page", pos: "慣用句", kana: "オン・ザ・セイム・ページ", ja: "同じ考えである", ex: "Let's make sure we're on the same page before we start.", exJa: "始める前にお互い同じ考えであることを確認しよう。", cat: "日常会話" },
  { en: "out of the blue", pos: "慣用句", kana: "アウト・オブ・ザ・ブルー", ja: "突然", ex: "He called me out of the blue after years.", exJa: "何年ぶりかに彼が突然電話をかけてきた。", cat: "日常会話" },
  { en: "a piece of cake", pos: "慣用句", kana: "ア・ピース・オブ・ケイク", ja: "とても簡単なこと", ex: "The test was a piece of cake for her.", exJa: "そのテストは彼女にとってとても簡単だった。", cat: "日常会話" },
  { en: "give it a shot", pos: "慣用句", kana: "ギヴ・イット・ア・ショット", ja: "試してみる", ex: "I've never tried sushi, but I'll give it a shot.", exJa: "寿司を食べたことはないけど試してみるよ。", cat: "日常会話" },
  { en: "get used to", pos: "動詞句", kana: "ゲット・ユーズド・トゥ", ja: "慣れる", ex: "It took a while to get used to the new schedule.", exJa: "新しいスケジュールに慣れるのに時間がかかった。", cat: "日常会話" },
  { en: "used to", pos: "助動詞句", kana: "ユーズド・トゥ", ja: "以前は～した", ex: "I used to live in a small town.", exJa: "私は以前小さな町に住んでいた。", cat: "日常会話" },
  { en: "mixed feelings", pos: "名詞", kana: "ミクスト・フィーリングズ", ja: "複雑な気持ち", ex: "I have mixed feelings about moving abroad.", exJa: "海外に引っ越すことについて複雑な気持ちがある。", cat: "日常会話" },
  { en: "second thoughts", pos: "名詞", kana: "セカンド・ソーツ", ja: "考え直すこと", ex: "I'm having second thoughts about the trip.", exJa: "その旅行について考え直している。", cat: "日常会話" },
  { en: "change one's mind", pos: "動詞句", kana: "チェンジ・ワンズ・マインド", ja: "考えを変える", ex: "She changed her mind at the last minute.", exJa: "彼女は土壇場で考えを変えた。", cat: "日常会話" },
  { en: "make up one's mind", pos: "動詞句", kana: "メイク・アップ・ワンズ・マインド", ja: "決心する", ex: "He finally made up his mind to quit smoking.", exJa: "彼はついに禁煙を決心した。", cat: "日常会話" },
  { en: "weigh the options", pos: "動詞句", kana: "ウェイ・ジ・オプションズ", ja: "選択肢をよく検討する", ex: "We should weigh the options before deciding.", exJa: "決める前に選択肢をよく検討すべきだ。", cat: "日常会話" },
  { en: "take it easy", pos: "慣用句", kana: "テイク・イット・イージー", ja: "気楽にやる", ex: "Take it easy this weekend and just rest.", exJa: "今週末は気楽にして、ただ休んで。", cat: "日常会話" },
  { en: "get carried away", pos: "動詞句", kana: "ゲット・キャリード・アウェイ", ja: "調子に乗る・夢中になる", ex: "Sorry, I got carried away talking about my trip.", exJa: "旅行の話に夢中になってしまってごめんね。", cat: "日常会話" },
  { en: "lose track of time", pos: "慣用句", kana: "ルーズ・トラック・オブ・タイム", ja: "時間を忘れる", ex: "We lost track of time chatting on the phone.", exJa: "電話でおしゃべりしていて時間を忘れてしまった。", cat: "日常会話" },
  { en: "run out of time", pos: "動詞句", kana: "ラン・アウト・オブ・タイム", ja: "時間が足りなくなる", ex: "We ran out of time before finishing the game.", exJa: "ゲームを終える前に時間が足りなくなった。", cat: "日常会話" },
  { en: "in the mood for", pos: "慣用句", kana: "イン・ザ・ムード・フォー", ja: "～する気分である", ex: "I'm not really in the mood for a big meal tonight.", exJa: "今夜はあまりがっつり食べる気分ではない。", cat: "日常会話" },
  { en: "feel like", pos: "動詞句", kana: "フィール・ライク", ja: "～したい気分だ", ex: "I feel like going for a walk after dinner.", exJa: "夕食後に散歩に行きたい気分だ。", cat: "日常会話" },
  { en: "care about", pos: "動詞句", kana: "ケア・アバウト", ja: "気にかける", ex: "She really cares about her friends' feelings.", exJa: "彼女は本当に友人の気持ちを気にかけている。", cat: "日常会話" },
  { en: "depend on", pos: "動詞句", kana: "ディペンド・オン", ja: "頼る・次第である", ex: "Whether we go depends on the weather.", exJa: "行くかどうかは天気次第だ。", cat: "日常会話" },
  { en: "get to know", pos: "動詞句", kana: "ゲット・トゥ・ノウ", ja: "知り合う", ex: "It's nice to get to know your new coworkers.", exJa: "新しい同僚と知り合うのは楽しい。", cat: "日常会話" },
  { en: "hit it off", pos: "慣用句", kana: "ヒット・イット・オフ", ja: "すぐに意気投合する", ex: "They hit it off right away at the party.", exJa: "彼らはパーティーですぐに意気投合した。", cat: "日常会話" },
  { en: "stay in touch", pos: "動詞句", kana: "ステイ・イン・タッチ", ja: "連絡を取り合う", ex: "Let's stay in touch even after you move.", exJa: "引っ越した後も連絡を取り合おう。", cat: "日常会話" },
  { en: "lose touch", pos: "動詞句", kana: "ルーズ・タッチ", ja: "連絡が途絶える", ex: "We lost touch after high school.", exJa: "高校卒業後、私たちは連絡が途絶えた。", cat: "日常会話" },
  { en: "look after", pos: "動詞句", kana: "ルック・アフター", ja: "世話をする", ex: "Can you look after my cat this weekend?", exJa: "今週末、私の猫の世話をしてもらえますか。", cat: "日常会話" },
  { en: "run into", pos: "動詞句", kana: "ラン・イントゥ", ja: "偶然出会う", ex: "I ran into an old friend at the station.", exJa: "駅で昔の友人に偶然出会った。", cat: "日常会話" },
  { en: "bump into", pos: "動詞句", kana: "バンプ・イントゥ", ja: "ばったり会う", ex: "I bumped into my teacher at the supermarket.", exJa: "スーパーで先生にばったり会った。", cat: "日常会話" },
  { en: "drop by", pos: "動詞句", kana: "ドロップ・バイ", ja: "ちょっと立ち寄る", ex: "Feel free to drop by anytime this week.", exJa: "今週いつでも気軽に立ち寄ってください。", cat: "日常会話" },
  { en: "swing by", pos: "動詞句", kana: "スウィング・バイ", ja: "ちょっと立ち寄る", ex: "I'll swing by your place after work.", exJa: "仕事の後にあなたの家にちょっと立ち寄るね。", cat: "日常会話" },
  { en: "stop by", pos: "動詞句", kana: "ストップ・バイ", ja: "立ち寄る", ex: "Let's stop by the bakery on the way home.", exJa: "帰り道にパン屋に立ち寄ろう。", cat: "日常会話" },
  { en: "check in", pos: "動詞句", kana: "チェック・イン", ja: "様子を確認する", ex: "I'll check in with you tomorrow morning.", exJa: "明日の朝、あなたに様子を確認するね。", cat: "日常会話" },
  { en: "touch base", pos: "慣用句", kana: "タッチ・ベース", ja: "近況報告し合う", ex: "Let's touch base again next week.", exJa: "来週またお互いの近況を報告し合おう。", cat: "日常会話" },
  { en: "keep someone posted", pos: "慣用句", kana: "キープ・サムワン・ポステッド", ja: "経過を知らせる", ex: "I'll keep you posted on how the interview goes.", exJa: "面接がどうだったか経過を知らせるね。", cat: "日常会話" },
  { en: "get back to", pos: "動詞句", kana: "ゲット・バック・トゥ", ja: "後で連絡する", ex: "I'll get back to you by tomorrow afternoon.", exJa: "明日の午後までにあなたに連絡します。", cat: "日常会話" },
  { en: "hold on", pos: "動詞句", kana: "ホールド・オン", ja: "少し待つ", ex: "Hold on a second, I need to grab my phone.", exJa: "ちょっと待って、携帯を取ってくるから。", cat: "日常会話" },
  { en: "never mind", pos: "慣用句", kana: "ネヴァー・マインド", ja: "気にしないで", ex: "Never mind, it wasn't important anyway.", exJa: "気にしないで、どうせ大したことじゃなかったから。", cat: "日常会話" },
  { en: "no big deal", pos: "慣用句", kana: "ノー・ビッグ・ディール", ja: "大したことではない", ex: "Don't worry, it's no big deal at all.", exJa: "心配しないで、全然大したことじゃないから。", cat: "日常会話" },
  { en: "by the way", pos: "慣用句", kana: "バイ・ザ・ウェイ", ja: "ところで", ex: "By the way, did you finish the report?", exJa: "ところで、その報告書は終わりましたか。", cat: "日常会話" },
  { en: "come to think of it", pos: "慣用句", kana: "カム・トゥ・シンク・オブ・イット", ja: "そういえば", ex: "Come to think of it, I never called him back.", exJa: "そういえば、彼に折り返し電話するのを忘れていた。", cat: "日常会話" },
  { en: "as far as I know", pos: "慣用句", kana: "アズ・ファー・アズ・アイ・ノウ", ja: "私の知る限り", ex: "As far as I know, the store is still open.", exJa: "私の知る限り、その店はまだ開いている。", cat: "日常会話" },
  { en: "if I'm not mistaken", pos: "慣用句", kana: "イフ・アイム・ノット・ミステイクン", ja: "もし間違っていなければ", ex: "If I'm not mistaken, the train leaves at nine.", exJa: "もし間違っていなければ、その電車は9時に出発する。", cat: "日常会話" },
  { en: "to be honest", pos: "慣用句", kana: "トゥ・ビー・オネスト", ja: "正直に言うと", ex: "To be honest, I forgot about the meeting.", exJa: "正直に言うと、その会議のことを忘れていた。", cat: "日常会話" },
  { en: "in my opinion", pos: "慣用句", kana: "イン・マイ・オピニオン", ja: "私の意見では", ex: "In my opinion, the plan needs more time.", exJa: "私の意見では、その計画にはもっと時間が必要だ。", cat: "日常会話" },
  { en: "as a matter of fact", pos: "慣用句", kana: "アズ・ア・マター・オブ・ファクト", ja: "実を言うと", ex: "As a matter of fact, I already bought the tickets.", exJa: "実を言うと、もうチケットは買ってある。", cat: "日常会話" },
  { en: "apology", pos: "名詞", kana: "アポロジー", ja: "謝罪", ex: "He wrote a short apology after the argument.", exJa: "彼はその口論の後、短い謝罪文を書いた。", cat: "日常会話" },
  { en: "invitation", pos: "名詞", kana: "インヴィテーション", ja: "招待", ex: "We received an invitation to her wedding.", exJa: "彼女の結婚式への招待状を受け取った。", cat: "日常会話" },
  { en: "conversation", pos: "名詞", kana: "コンヴァセーション", ja: "会話", ex: "The conversation drifted from work to travel plans.", exJa: "会話は仕事から旅行の計画へと移っていった。", cat: "日常会話" },
];
